"""Curated content for the multi-subject learning system.

Subjects: AL Economics (CIE-style), IB Business Management, AL Business (CIE-style),
and Competition Knowledge (Conrad / BPA + 赛代学). IB Economics content lives in
content.py and is reused as-is.

Each subject: syllabus (units -> topics, level: as/a2/hl/both), glossary,
assessment, quiz (MCQ with explanations). Topics carry exam_tips inline.
"""

# ===========================================================================
# AL ECONOMICS (CIE 9708 style)
# ===========================================================================

AL_ECON = {
    "id": "al-econ", "name_zh": "AL 经济学", "name_en": "A-Level Economics",
    "accent": "#0ea5a4", "level_names": {"as": "AS", "a2": "A2", "both": "AS + A2"},
    "syllabus": [
        {"id": "al-e1", "order": 1, "title_en": "Scarcity & Choice", "title_zh": "稀缺与选择",
         "short_zh": "基本问题", "topics": [
            {"id": "AE1.1", "title_en": "Basic economic problem", "title_zh": "基本经济问题", "level": "as",
             "desc_zh": "稀缺性、选择、机会成本与生产要素；经济品的分类。",
             "key_concepts": ["Scarcity", "Opportunity cost", "Factors of production"],
             "exam_tips": ["务必用 opportunity cost 的标准定义 \"the next best alternative forgone\"。",
                            "PPC 内点＝无效率、外点＝不可达、整条外移＝经济增长，三态要分清。"]},
            {"id": "AE1.2", "title_en": "Resource allocation & economic systems", "title_zh": "资源配置与经济体制", "level": "as",
             "desc_zh": "市场/计划/混合经济；生产什么、如何生产、为谁生产。",
             "key_concepts": ["Market economy", "Planned economy", "Mixed economy"],
             "exam_tips": ["比较三种体制时从 效率 / 公平 / 激励 三个维度展开。"]},
        ]},
        {"id": "al-e2", "order": 2, "title_en": "Markets & Elasticity", "title_zh": "市场与弹性",
         "short_zh": "市场机制", "topics": [
            {"id": "AE2.1", "title_en": "Demand, supply & equilibrium", "title_zh": "需求、供给与均衡", "level": "as",
             "desc_zh": "需求/供给定律、movement 与 shift、均衡与失衡的调整。",
             "key_concepts": ["Law of demand", "Law of supply", "Equilibrium"],
             "exam_tips": ["区分 movement along（价格本身）与 shift（非价格因素）是必考点。"]},
            {"id": "AE2.2", "title_en": "Elasticity (PED, XED, YED, PES)", "title_zh": "四种弹性", "level": "as",
             "desc_zh": "弹性的计算、分类、决定因素与应用（定价、税收归宿）。",
             "key_concepts": ["PED", "YED", "XED", "PES"],
             "exam_tips": ["PED=ΔQ%/ΔP%（负号省略）；收入检验：elastic 降价增收。",
                            "税收归宿：弹性小的一方承担更多税负，要能画图说明。"]},
            {"id": "AE2.3", "title_en": "Consumer & producer surplus", "title_zh": "消费者与生产者剩余", "level": "as",
             "desc_zh": "剩余的图形含义与政策对剩余（福利）的影响。",
             "key_concepts": ["Consumer surplus", "Producer surplus", "Welfare"],
             "exam_tips": ["关税/间接税题：指出 CS、PS、政府收入与 deadweight loss 的面积变化。"]},
            {"id": "AE2.4", "title_en": "Indirect taxes & subsidies", "title_zh": "间接税与补贴", "level": "as",
             "desc_zh": "从量/从价税、补贴对均衡的影响与归宿分析。",
             "key_concepts": ["Specific tax", "Ad valorem tax", "Subsidy"],
             "exam_tips": ["从量税＝供给曲线平行上移；从价税＝绕原点旋转（变得更陡）。"]},
        ]},
        {"id": "al-e3", "order": 3, "title_en": "Market Failure & Government Intervention", "title_zh": "市场失灵与政府干预",
         "short_zh": "市场失灵", "topics": [
            {"id": "AE3.1", "title_en": "Externalities & public goods", "title_zh": "外部性与公共物品", "level": "as",
             "desc_zh": "正负外部性、公共物品、搭便车与福利损失。",
             "key_concepts": ["Externality", "Public goods", "Market failure"],
             "exam_tips": ["画 MSC/MPC（或 MSB/MPB）并标注 socially optimal output 与 DWL。"]},
            {"id": "AE3.2", "title_en": "Merit/demerit goods & information gaps", "title_zh": "优值/劣值品与信息不对称", "level": "as",
             "desc_zh": "信息不完全导致消费过度或不足；政府信息提供。",
             "key_concepts": ["Merit goods", "Demerit goods", "Information failure"],
             "exam_tips": ["区别\"市场失灵\"与\"政府失灵\"——干预的副作用要会评估。"]},
            {"id": "AE3.3", "title_en": "Regulation, tradable permits & privatisation", "title_zh": "管制、可交易许可与私有化", "level": "a2",
             "desc_zh": "最高/最低价、碳交易、国有化与私有化的利弊评估。",
             "key_concepts": ["Price ceiling", "Cap-and-trade", "Privatisation"],
             "exam_tips": ["评估题：干预的有效性取决于 PED、执行成本与信息。"]},
        ]},
        {"id": "al-e4", "order": 4, "title_en": "Theory of Firm & Market Structures", "title_zh": "厂商理论与市场结构",
         "short_zh": "厂商理论", "topics": [
            {"id": "AE4.1", "title_en": "Production & cost theory", "title_zh": "生产与成本理论", "level": "as",
             "desc_zh": "TP/AP/MP、固定与可变成本、AC/MC、规模经济与不经济。",
             "key_concepts": ["Economies of scale", "Marginal cost", "Average cost"],
             "exam_tips": ["MC 过 AC 最低点是画图必标点；规模经济类型（内部/外部）要能举例。"]},
            {"id": "AE4.2", "title_en": "Revenue & profit maximisation", "title_zh": "收益与利润最大化", "level": "as",
             "desc_zh": "TR/AR/MR、正常与超额利润、MC=MR 原则。",
             "key_concepts": ["Total revenue", "Marginal revenue", "Normal profit"],
             "exam_tips": ["正常利润计入成本（AC 包含 normal profit），长期完全竞争只赚正常利润。"]},
            {"id": "AE4.3", "title_en": "Perfect competition & monopoly", "title_zh": "完全竞争与垄断", "level": "as",
             "desc_zh": "两种极端结构的短期/长期均衡、效率比较。",
             "key_concepts": ["Perfect competition", "Monopoly", "Allocative efficiency"],
             "exam_tips": ["垄断无效率三连：价高、量少、DWL；但注意自然垄断与规模经济的辩护。"]},
            {"id": "AE4.4", "title_en": "Oligopoly & contestability", "title_zh": "寡头与可竞争市场", "level": "a2",
             "desc_zh": "非价格竞争、进入壁垒与可竞争市场理论。",
             "key_concepts": ["Oligopoly", "Barriers to entry", "Contestable market"],
             "exam_tips": ["CIE 常考 advertising 的利弊两面评估。"]},
            {"id": "AE4.5", "title_en": "Price discrimination", "title_zh": "价格歧视", "level": "a2",
             "desc_zh": "三级价格歧视的条件、图形与福利影响。",
             "key_concepts": ["Price discrimination", "Consumer surplus"],
             "exam_tips": ["三个条件：市场分割、弹性差异、无转售；用弹性差解释定价差。"]},
            {"id": "AE4.6", "title_en": "Utility & consumer choice", "title_zh": "效用与消费者选择", "level": "a2",
             "desc_zh": "边际效用递减、 equi-marginal 原则与需求曲线推导。",
             "key_concepts": ["Marginal utility", "Diminishing returns"],
             "exam_tips": [" equi-marginal principle：MUa/Pa = MUb/Pb。"]},
            {"id": "AE4.7", "title_en": "Labour market & wage determination", "title_zh": "劳动市场与工资决定", "level": "a2",
             "desc_zh": "劳动供求、工会、最低工资、歧视与移民。",
             "key_concepts": ["MRP theory", "Trade union", "Minimum wage"],
             "exam_tips": ["劳动需求由 MRP（边际收益产品）决定；最低工资按弹性分情况评估。"]},
        ]},
        {"id": "al-e5", "order": 5, "title_en": "Macroeconomy", "title_zh": "宏观经济",
         "short_zh": "宏观", "topics": [
            {"id": "AE5.1", "title_en": "National income & GDP", "title_zh": "国民收入与 GDP", "level": "as",
             "desc_zh": "GDP/GNP/NNP 的定义、三种计算法与名义/实际区分。",
             "key_concepts": ["GDP", "Real vs nominal", "Circular flow"],
             "exam_tips": ["比较生活水平时必须提到 GDP 的局限（非市场活动/分配/环境）。"]},
            {"id": "AE5.2", "title_en": "AD/AS analysis", "title_zh": "AD/AS 分析", "level": "as",
             "desc_zh": "AD 构成、凯恩斯与新古典 AS、均衡与移动。",
             "key_concepts": ["Aggregate demand", "Aggregate supply"],
             "exam_tips": ["写清\"什么因素→哪条曲线→哪方向→对 P 和 Y 的影响\"四步链条。"]},
            {"id": "AE5.3", "title_en": "Inflation & unemployment", "title_zh": "通胀与失业", "level": "as",
             "desc_zh": "CPI、通胀成因（需求拉动/成本推动）、失业类型与权衡。",
             "key_concepts": ["CPI", "Demand-pull inflation", "Phillips curve"],
             "exam_tips": ["区分通胀的两种成因决定政策处方完全不同。"]},
            {"id": "AE5.4", "title_en": "Macro policies", "title_zh": "宏观政策", "level": "as",
             "desc_zh": "财政/货币/供给侧政策的工具、传导与局限。",
             "key_concepts": ["Fiscal policy", "Monetary policy", "Supply-side policy"],
             "exam_tips": ["评估三步：时滞、副作用（挤出/通胀）、目标冲突。"]},
            {"id": "AE5.5", "title_en": "Poverty & inequality", "title_zh": "贫困与不平等", "level": "a2",
             "desc_zh": "绝对/相对贫困、洛伦兹曲线与基尼、再分配政策。",
             "key_concepts": ["Lorenz curve", "Gini coefficient"],
             "exam_tips": ["再分配政策的 trade-off：公平 vs 激励（效率）。"]},
        ]},
        {"id": "al-e6", "order": 6, "title_en": "International & Development", "title_zh": "国际与发展",
         "short_zh": "国际经济", "topics": [
            {"id": "AE6.1", "title_en": "International trade", "title_zh": "国际贸易", "level": "as",
             "desc_zh": "绝对/比较优势、贸易收益、保护主义及其评估。",
             "key_concepts": ["Comparative advantage", "Tariff", "Protectionism"],
             "exam_tips": ["比较优势看机会成本；贸易条件(ToT)变化对收益分配的影响是 A2 高频。"]},
            {"id": "AE6.2", "title_en": "Balance of payments & exchange rates", "title_zh": "国际收支与汇率", "level": "as",
             "desc_zh": "经常/资本账户、汇率决定与贬值效应（Marshall-Lerner、J 曲线）。",
             "key_concepts": ["Current account", "Exchange rate", "Marshall-Lerner condition"],
             "exam_tips": ["贬值改善经常账户的前提：进出口需求弹性之和>1。"]},
            {"id": "AE6.3", "title_en": "Economic development", "title_zh": "经济发展", "level": "a2",
             "desc_zh": "增长 vs 发展、HDI 与其他指标、发展障碍与战略。",
             "key_concepts": ["Human Development Index", "Poverty trap", "FDI"],
             "exam_tips": ["发展战略评估：市场化 vs 干预、贸易 vs 援助，两派都要写。"]},
        ]},
    ],
    "assessment": {
        "note": "以 CIE 9708 近年考纲为参考（具体以当季 syllabus 为准）",
        "components": [
            {"id": "p1", "name_zh": "Paper 1 · 选择题 (AS)", "time": "1h15m", "marks": 30, "weight": 20,
             "note_zh": "30 道 MCQ，覆盖 AS 全部内容。"},
            {"id": "p2", "name_zh": "Paper 2 · 数据回应 (AS)", "time": "1h30m", "marks": 40, "weight": 30,
             "note_zh": "数据题＋小 essay，分 (a)(b)(c)(d) 递进。"},
            {"id": "p3", "name_zh": "Paper 3 · 选择题 (A2)", "time": "1h15m", "marks": 30, "weight": 20,
             "note_zh": "30 道 MCQ，AS+A2 全部内容。"},
            {"id": "p4", "name_zh": "Paper 4 · 数据回应与论文 (A2)", "time": "2h15m", "marks": 70, "weight": 30,
             "note_zh": "一道数据题＋一道 25 分论述文（评估为主）。"},
        ]},
    "glossary": [
        {"term_en": "Scarcity", "term_zh": "稀缺性", "topic": "AE1.1", "def_zh": "无限欲望 vs 有限资源的基本问题。"},
        {"term_en": "Opportunity cost", "term_zh": "机会成本", "topic": "AE1.1", "def_zh": "被放弃的次优选择的价值。"},
        {"term_en": "PED", "term_zh": "需求价格弹性", "topic": "AE2.2", "def_zh": "Q 变化% / P 变化%；>1 有弹性。"},
        {"term_en": "XED", "term_zh": "交叉价格弹性", "topic": "AE2.2", "def_zh": "替代品为正，互补品为负。"},
        {"term_en": "YED", "term_zh": "需求收入弹性", "topic": "AE2.2", "def_zh": "正常品为正；奢侈品>1；劣等品为负。"},
        {"term_en": "PES", "term_zh": "供给价格弹性", "topic": "AE2.2", "def_zh": "时间越长、闲置产能越多弹性越大。"},
        {"term_en": "Consumer surplus", "term_zh": "消费者剩余", "topic": "AE2.3", "def_zh": "愿付价与实付价之差。"},
        {"term_en": "Externality", "term_zh": "外部性", "topic": "AE3.1", "def_zh": "第三方承担的成本/收益，未入价。"},
        {"term_en": "Public goods", "term_zh": "公共物品", "topic": "AE3.1", "def_zh": "非竞争+非排他，市场供给不足。"},
        {"term_en": "Economies of scale", "term_zh": "规模经济", "topic": "AE4.1", "def_zh": "产量增加使长期平均成本下降。"},
        {"term_en": "Normal profit", "term_zh": "正常利润", "topic": "AE4.2", "def_zh": "刚好留住要素的最低利润，计入成本。"},
        {"term_en": "Monopoly", "term_zh": "垄断", "topic": "AE4.3", "def_zh": "单一卖者+进入壁垒，P>MC 无效率。"},
        {"term_en": "Price discrimination", "term_zh": "价格歧视", "topic": "AE4.5", "def_zh": "对同物不同人不同价（可分割/弹性异/无转售）。"},
        {"term_en": "MRP", "term_zh": "边际收益产品", "topic": "AE4.7", "def_zh": "劳动需求的基础：MP×MR。"},
        {"term_en": "Aggregate demand", "term_zh": "总需求", "topic": "AE5.2", "def_zh": "C+I+G+(X−M)。"},
        {"term_en": "Demand-pull inflation", "term_zh": "需求拉动通胀", "topic": "AE5.3", "def_zh": "AD 右移过热引起。"},
        {"term_en": "Cost-push inflation", "term_zh": "成本推动通胀", "topic": "AE5.3", "def_zh": "成本上升使 AS 左移引起。"},
        {"term_en": "Phillips curve", "term_zh": "菲利普斯曲线", "topic": "AE5.3", "def_zh": "短期通胀与失业的权衡关系。"},
        {"term_en": "Gini coefficient", "term_zh": "基尼系数", "topic": "AE5.5", "def_zh": "0=完全平等，1=完全不平等。"},
        {"term_en": "Comparative advantage", "term_zh": "比较优势", "topic": "AE6.1", "def_zh": "以更低机会成本生产。"},
        {"term_en": "Marshall-Lerner condition", "term_zh": "马歇尔-勒纳条件", "topic": "AE6.2", "def_zh": "贬值改善贸易收支的弹性条件（和>1）。"},
        {"term_en": "Terms of trade", "term_zh": "贸易条件", "topic": "AE6.1", "def_zh": "出口价指数/进口价指数×100。"},
        {"term_en": "HDI", "term_zh": "人类发展指数", "topic": "AE6.3", "def_zh": "收入+教育+寿命的复合发展指标。"},
    ],
    "quiz": [
        {"q": "咖啡价格上升导致咖啡需求量下降，这属于？", "opts": ["沿需求曲线移动", "需求曲线左移", "需求曲线右移", "供给曲线移动"], "a": 0, "why": "商品自身价格变化引起 movement along。"},
        {"q": "|PED| = 0.4 时降价 10%，总收入将？", "opts": ["下降", "上升", "不变", "无法判断"], "a": 0, "why": "无弹性商品量增幅小于价降幅，TR 下降。"},
        {"q": "两种商品 XED = +2.1，它们是？", "opts": ["替代品", "互补品", "无关品", "劣等品"], "a": 0, "why": "XED>0 为替代品。"},
        {"q": "公共物品市场供给不足的原因是？", "opts": ["搭便车问题", "规模不经济", "信息对称", "边际成本递增"], "a": 0, "why": "非排他性导致无人愿意付费。"},
        {"q": "从量税（specific tax）使供给曲线？", "opts": ["平行上移", "绕原点旋转", "平行下移", "不变"], "a": 0, "why": "从量税每单位固定金额，平行上移；从价税才旋转。"},
        {"q": "长期完全竞争均衡中企业？", "opts": ["只获正常利润", "获超额利润", "亏损", "P>MC"], "a": 0, "why": "自由进入退出使超额利润归零。"},
        {"q": "垄断企业利润最大化条件？", "opts": ["MC=MR", "P=MC", "AR=AC", "TR 最大"], "a": 0, "why": "任何结构下利润最大化都在 MC=MR。"},
        {"q": "成本推动通胀的图示是？", "opts": ["AS 左移", "AD 右移", "AS 右移", "AD 左移"], "a": 0, "why": "成本上升使 AS 左移，物价升产出降。"},
        {"q": "以下哪项是漏出（leakage）？", "opts": ["储蓄 S", "投资 I", "政府支出 G", "出口 X"], "a": 0, "why": "漏出=S+T+M；注入=I+G+X。"},
        {"q": "基尼系数变大意味着？", "opts": ["分配更不平等", "分配更平等", "通胀上升", "增长加快"], "a": 0, "why": "Gini 越接近 1 越不平等。"},
        {"q": "A 国生产 1 单位 X 放弃 2Y，B 国放弃 3Y，则？", "opts": ["A 在 X 上有比较优势", "B 在 X 上有比较优势", "A 绝对优势在 X", "无贸易基础"], "a": 0, "why": "机会成本更低者有比较优势。"},
        {"q": "贬值后经常账户先恶化后改善的现象叫？", "opts": ["J 曲线效应", "L 曲线效应", "马歇尔效应", "庇古效应"], "a": 0, "why": "短期价格效应、长期数量调整，呈 J 形。"},
        {"q": "最低工资高于均衡工资将导致？", "opts": ["劳动过剩（失业）", "劳动短缺", "工资下降", "无影响"], "a": 0, "why": "价格下限造成超额供给。"},
        {"q": "MC 曲线与 AC 曲线相交于？", "opts": ["AC 最低点", "AC 最高点", "原点", "MC 最低点"], "a": 0, "why": "MC 低于 AC 时拉低 AC，交于 AC 最低点。"},
        {"q": "以下哪项属于间接税？", "opts": ["增值税 VAT", "所得税", "公司税", "遗产税"], "a": 0, "why": "间接税对支出征收，可转嫁。"},
    ],
}

# ===========================================================================
# IB BUSINESS MANAGEMENT (2022 guide, first exams 2024)
# ===========================================================================

IB_BUS = {
    "id": "ib-bus", "name_zh": "IB 商业管理", "name_en": "IB Business Management",
    "accent": "#6366f1", "level_names": {"hl": "HL", "sl": "SL", "both": "SL + HL"},
    "syllabus": [
        {"id": "ib-b1", "order": 1, "title_en": "Business Organization & Environment", "title_zh": "商业组织与环境",
         "short_zh": "组织环境", "topics": [
            {"id": "BB1.1", "title_en": "Introduction to business management", "title_zh": "商业管理导论", "level": "both",
             "desc_zh": "企业家、企业类型（营利/非营利）、增值（added value）。",
             "key_concepts": ["Entrepreneur", "Added value", "Stakeholder"],
             "exam_tips": ["增值 = 产出价值 − 投入成本；用它解释企业存在的意义。"]},
            {"id": "BB1.2", "title_en": "Types of business entities", "title_zh": "企业组织形式", "level": "both",
             "desc_zh": "独资、合伙、公司（有限公司）；公营/私营/混合。",
             "key_concepts": ["Sole trader", "Partnership", "Limited liability"],
             "exam_tips": ["从责任、融资、控制权、税四个维度比较组织形式。"]},
            {"id": "BB1.3", "title_en": "Organizational objectives", "title_zh": "组织目标", "level": "both",
             "desc_zh": "愿景/使命/目标层级、SMART、企业社会责任(CSR)与 Porter 通用战略。",
             "key_concepts": ["Vision & mission", "SMART objectives", "CSR"],
             "exam_tips": ["目标层级：vision→mission→strategic→tactical→operational，要能排序。"]},
            {"id": "BB1.4", "title_en": "Stakeholders", "title_zh": "利益相关者", "level": "both",
             "desc_zh": "内部/外部/关联利益相关者，冲突与优先级。",
             "key_concepts": ["Internal stakeholders", "External stakeholders"],
             "exam_tips": ["分析题先分类，再谈\"权力-利益\"与冲突化解。"]},
            {"id": "BB1.5", "title_en": "External environment & growth", "title_zh": "外部环境与增长", "level": "both",
             "desc_zh": "STEEPLE 分析、内生/外延增长（并购）、Ansoff 矩阵。",
             "key_concepts": ["STEEPLE", "M&A", "Ansoff matrix"],
             "exam_tips": ["增长方式比较：内生（慢、稳）vs 并购（快、整合风险）。"]},
            {"id": "BB1.6", "title_en": "Organizational planning (HL)", "title_zh": "组织计划工具 (HL)", "level": "hl",
             "desc_zh": "鱼骨图、甘特图、决策树与强迫选择法。",
             "key_concepts": ["Gantt chart", "Decision tree"],
             "exam_tips": ["决策树计算 EV 后必须评估假设与偏差。"]},
        ]},
        {"id": "ib-b2", "order": 2, "title_en": "Human Resource Management", "title_zh": "人力资源管理",
         "short_zh": "人力", "topics": [
            {"id": "BB2.1", "title_en": "HRM & workforce planning", "title_zh": "人力资源管理与规划", "level": "both",
             "desc_zh": "招聘、解雇、劳动力的流动性（裁员/流失）。",
             "key_concepts": ["Recruitment", "Redundancy", "Labour turnover"],
             "exam_tips": ["labour turnover = 离职人数/总人数×100%，要会算并解释含义。"]},
            {"id": "BB2.2", "title_en": "Motivation & satisfaction", "title_zh": "激励与满意度", "level": "both",
             "desc_zh": "Taylor、Maslow、Herzberg、Adams 公平理论、Vroom 期望理论；金钱 vs 非金钱激励。",
             "key_concepts": ["Maslow", "Herzberg", "Expectancy theory"],
             "exam_tips": ["评价激励理论：普适性、文化差异、个体差异三点框架。"]},
            {"id": "BB2.3", "title_en": "Leadership (HL)", "title_zh": "领导力 (HL)", "level": "hl",
             "desc_zh": "领导风格（专制/民主/放任）、Goleman 六种风格。",
             "key_concepts": ["Autocratic", "Democratic", "Laissez-faire"],
             "exam_tips": ["没有最好风格，只有情境适配——答案要绑定案例情境。"]},
            {"id": "BB2.4", "title_en": "Culture & communication", "title_zh": "组织文化与沟通", "level": "both",
             "desc_zh": "Hofstede 文化维度（HL）、正式/非正式沟通与屏障。",
             "key_concepts": ["Corporate culture", "Barriers to communication"],
             "exam_tips": ["沟通障碍的解决要落到具体渠道与反馈机制。"]},
            {"id": "BB2.5", "title_en": "Industrial relations", "title_zh": "劳资关系", "level": "both",
             "desc_zh": "工会、集体谈判与劳资纠纷的处理。",
             "key_concepts": ["Trade union", "Collective bargaining"],
             "exam_tips": ["劳资冲突分析：双方利益→谈判筹码→外部环境。"]},
        ]},
        {"id": "ib-b3", "order": 3, "title_en": "Finance & Accounts", "title_zh": "财务与会计",
         "short_zh": "财务", "topics": [
            {"id": "BB3.1", "title_en": "Sources of finance", "title_zh": "融资来源", "level": "both",
             "desc_zh": "内部/外部、短期/长期/中期融资的匹配原则。",
             "key_concepts": ["Overdraft", "Debentures", "Leasing"],
             "exam_tips": ["匹配原则：短贷短用、长贷长用，错配是风险根源。"]},
            {"id": "BB3.2", "title_en": "Costs & revenues", "title_zh": "成本与收入", "level": "both",
             "desc_zh": "固定/可变成本、直接/间接成本、收入与成本结构。",
             "key_concepts": ["Fixed cost", "Variable cost", "Direct cost"],
             "exam_tips": ["区分 direct/indirect 与 fixed/variable 是两组不同维度。"]},
            {"id": "BB3.3", "title_en": "Final accounts", "title_zh": "期末报表", "level": "both",
             "desc_zh": "利润表（损益表）与资产负债表的结构与勾稽。",
             "key_concepts": ["Income statement", "Balance sheet", "Depreciation"],
             "exam_tips": ["资产负债表恒等式：资产=负债+权益。折旧两法（直线/余额递减）会算。"]},
            {"id": "BB3.4", "title_en": "Profitability & liquidity ratios", "title_zh": "盈利与流动性比率", "level": "both",
             "desc_zh": "毛利率、净利率、ROCE、流动比率、速动比率。",
             "key_concepts": ["Gross profit margin", "ROCE", "Current ratio"],
             "exam_tips": ["比率题三步：计算→对比（时间/行业）→解释原因。"]},
            {"id": "BB3.5", "title_en": "Efficiency ratios (HL)", "title_zh": "效率比率 (HL)", "level": "hl",
             "desc_zh": "存货周转、应收账款天数、应付账款天数。",
             "key_concepts": ["Stock turnover", " debtor days"],
             "exam_tips": ["周转太快也可能缺货——效率与安全的权衡。"]},
            {"id": "BB3.6", "title_en": "Cash flow", "title_zh": "现金流", "level": "both",
             "desc_zh": "现金流预测、盈余与赤字的管理（利润≠现金！）。",
             "key_concepts": ["Cash flow forecast", "Working capital"],
             "exam_zh": None, "exam_tips": ["\"盈利却破产\"是经典考点：利润是观点，现金是事实。"]},
            {"id": "BB3.7", "title_en": "Investment appraisal (HL)", "title_zh": "投资评估 (HL)", "level": "hl",
             "desc_zh": "回收期、平均回报率(ARR)、净现值(NPV)。",
             "key_concepts": ["Payback period", "ARR", "NPV"],
             "exam_tips": ["NPV 考虑货币时间价值最科学，但对折现率敏感。"]},
            {"id": "BB3.8", "title_en": "Budgets (HL)", "title_zh": "预算 (HL)", "level": "hl",
             "desc_zh": "成本/利润中心、预算的编制与差异分析。",
             "key_concepts": ["Cost centre", "Variance analysis"],
             "exam_tips": ["差异 = 实际 − 预算，有利/不利要分方向。"]},
        ]},
        {"id": "ib-b4", "order": 4, "title_en": "Marketing", "title_zh": "市场营销",
         "short_zh": "营销", "topics": [
            {"id": "BB4.1", "title_en": "The role of marketing & market research", "title_zh": "营销角色与市场调研", "level": "both",
             "desc_zh": "营销导向演变、一级/二级调研、定量/定性方法与偏差。",
             "key_concepts": ["Product orientation", "Primary research", "Sampling bias"],
             "exam_tips": ["调研方法评估三件套：成本、可靠性、样本偏差。"]},
            {"id": "BB4.2", "title_en": "The marketing mix (7Ps)", "title_zh": "营销组合 7P", "level": "both",
             "desc_zh": "产品/价格/渠道/促销 + 人员/过程/有形展示（服务营销）。",
             "key_concepts": ["Marketing mix", "7Ps"],
             "exam_tips": ["7P 要作为整体（一致性）讨论，不能逐个孤立罗列。"]},
            {"id": "BB4.3", "title_en": "Product & branding", "title_zh": "产品与品牌", "level": "both",
             "desc_zh": "产品类型、品牌（自有/制造商）、USP、新产品开发。",
             "key_concepts": ["Brand", "USP", "Product life cycle"],
             "exam_tips": ["PLC 各阶段的营销策略调整（延伸策略）是高频。"]},
            {"id": "BB4.4", "title_en": "Price", "title_zh": "定价", "level": "both",
             "desc_zh": "成本导向（成本加成）、竞争导向（定价）、市场导向（渗透/撇脂/心理定价）及 HL 价格歧视。",
             "key_concepts": ["Cost-plus", "Penetration pricing", "Price skimming", "Price discrimination (HL)"],
             "exam_tips": ["撇脂 vs 渗透的适用条件（创新度、竞争、弹性）是必考。"]},
            {"id": "BB4.5", "title_en": "Promotion", "title_zh": "促销", "level": "both",
             "desc_zh": "推/拉策略、广告、公关、个人推销、促销组合与 AIDA。",
             "key_concepts": ["Above/below the line", "AIDA"],
             "exam_tips": ["promotion 与 PLC/target market 的匹配要一起答。"]},
            {"id": "BB4.6", "title_en": "Place & e-commerce", "title_zh": "渠道与电商", "level": "both",
             "desc_zh": "分销渠道长度、零售业态、电商的类型与影响。",
             "key_concepts": ["Distribution channel", "E-commerce"],
             "exam_tips": ["渠道取舍：控制 vs 成本 vs 覆盖面。"]},
            {"id": "BB4.7", "title_en": "International marketing (HL)", "title_zh": "国际营销 (HL)", "level": "hl",
             "desc_zh": "全球化品牌 vs 本土化调整、进入模式与风险。",
             "key_concepts": ["Globalization", "Glocalization"],
             "exam_tips": ["标准化省成本 vs 本土化贴市场，评估要给情境化结论。"]},
        ]},
        {"id": "ib-b5", "order": 5, "title_en": "Operations Management", "title_zh": "运营管理",
         "short_zh": "运营", "topics": [
            {"id": "BB5.1", "title_en": "The role of operations", "title_zh": "运营的角色", "level": "both",
             "desc_zh": "生产、生产率、精益生产与质量管理。",
             "key_concepts": ["Productivity", "Lean production", "Kaizen"],
             "exam_tips": ["精益的核心是消除浪费（muda），工具：JIT、Kaizen、连续改进。"]},
            {"id": "BB5.2", "title_en": "Production methods & location", "title_zh": "生产方法与选址", "level": "both",
             "desc_zh": "批量/流水/单位生产；选址因素（定量+定性）。",
             "key_concepts": ["Batch production", "Mass customization"],
             "exam_tips": ["选址题用\"成本因素 vs 非成本因素\"分类作答。"]},
            {"id": "BB5.3", "title_en": "Quality management", "title_zh": "质量管理 (HL 拓展)", "level": "both",
             "desc_zh": "质量检验 vs 全面质量管理(TQM)。",
             "key_concepts": ["Quality control", "TQM"],
             "exam_tips": ["TQM 重预防重全员，control 重事后把关——对比是高频。"]},
            {"id": "BB5.4", "title_en": "Break-even analysis", "title_zh": "盈亏平衡分析", "level": "both",
             "desc_zh": "贡献、盈亏平衡点计算与图解、目标利润产量。",
             "key_concepts": ["Contribution", "Break-even point", "Margin of safety"],
             "exam_tips": ["BEP = FC / (P − VC)；图中标 FC、TC、TR 与安全边际。"]},
            {"id": "BB5.5", "title_en": "Production planning & MIS (HL)", "title_zh": "生产计划与管理信息系统 (HL)", "level": "hl",
             "desc_zh": "产能利用、库存管理、MIS 与大数据。",
             "key_concepts": ["Capacity utilization", "MIS"],
             "exam_tips": ["产能利用率高不总是好事（无弹性、维护不足）。"]},
        ]},
    ],
    "assessment": {
        "note": "IB BM 2022 新大纲（2024 首考）；以当季 guide 为准",
        "SL": [{"id": "p1", "name_zh": "Paper 1（基于案例）", "time": "1h15m", "weight": 35},
               {"id": "p2", "name_zh": "Paper 2（数据+论述）", "time": "1h45m", "weight": 40},
               {"id": "ia", "name_zh": "IA 商业研究项目（约1800词）", "time": "—", "weight": 25}],
        "HL": [{"id": "p1", "name_zh": "Paper 1（基于案例）", "time": "1h15m", "weight": 25},
               {"id": "p2", "name_zh": "Paper 2（数据+论述）", "time": "1h45m", "weight": 30},
               {"id": "p3", "name_zh": "Paper 3（基于案例·战略）", "time": "1h15m", "weight": 25},
               {"id": "ia", "name_zh": "IA 商业研究项目（约1800词）", "time": "—", "weight": 20}],
    },
    "glossary": [
        {"term_en": "Added value", "term_zh": "增值", "topic": "BB1.1", "def_zh": "产出价值 − 购入成本。"},
        {"term_en": "Limited liability", "term_zh": "有限责任", "topic": "BB1.2", "def_zh": "股东只以出资额为限承担责任。"},
        {"term_en": "SMART objectives", "term_zh": "SMART 目标", "topic": "BB1.3", "def_zh": "具体/可衡量/可达成/相关/有时限。"},
        {"term_en": "Stakeholder", "term_zh": "利益相关者", "topic": "BB1.4", "def_zh": "受企业影响或能影响企业的个人/组织。"},
        {"term_en": "STEEPLE", "term_zh": "STEEPLE 分析", "topic": "BB1.5", "def_zh": "社会/技术/经济/环境/政治/法律/伦理外部环境扫描。"},
        {"term_en": "Ansoff matrix", "term_zh": "安索夫矩阵", "topic": "BB1.5", "def_zh": "市场渗透/开发/产品开发/多元化的增长风险矩阵。"},
        {"term_en": "Labour turnover", "term_zh": "员工流失率", "topic": "BB2.1", "def_zh": "离职人数÷总员工×100%。"},
        {"term_en": "Herzberg", "term_zh": "赫茨伯格双因素", "topic": "BB2.2", "def_zh": "保健因素消除不满，激励因素创造满意。"},
        {"term_en": "Laissez-faire", "term_zh": "放任式领导", "topic": "BB2.3", "def_zh": "\"放手不管\"，适合高成熟度团队。"},
        {"term_en": "Overdraft", "term_zh": "银行透支", "topic": "BB3.1", "def_zh": "短期灵活融资，利随用随计。"},
        {"term_en": "Depreciation", "term_zh": "折旧", "topic": "BB3.3", "def_zh": "直线法/余额递减法分摊固定资产成本。"},
        {"term_en": "ROCE", "term_zh": "资本回报率", "topic": "BB3.4", "def_zh": "息税前利润÷资本运用×100%。"},
        {"term_en": "Current ratio", "term_zh": "流动比率", "topic": "BB3.4", "def_zh": "流动资产÷流动负债，安全域约 1.5–2。"},
        {"term_en": "Working capital", "term_zh": "营运资本", "topic": "BB3.6", "def_zh": "流动资产−流动负债。"},
        {"term_en": "NPV", "term_zh": "净现值", "topic": "BB3.7", "def_zh": "未来现金流按折现率折现后之和减初始投入。"},
        {"term_en": "Variance analysis", "term_zh": "差异分析", "topic": "BB3.8", "def_zh": "实际与预算之差，分有利/不利。"},
        {"term_en": "Marketing mix", "term_zh": "营销组合", "topic": "BB4.2", "def_zh": "4P/7P 的协同组合。"},
        {"term_en": "Price skimming", "term_zh": "撇脂定价", "topic": "BB4.4", "def_zh": "新品高价切入，逐级降价（创新品适用）。"},
        {"term_en": "Penetration pricing", "term_zh": "渗透定价", "topic": "BB4.4", "def_zh": "低价抢占份额，弹性大市场适用。"},
        {"term_en": "AIDA", "term_zh": "AIDA 模型", "topic": "BB4.5", "def_zh": "注意→兴趣→欲望→行动的促销漏斗。"},
        {"term_en": "Lean production", "term_zh": "精益生产", "topic": "BB5.1", "def_zh": "以最少资源消除一切浪费（JIT/Kaizen）。"},
        {"term_en": "TQM", "term_zh": "全面质量管理", "topic": "BB5.3", "def_zh": "全员、全过程、以预防为主的质量文化。"},
        {"term_en": "Break-even point", "term_zh": "盈亏平衡点", "topic": "BB5.4", "def_zh": "FC÷(P−VC)，总收入=总成本的产量。"},
        {"term_en": "Margin of safety", "term_zh": "安全边际", "topic": "BB5.4", "def_zh": "实际产量−盈亏平衡产量。"},
    ],
    "quiz": [
        {"q": "增值（added value）的计算是？", "opts": ["销售收入−购买成本", "利润−成本", "资产−负债", "产出×价格"], "a": 0, "why": "增值=产出价值−购入投入成本。"},
        {"q": "有限公司股东承担？", "opts": ["有限责任", "无限责任", "连带责任", "无责任"], "a": 0, "why": "limited liability 以出资额为限。"},
        {"q": "Ansoff 矩阵中风险最高的战略是？", "opts": ["多元化", "市场渗透", "市场开发", "产品开发"], "a": 0, "why": "新市场+新产品=双重不确定性。"},
        {"q": "按 Herzberg，工资属于？", "opts": ["保健因素", "激励因素", "成就需要", "自我实现"], "a": 0, "why": "工资消除不满但不创造长期满意。"},
        {"q": "流动比率的经验安全区间约是？", "opts": ["1.5–2", "0.5–1", "3–5", "5–10"], "a": 0, "why": "过低有流动性风险，过高资金效率差。"},
        {"q": "\"盈利的企业也可能倒闭\"是因为？", "opts": ["现金流出问题", "利润率太低", "竞争加剧", "通胀"], "a": 0, "why": "利润≠现金，现金流断裂才是直接死因。"},
        {"q": "NPV 相比回收期的最大优势是？", "opts": ["考虑货币时间价值", "计算更简单", "忽略风险", "不看现金流"], "a": 0, "why": "NPV 折现处理时间价值。"},
        {"q": "撇脂定价适合？", "opts": ["创新品、早期采用者", "成熟品", "日用品", "弹性大的市场"], "a": 0, "why": "创新+低弹性才撑得起高价。"},
        {"q": "AIDA 的正确顺序是？", "opts": ["注意→兴趣→欲望→行动", "行动→兴趣→注意→欲望", "兴趣→注意→行动→欲望", "欲望→注意→行动→兴趣"], "a": 0, "why": "Attention→Interest→Desire→Action。"},
        {"q": "盈亏平衡产量公式是？", "opts": ["FC÷(P−VC)", "FC×VC", "TR−TC", "(P−VC)÷FC"], "a": 0, "why": "单位贡献刚好覆盖固定成本。"},
        {"q": "JIT（准时制）的主要风险是？", "opts": ["供应链中断风险", "库存过高", "质量下降", "成本上升"], "a": 0, "why": "零库存依赖供应链极度可靠。"},
        {"q": "差异（variance）为\"不利\"意味着？", "opts": ["实际成本高于预算", "实际成本低于预算", "实际收入高于预算", "预算不准"], "a": 0, "why": "成本超支或收入不及预算都是不利差异。"},
        {"q": "以下哪项属于 below-the-line 促销？", "opts": ["个人推销", "电视广告", "户外广告", "广播广告"], "a": 0, "why": "BTOL 是可衡量、针对性强的直接沟通（推销/直邮/促销）。"},
        {"q": "glocalization 指的是？", "opts": ["全球化品牌+本土化调整", "完全标准化", "完全本土化", "退出国际市场"], "a": 0, "why": "全球框架、本地落地（think global, act local）。"},
        {"q": "产能利用率 100% 一定是好事吗？", "opts": ["否，缺乏弹性与维护空间", "是，效率最高", "与需求无关", "只看成本"], "a": 0, "why": "满负荷无法应对需求波动、设备老化快。"},
    ],
}

# ===========================================================================
# AL BUSINESS (CIE 9609 style)
# ===========================================================================

AL_BUS = {
    "id": "al-bus", "name_zh": "AL 商科", "name_en": "A-Level Business",
    "accent": "#f59e0b", "level_names": {"as": "AS", "a2": "A2", "both": "AS + A2"},
    "syllabus": [
        {"id": "al-b1", "order": 1, "title_en": "Business & Its Environment", "title_zh": "商业及其环境",
         "short_zh": "商业环境", "topics": [
            {"id": "AB1.1", "title_en": "Enterprise & business structure", "title_zh": "创业与企业结构", "level": "as",
             "desc_zh": "企业家精神、企业目标、添加值；独资/合伙/公司/特许经营。",
             "key_concepts": ["Entrepreneurship", "Added value", "Franchise"],
             "exam_tips": ["\"为何创业\"与\"为何选择公司制\"是最常见的两道 8 分题。"]},
            {"id": "AB1.2", "title_en": "Size, growth & stakeholders", "title_zh": "规模、增长与利益相关者", "level": "as",
             "desc_zh": "企业规模衡量、内外部增长方式、利益相关者冲突。",
             "key_concepts": ["M&A", "Joint venture", "Stakeholder conflict"],
             "exam_tips": ["并购成败评估：协同效应 vs 整合成本，双边都要写。"]},
            {"id": "AB1.3", "title_en": "Business structure & external influences", "title_zh": "外部环境影响", "level": "a2",
             "desc_zh": "PEST(E) 宏观环境、跨国公司与政府关系。",
             "key_concepts": ["PEST analysis", "MNC"],
             "exam_tips": ["外部因素分析必须落到\"对需求/成本/决策的具体影响\"。"]},
        ]},
        {"id": "al-b2", "order": 2, "title_en": "Human Resource Management", "title_zh": "人力资源管理",
         "short_zh": "人力", "topics": [
            {"id": "AB2.1", "title_en": "HRM & motivation", "title_zh": "人力资源与激励", "level": "as",
             "desc_zh": "招聘流程、劳动契约、Taylor/Maslow/Herzberg 激励理论的应用。",
             "key_concepts": ["Motivation theories", "Financial incentives"],
             "exam_tips": ["\"金钱是否最佳激励\"——用理论+情境两面评估。"]},
            {"id": "AB2.2", "title_en": "Management, leadership & organisation", "title_zh": "管理、领导与组织", "level": "a2",
             "desc_zh": "管理职能（PODSCORB 简版）、领导风格、组织结构与授权。",
             "key_concepts": ["Span of control", "Delegation", "Matrix structure"],
             "exam_tips": ["扁平 vs 高层级的权衡：沟通速度 vs 控制幅度。"]},
        ]},
        {"id": "al-b3", "order": 3, "title_en": "Marketing", "title_zh": "市场营销",
         "short_zh": "营销", "topics": [
            {"id": "AB3.1", "title_en": "Market research & marketing mix", "title_zh": "市场调研与营销组合", "level": "as",
             "desc_zh": "产品生命周期、市场细分与定位、4P 组合决策。",
             "key_concepts": ["Market segmentation", "Product life cycle", "4Ps"],
             "exam_tips": ["延伸策略（extension strategies）必须联系 PLC 阶段。"]},
            {"id": "AB3.2", "title_en": "Pricing & promotion strategy", "title_zh": "定价与促销战略", "level": "a2",
             "desc_zh": "价格弹性与定价策略、品牌策略、整合营销传播。",
             "key_concepts": ["Price elasticity & pricing", "Branding", "IMC"],
             "exam_tips": ["定价题先判弹性，再选策略（弹性大→降价/渗透）。"]},
        ]},
        {"id": "al-b4", "order": 4, "title_en": "Operations Management", "title_zh": "运营管理",
         "short_zh": "运营", "topics": [
            {"id": "AB4.1", "title_en": "Production, costs & scale", "title_zh": "生产、成本与规模", "level": "as",
             "desc_zh": "生产方式、固定/可变成本、规模经济与不经济。",
             "key_concepts": ["Economies of scale", "Capacity utilisation"],
             "exam_tips": ["规模经济五类（采购/技术/财务/管理/风险）要能举例。"]},
            {"id": "AB4.2", "title_en": "Lean, quality & inventory", "title_zh": "精益、质量与库存", "level": "a2",
             "desc_zh": "精益生产、JIT、质量管理、供应链管理。",
             "key_concepts": ["Lean production", "JIT", "Quality assurance"],
             "exam_tips": ["JIT 评估：库存成本↓ vs 断供风险↑。"]},
        ]},
        {"id": "al-b5", "order": 5, "title_en": "Finance & Accounting", "title_zh": "财务与会计",
         "short_zh": "财务", "topics": [
            {"id": "AB5.1", "title_en": "Finance sources & forecasting", "title_zh": "融资来源与预测", "level": "as",
             "desc_zh": "短/中/长期融资、收入/成本/利润预测、现金流预测与解决赤字。",
             "key_concepts": ["Cash flow forecast", "Overdraft", "Debenture"],
             "exam_tips": ["现金流预测表会读会改（调整某个假设的传导）。"]},
            {"id": "AB5.2", "title_en": "Accounts, ratios & appraisal", "title_zh": "报表、比率与评估", "level": "a2",
             "desc_zh": "利润表/资产负债表、盈利/流动/效率比率、投资评估（回收期/ARR/NPV）。",
             "key_concepts": ["Gross profit margin", "ROCE", "ARR", "NPV"],
             "exam_tips": ["比率一定要对比基准（趋势/同行）才有意义。"]},
        ]},
        {"id": "al-b6", "order": 6, "title_en": "Strategic Management", "title_zh": "战略管理",
         "short_zh": "战略", "topics": [
            {"id": "AB6.1", "title_en": "Strategic analysis & choice", "title_zh": "战略分析与选择", "level": "a2",
             "desc_zh": "SWOT、波特五力、核心竞争力、Ansoff、波特通用战略。",
             "key_concepts": ["SWOT", "Porter's generic strategies", "Core competences"],
             "exam_tips": ["战略工具的局限（静态/主观/过时）是评估部分的标配。"]},
            {"id": "AB6.2", "title_en": "Strategic implementation & change", "title_zh": "战略实施与变革", "level": "a2",
             "desc_zh": "变革管理（Lewin 三步）、风险管理与危机应对、组织文化。",
             "key_concepts": ["Lewin's change model", "Risk management"],
             "exam_tips": ["变革阻力分析：员工/文化/成本三来源+对应化解。"]},
        ]},
    ],
    "assessment": {
        "note": "以 CIE 9609 近年考纲为参考（具体以当季 syllabus 为准）",
        "components": [
            {"id": "p1", "name_zh": "Paper 1 · 商业概念 (AS)", "time": "1h15m", "weight": 20,
             "note_zh": "简答+短论述。"},
            {"id": "p2", "name_zh": "Paper 2 · 数据回应 (AS)", "time": "1h30m", "weight": 30,
             "note_zh": "基于数据的案例分析。"},
            {"id": "p3", "name_zh": "Paper 3 · 商业决策 (A2)", "time": "3h", "weight": 50,
             "note_zh": "大案例+决策建议+论述，覆盖 A2 全部内容。"},
        ]},
    "glossary": [
        {"term_en": "Franchise", "term_zh": "特许经营", "topic": "AB1.1", "def_zh": "购买成熟品牌与经营模式的授权。"},
        {"term_en": "Added value", "term_zh": "增值", "topic": "AB1.1", "def_zh": "售价减去购入投入成本。"},
        {"term_en": "M&A", "term_zh": "并购", "topic": "AB1.2", "def_zh": "合并/收购实现外部增长。"},
        {"term_en": "PEST analysis", "term_zh": "PEST 分析", "topic": "AB1.3", "def_zh": "政治/经济/社会/技术外部扫描。"},
        {"term_en": "Span of control", "term_zh": "管理幅度", "topic": "AB2.2", "def_zh": "一名管理者直接管辖的下属数。"},
        {"term_en": "Market segmentation", "term_zh": "市场细分", "topic": "AB3.1", "def_zh": "按地理/人口/心理/行为切分市场。"},
        {"term_en": "Extension strategy", "term_zh": "（产品）延伸策略", "topic": "AB3.1", "def_zh": "延缓 PLC 成熟期衰退的手段。"},
        {"term_en": "IMC", "term_zh": "整合营销传播", "topic": "AB3.2", "def_zh": "所有促销工具传递一致信息。"},
        {"term_en": "Capacity utilisation", "term_zh": "产能利用率", "topic": "AB4.1", "def_zh": "实际产出÷满负荷产出×100%。"},
        {"term_en": "Lean production", "term_zh": "精益生产", "topic": "AB4.2", "def_zh": "消除浪费、压缩时间与成本。"},
        {"term_en": "JIT", "term_zh": "准时制", "topic": "AB4.2", "def_zh": "需要时才进货，几乎零库存。"},
        {"term_en": "ROCE", "term_zh": "资本回报率", "topic": "AB5.2", "def_zh": "营业利润÷(股本+长期负债)×100%。"},
        {"term_en": "ARR", "term_zh": "平均回报率", "topic": "AB5.2", "def_zh": "年均利润÷初始投入×100%。"},
        {"term_en": "Porter's generic strategies", "term_zh": "波特通用战略", "topic": "AB6.1", "def_zh": "成本领先/差异化/聚焦。"},
        {"term_en": "Core competences", "term_zh": "核心竞争力", "topic": "AB6.1", "def_zh": "难以模仿、创造价值的能力组合。"},
        {"term_en": "Lewin's change model", "term_zh": "勒温变革三步", "topic": "AB6.2", "def_zh": "解冻→变革→再冻结。"},
    ],
    "quiz": [
        {"q": "特许经营对受许人的主要好处是？", "opts": ["成熟品牌与模式降低风险", "完全经营自由", "无需付费", "利润全归自己"], "a": 0, "why": "买的是已验证的商业模式与品牌。"},
        {"q": "外部增长（并购）的主要风险是？", "opts": ["整合失败与文化冲突", "增长太慢", "无法融资", "政府不收税"], "a": 0, "why": "研究显示多数并购未达协同预期。"},
        {"q": "矩阵式结构的典型缺点是？", "opts": ["双重汇报引发冲突", "沟通层级过多", "无法项目化", "完全集权"], "a": 0, "why": "双上级（职能+项目）是矩阵制固有张力。"},
        {"q": "PLC 成熟期最常用的策略是？", "opts": ["延伸策略", "撇脂定价", "退出市场", "减少促销"], "a": 0, "why": "延长成熟期、推迟衰退。"},
        {"q": "以下哪项不属于规模经济？", "opts": ["管理不经济", "采购经济", "技术经济", "财务经济"], "a": 0, "why": "规模不经济是规模扩大导致成本上升。"},
        {"q": "JIT 库存制的核心权衡是？", "opts": ["库存成本 vs 断供风险", "质量 vs 数量", "价格 vs 渠道", "品牌 vs 利润"], "a": 0, "why": "零库存省成本但依赖供应链稳定。"},
        {"q": "现金流量表中\"净现金流\"为负说明？", "opts": ["现金流出大于流入", "企业一定破产", "利润为负", "收入为零"], "a": 0, "why": "仅指该期现金净减少，需看持续性。"},
        {"q": "ROCE 衡量的是？", "opts": ["资本运用的回报效率", "流动性", "库存效率", "股价表现"], "a": 0, "why": "营业利润相对长期资本的回报。"},
        {"q": "波特\"成本领先\"战略的关键是？", "opts": ["以更低成本运营获得价格优势", "独特性溢价", "聚焦小市场", "多元并购"], "a": 0, "why": "成本领先≠低价格战，是结构性成本优势。"},
        {"q": "Lewin 变革模型第一步是？", "opts": ["解冻", "变革", "再冻结", "评估"], "a": 0, "why": "先打破现状、制造变革紧迫感。"},
        {"q": "以下哪项是定性市场调研？", "opts": ["焦点小组", "问卷统计", "销售数据分析", " census"], "a": 0, "why": "焦点小组探索\"为什么\"，属定性方法。"},
        {"q": "速动比率剔除存货是因为？", "opts": ["存货变现慢且不确定", "存货无价值", "会计准则要求", "存货不属于资产"], "a": 0, "why": "存货流动性最差，剔除后更严格。"},
    ],
}

# ===========================================================================
# COMPETITION KNOWLEDGE (Conrad / BPA + 赛代学)
# ===========================================================================

COMP = {
    "id": "comp", "name_zh": "竞赛知识（康莱德 & BPA）", "name_en": "Competition Knowledge",
    "accent": "#ef4444", "level_names": {"both": "通识", "conrad": "康莱德", "bpa": "BPA"},
    "syllabus": [
        {"id": "cp1", "order": 1, "title_en": "Conrad Challenge 康莱德", "title_zh": "康莱德创新挑战赛",
         "short_zh": "康莱德", "topics": [
            {"id": "CP1.1", "title_en": "Competition structure & innovation cycle", "title_zh": "赛制与创新周期", "level": "conrad",
             "desc_zh": "Activation（Lean Canvas）→ Innovation（Innovation Brief）→ Power Pitch 三阶段。",
             "key_concepts": ["Activation Stage", "Innovation Stage", "Power Pitch"],
             "exam_tips": ["Lean Canvas 提交后仍可迭代，评委看重\"进化轨迹\"。"]},
            {"id": "CP1.2", "title_en": "Six judging dimensions", "title_zh": "六维评分体系", "level": "conrad",
             "desc_zh": "Theme 30% / Innovation 20% / Storytelling 20% / Practicality 20% / Marketing 10% / Finances 10%。",
             "key_concepts": ["Theme", "Innovation", "Storytelling", "Practicality", "Marketing", "Finances"],
             "exam_tips": ["Theme 占 30% 最高——先定主题再立项，全文显式呼应主题词。"]},
            {"id": "CP1.3", "title_en": "Lean Canvas 12 questions", "title_zh": "Lean Canvas 12 问", "level": "conrad",
             "desc_zh": "Problem/Solution/UVP/Advantage/Customer/Channels/Revenue/Cost/Metrics/Idea... 每题≤40词。",
             "key_concepts": ["Problem", "UVP", "Unfair advantage", "Revenue streams"],
             "exam_tips": ["Problem 必须：具体人群+量化数据+当季主题词，三要素缺一不可。"]},
            {"id": "CP1.4", "title_en": "Innovation Brief & tracks", "title_zh": "创新简报与赛道", "level": "conrad",
             "desc_zh": "航空/网络/能源环境/健康营养/水资源五大赛道；Brief 的写作框架。",
             "key_concepts": ["Five categories", "Water Challenge"],
             "exam_tips": ["赛道选择：兴趣+资源+差异化+政策对齐四步法。"]},
            {"id": "CP1.5", "title_en": "Finances & unit economics", "title_zh": "财务与单位经济", "level": "conrad",
             "desc_zh": "成本估算、收入预测、融资策略、LTV/CAC 与单位经济模型。",
             "key_concepts": ["LTV/CAC", "Unit economics", "Burn rate"],
             "exam_tips": ["LTV/CAC>3 是常见的健康参考线；评委追问成本假设的依据。"]},
        ]},
        {"id": "cp2", "order": 2, "title_en": "BPA", "title_zh": "BPA 商业挑战赛",
         "short_zh": "BPA", "topics": [
            {"id": "CP2.1", "title_en": "BPA structure & WSAP events", "title_zh": "BPA 赛制与专项赛", "level": "bpa",
             "desc_zh": "客观题测试（Objective Test）+ 专项赛（WSAP：金融/营销/管理/HR 等）+ 案例分析。",
             "key_concepts": ["Objective test", "WSAP", "Case study"],
             "exam_tips": ["客观题覆盖整本 Business + 经济基础，刷教材即刷题。"]},
            {"id": "CP2.2", "title_en": "Case study framework", "title_zh": "案例分析框架", "level": "bpa",
             "desc_zh": "SWOT/五力/STP/比率分析的工具组合式答题法。",
             "key_concepts": ["SWOT", "Porter's five forces", "Ratio analysis"],
             "exam_tips": ["案例分析三步：诊断（工具）→ 方案（匹配资源）→ 论证（利弊+优先级）。"]},
            {"id": "CP2.3", "title_en": "CBPA 八步研习法", "title_zh": "CBPA 八步研习法", "level": "bpa",
             "desc_zh": "从选题、研习到陈述的八步备赛流程。",
             "key_concepts": ["Research steps", "Presentation"],
             "exam_tips": ["每步都有官方 Task 文档，按步提交产出物。"]},
        ]},
        {"id": "cp3", "order": 3, "title_en": "赛代学 Cross-mapping", "title_zh": "赛代学：竞赛 × 学科拟合",
         "short_zh": "赛代学", "topics": [
            {"id": "CP3.1", "title_en": "Economics × Competition", "title_zh": "经济学 × 竞赛", "level": "both",
             "desc_zh": "微观（供需/弹性/市场结构/市场失灵）对应 Marketing 与 Practicality；宏观对应 Pitch 背景；全球（SDG/可持续）对应 Theme 30%。",
             "key_concepts": ["PED & pricing", "Market failure & ESG", "Comparative advantage"],
             "exam_tips": ["康莱德 Theme=30% 恰是经济\"全球单元\"的 SDG/可持续内容。"]},
            {"id": "CP3.2", "title_en": "Business × Competition", "title_zh": "商科 × 竞赛", "level": "both",
             "desc_zh": "营销 7P/STP ↔ Marketing 维度；财务三表/投资评估 ↔ Finances 维度；运营/盈亏平衡 ↔ Practicality 维度。",
             "key_concepts": ["7Ps", "NPV/IRR", "Break-even"],
             "exam_tips": ["Lean Canvas 的每一格几乎都能映射到一个商科知识点。"]},
            {"id": "CP3.3", "title_en": "Startup toolkit", "title_zh": "创业工具箱", "level": "both",
             "desc_zh": "BMC 9 格、Lean Canvas、TAM/SAM/SOM、MVP、ERRC 网格。",
             "key_concepts": ["BMC", "TAM/SAM/SOM", "MVP", "ERRC"],
             "exam_tips": ["TAM（总市场）≥SAM（可服务）≥SOM（可获得），口径不能倒挂。"]},
        ]},
    ],
    "assessment": {
        "note": "康莱德与 BPA 的关键评分要点（赛代学参考）",
        "components": [
            {"id": "conrad", "name_zh": "康莱德 6 维评分", "time": "—", "weight": None,
             "note_zh": "Theme 30 / Innovation 20 / Storytelling 20 / Practicality 20 / Marketing 10 / Finances 10（%）。"},
            {"id": "bpa", "name_zh": "BPA 评估形式", "time": "—", "weight": None,
             "note_zh": "客观题测试 + 案例分析 + WSAP 专项（各 event 规则不同）。"},
        ]},
    "glossary": [
        {"term_en": "Lean Canvas", "term_zh": "精益画布", "topic": "CP1.3", "def_zh": "10 格一页纸创业假设图（Conrad 用 12 问版）。"},
        {"term_en": "UVP", "term_zh": "独特价值主张", "topic": "CP1.3", "def_zh": "一句话说清\"为什么选你\"。"},
        {"term_en": "Unfair advantage", "term_zh": "不公平优势", "topic": "CP1.3", "def_zh": "竞品难以复制的壁垒（IP/网络/数据）。"},
        {"term_en": "TAM/SAM/SOM", "term_zh": "市场分层测算", "topic": "CP3.3", "def_zh": "总市场/可服务市场/可获得市场。"},
        {"term_en": "MVP", "term_zh": "最小可行产品", "topic": "CP3.3", "def_zh": "以最小成本验证核心假设的版本。"},
        {"term_en": "BMC", "term_zh": "商业模式画布", "topic": "CP3.3", "def_zh": "9 格描述价值创造-传递-获取全链。"},
        {"term_en": "ERRC", "term_zh": "ERRC 网格", "topic": "CP3.3", "def_zh": "蓝海四动作：消除/减少/提升/创造。"},
        {"term_en": "LTV", "term_zh": "客户终身价值", "topic": "CP1.5", "def_zh": "单客户全周期贡献毛利。"},
        {"term_en": "CAC", "term_zh": "获客成本", "topic": "CP1.5", "def_zh": "获取一个客户的总营销销售成本。"},
        {"term_en": "Burn rate", "term_zh": "烧钱率", "topic": "CP1.5", "def_zh": "月度净现金消耗速度。"},
        {"term_en": "STP", "term_zh": "STP 营销", "topic": "CP3.2", "def_zh": "细分→目标→定位。"},
        {"term_en": "NPV", "term_zh": "净现值", "topic": "CP3.2", "def_zh": "折现现金流之和减初始投入。"},
        {"term_en": "SDG", "term_zh": "联合国可持续发展目标", "topic": "CP3.1", "def_zh": "17 项目标，康莱德 Theme 常绑定。"},
        {"term_en": "ESG", "term_zh": "环境/社会/治理", "topic": "CP3.1", "def_zh": "可持续投资与治理的三支柱。"},
        {"term_en": "Five forces", "term_zh": "波特五力", "topic": "CP2.2", "def_zh": "供应商/买方/替代/新进入/现存竞争。"},
        {"term_en": "Pitch Deck", "term_zh": "路演简报", "topic": "CP1.1", "def_zh": "10-15 页投资人叙事结构。"},
    ],
    "quiz": [
        {"q": "康莱德评分中权重最高的维度是？", "opts": ["Theme 主题契合 30%", "Finances 10%", "Marketing 10%", "Storytelling 20%"], "a": 0, "why": "Theme 30%，先定主题再立项。"},
        {"q": "Lean Canvas 每题的字数上限是？", "opts": ["40 词（Q6 为 10 词）", "100 词", "无限制", "200 词"], "a": 0, "why": "Portal 会按词数硬截断。"},
        {"q": "TAM、SAM、SOM 的正确关系是？", "opts": ["TAM ≥ SAM ≥ SOM", "SOM ≥ SAM ≥ TAM", "三者相等", "无关"], "a": 0, "why": "市场口径逐层收窄。"},
        {"q": "LTV/CAC 常见的健康参考线是？", "opts": ["> 3", "> 0.5", "= 1", "< 1"], "a": 0, "why": "3 倍以上说明单位经济健康。"},
        {"q": "MVP 的核心目的是？", "opts": ["以最小成本验证关键假设", "做出最完美产品", "压缩售价", "快速盈利"], "a": 0, "why": "MVP 是验证工具，不是缩水版成品。"},
        {"q": "康莱德 Problem 答案的必备三要素是？", "opts": ["人群+量化+主题词", "技术+专利+团队", "愿景+使命+价值观", "价格+渠道+促销"], "a": 0, "why": "缺量化或缺主题呼应都会被扣分。"},
        {"q": "BPA 客观题的主要范围是？", "opts": ["整本 Business+经济基础", "只考会计", "只考演讲", "编程能力"], "a": 0, "why": "管理/营销/财务/经济/法律均覆盖。"},
        {"q": "蓝海 ERRC 的四步动作是？", "opts": ["消除/减少/提升/创造", "计划/执行/检查/改进", "成本/差异/聚焦/品牌", "吸引/兴趣/欲望/行动"], "a": 0, "why": "Eliminate/Reduce/Raise/Create。"},
        {"q": "波特五力不包括？", "opts": ["政府补贴", "新进入者威胁", "替代品威胁", "买方议价能力"], "a": 0, "why": "五力：现存竞争/新进入/替代/买方/供方。"},
        {"q": "BMC 九格中\"价值主张\"描述的是？", "opts": ["为谁解决什么问题、凭什么选你", "怎么招人", "服务器成本", "股价目标"], "a": 0, "why": "它是画布的核心格，其余八格围绕它。"},
        {"q": "以下哪个概念属于\"单位经济\"范畴？", "opts": ["单客毛利与获客成本", "GDP 增速", "基尼系数", "菲利普斯曲线"], "a": 0, "why": "单位经济=每单位/每客户的收入成本结构。"},
        {"q": "康莱德赛制第一阶段（Activation）需提交？", "opts": ["Lean Canvas", "Pitch Deck", "决赛视频", "专利文件"], "a": 0, "why": "Activation 交 Lean Canvas，Innovation 交 Brief。"},
        {"q": "SDG 一共有多少项目标？", "opts": ["17", "8", "12", "20"], "a": 0, "why": "联合国 17 项可持续发展目标。"},
        {"q": "案例分析题的建议作答顺序是？", "opts": ["诊断→方案→论证", "方案→诊断→论证", "论证→诊断→方案", "结论→案例→理论"], "a": 0, "why": "先用工具诊断问题，再提匹配方案，最后论证利弊。"},
        {"q": "Storytelling 维度评委的核心问句是？", "opts": ["投资人想了解更多吗", "专利写了吗", "服务器在哪", "成本多少"], "a": 0, "why": "叙事维度的本质是 investor appeal。"},
    ],
}

SUBJECTS = [AL_ECON, IB_BUS, AL_BUS, COMP]
