"""Deep content for AL-econ / IB-bus / AL-bus / comp, matching the IB-econ
standard: expanded glossaries, extra quiz banks, IA/EE & essay guides,
teaching resources (textbook chapter maps), and the AL-econ diagram mapping
(reuses the 28 IB-econ diagram images)."""

# ===========================================================================
# 1. GLOSSARY EXPANSION
# ===========================================================================

GLOSSARY_EXTRA = {
    # ---------------- AL ECONOMICS (+57 → 80) ----------------
    "al-econ": [
        {"term_en": "Economic goods", "term_zh": "经济物品", "topic": "AE1.1", "def_zh": "稀缺、需要付出代价获取的物品。"},
        {"term_en": "Free goods", "term_zh": "免费物品", "topic": "AE1.1", "def_zh": "充裕且机会成本为零的物品（如空气）。"},
        {"term_en": "Production possibility curve", "term_zh": "生产可能性曲线", "topic": "AE1.1", "def_zh": "资源充分利用时两种商品的最大组合轨迹。"},
        {"term_en": "Division of labour", "term_zh": "劳动分工", "topic": "AE1.1", "def_zh": "把生产拆分为专门工序以提高效率。"},
        {"term_en": "Positive statement", "term_zh": "实证陈述", "topic": "AE1.2", "def_zh": "可检验的\"是什么\"（what is）。"},
        {"term_en": "Normative statement", "term_zh": "规范陈述", "topic": "AE1.2", "def_zh": "含价值判断的\"应该怎样\"（what ought to be）。"},
        {"term_en": "Ceteris paribus", "term_zh": "其他条件不变", "topic": "AE2.1", "def_zh": "分析单一变量时冻结其他因素。"},
        {"term_en": "Movement along the curve", "term_zh": "沿曲线移动", "topic": "AE2.1", "def_zh": "由价格本身引起的量变。"},
        {"term_en": "Shift of the curve", "term_zh": "曲线平移", "topic": "AE2.1", "def_zh": "由非价格因素引起的整条线移动。"},
        {"term_en": "Inferior good", "term_zh": "劣等品", "topic": "AE2.2", "def_zh": "收入增加需求反而下降（YED<0）。"},
        {"term_en": "Normal good", "term_zh": "正常品", "topic": "AE2.2", "def_zh": "收入增加需求上升（YED>0）。"},
        {"term_en": "Price mechanism", "term_zh": "价格机制", "topic": "AE2.1", "def_zh": "价格通过信号、激励、配给配置资源。"},
        {"term_en": "Rationing function", "term_zh": "配给功能", "topic": "AE2.1", "def_zh": "高价限制需求、把稀缺品分给出价高者。"},
        {"term_en": "Signal function", "term_zh": "信号功能", "topic": "AE2.1", "def_zh": "价格变动传递稀缺性与机会信息。"},
        {"term_en": "Producer surplus", "term_zh": "生产者剩余", "topic": "AE2.3", "def_zh": "实收价高于最低可接受价之差。"},
        {"term_en": "Allocative efficiency", "term_zh": "配置效率", "topic": "AE2.3", "def_zh": "P=MC，资源用于消费者最看重的用途。"},
        {"term_en": "Deadweight loss", "term_zh": "无谓损失", "topic": "AE2.4", "def_zh": "干预使社会总剩余净减少的三角面积。"},
        {"term_en": "Ad valorem tax", "term_zh": "从价税", "topic": "AE2.4", "def_zh": "按价格百分比征收，供给曲线旋转。"},
        {"term_en": "Buffer stock scheme", "term_zh": "缓冲库存", "topic": "AE2.4", "def_zh": "政府买卖储备平抑初级产品价格波动。"},
        {"term_en": "Merit good", "term_zh": "优值品", "topic": "AE3.2", "def_zh": "被低估收益而消费不足（教育、疫苗）。"},
        {"term_en": "Demerit good", "term_zh": "劣值品", "topic": "AE3.2", "def_zh": "被低估危害而消费过度（烟、酒）。"},
        {"term_en": "Information asymmetry", "term_zh": "信息不对称", "topic": "AE3.2", "def_zh": "交易一方掌握更多信息（次品市场）。"},
        {"term_en": "Pigouvian tax", "term_zh": "庇古税", "topic": "AE3.3", "def_zh": "按边际外部成本征税矫正负外部性。"},
        {"term_en": "Cap-and-trade", "term_zh": "总量管制与交易", "topic": "AE3.3", "def_zh": "设定排放上限并允许许可交易。"},
        {"term_en": "Nationalisation", "term_zh": "国有化", "topic": "AE3.3", "def_zh": "政府接管私营产业的所有权与经营。"},
        {"term_en": "Fixed cost", "term_zh": "固定成本", "topic": "AE4.1", "def_zh": "不随产量变化的成本（租金）。"},
        {"term_en": "Variable cost", "term_zh": "可变成本", "topic": "AE4.1", "def_zh": "随产量变化的成本（原料）。"},
        {"term_en": "Marginal product", "term_zh": "边际产量", "topic": "AE4.1", "def_zh": "增加一单位要素带来的产出增量。"},
        {"term_en": "Law of diminishing returns", "term_zh": "边际报酬递减", "topic": "AE4.1", "def_zh": "短期追加可变要素的边际产出递减。"},
        {"term_en": "Diseconomies of scale", "term_zh": "规模不经济", "topic": "AE4.1", "def_zh": "规模过大导致长期平均成本上升。"},
        {"term_en": "Total revenue", "term_zh": "总收入", "topic": "AE4.2", "def_zh": "P×Q。"},
        {"term_en": "Abnormal profit", "term_zh": "超额利润", "topic": "AE4.2", "def_zh": "高于正常利润的部分（TR>TC）。"},
        {"term_en": "Shut-down point", "term_zh": "停业点", "topic": "AE4.3", "def_zh": "P<AVC 时短期也应停产。"},
        {"term_en": "Natural monopoly", "term_zh": "自然垄断", "topic": "AE4.3", "def_zh": "规模经济使单一供应商成本最低（电网）。"},
        {"term_en": "Concentration ratio", "term_zh": "集中度比率", "topic": "AE4.4", "def_zh": "头部厂商市场份额衡量垄断程度。"},
        {"term_en": "Non-price competition", "term_zh": "非价格竞争", "topic": "AE4.4", "def_zh": "以品牌/服务/质量而非价格竞争。"},
        {"term_en": "Cartel", "term_zh": "卡特尔", "topic": "AE4.4", "def_zh": "寡头间公开或默契的合谋定产定价。"},
        {"term_en": "Productive efficiency", "term_zh": "生产效率", "topic": "AE4.3", "def_zh": "AC 最低点生产（成本最小）。"},
        {"term_en": "Dynamic efficiency", "term_zh": "动态效率", "topic": "AE4.4", "def_zh": "通过创新长期降低成本/提升品质。"},
        {"term_en": "Limit pricing", "term_zh": "限制定价", "topic": "AE4.4", "def_zh": "在位者定低价阻止新进入者。"},
        {"term_en": "Marginal utility", "term_zh": "边际效用", "topic": "AE4.6", "def_zh": "多消费一单位的效用增量，递减。"},
        {"term_en": "Equi-marginal principle", "term_zh": "等边际原则", "topic": "AE4.6", "def_zh": "MUa/Pa=MUb/Pb 时效用最大化。"},
        {"term_en": "Derived demand", "term_zh": "派生需求", "topic": "AE4.7", "def_zh": "劳动需求由产品需求派生。"},
        {"term_en": "Monopsony", "term_zh": "买方垄断", "topic": "AE4.7", "def_zh": "单一雇主压低工资（如国家医疗系统）。"},
        {"term_en": "Frictional unemployment", "term_zh": "摩擦性失业", "topic": "AE5.3", "def_zh": "换工作之间的暂时失业。"},
        {"term_en": "Structural unemployment", "term_zh": "结构性失业", "topic": "AE5.3", "def_zh": "技能与岗位结构错配（长期）。"},
        {"term_en": "Cyclical unemployment", "term_zh": "周期性失业", "topic": "AE5.3", "def_zh": "总需求不足引起（衰退）。"},
        {"term_en": "Multiplier", "term_zh": "乘数", "topic": "AE5.4", "def_zh": "1/(1−MPC)：初始支出被放大的倍数。"},
        {"term_en": "Budget deficit", "term_zh": "财政赤字", "topic": "AE5.4", "def_zh": "政府支出超过税收收入。"},
        {"term_en": "Progressive tax", "term_zh": "累进税", "topic": "AE5.5", "def_zh": "税率随收入上升（再分配）。"},
        {"term_en": "Crowding out", "term_zh": "挤出效应", "topic": "AE5.4", "def_zh": "政府借款推高利率挤出私人投资。"},
        {"term_en": "Quantitative easing", "term_zh": "量化宽松", "topic": "AE5.4", "def_zh": "央行购买资产直接注入流动性。"},
        {"term_en": "Absolute advantage", "term_zh": "绝对优势", "topic": "AE6.1", "def_zh": "以更少资源生产同一商品。"},
        {"term_en": "Quota", "term_zh": "配额", "topic": "AE6.1", "def_zh": "进口数量上限（不产生政府收入）。"},
        {"term_en": "Fixed exchange rate", "term_zh": "固定汇率", "topic": "AE6.2", "def_zh": "央行干预维持汇率不变。"},
        {"term_en": "Revaluation", "term_zh": "法定升值", "topic": "AE6.2", "def_zh": "固定汇率制下的官方上调。"},
        {"term_en": "Financial account", "term_zh": "金融账户", "topic": "AE6.2", "def_zh": "记录跨境投资与资本流动。"},
        {"term_en": "Purchasing power parity", "term_zh": "购买力平价", "topic": "AE6.3", "def_zh": "汇率应使同一篮子商品价格相同。"},
        {"term_en": "Microfinance", "term_zh": "小额信贷", "topic": "AE6.3", "def_zh": "向低收入者提供的小额金融服务。"},
        {"term_en": "Foreign aid", "term_zh": "对外援助", "topic": "AE6.3", "def_zh": "官方发展援助 ODA 的赠款与优惠贷款。"},
    ],
    # ---------------- IB BUSINESS (+56 → 80) ----------------
    "ib-bus": [
        {"term_en": "Private sector", "term_zh": "私营部门", "topic": "BB1.1", "def_zh": "由个人或股东拥有的企业。"},
        {"term_en": "Public sector", "term_zh": "公营部门", "topic": "BB1.1", "def_zh": "政府拥有并控制的组织。"},
        {"term_en": "Non-profit", "term_zh": "非营利组织", "topic": "BB1.1", "def_zh": "盈余用于使命而非分配给股东。"},
        {"term_en": "Mission statement", "term_zh": "使命宣言", "topic": "BB1.3", "def_zh": "组织存在理由与经营方式的宣言。"},
        {"term_en": "Tactical objectives", "term_zh": "战术目标", "topic": "BB1.3", "def_zh": "中期、部门层面的具体目标。"},
        {"term_en": "Ethics", "term_zh": "商业伦理", "topic": "BB1.3", "def_zh": "超出法律要求的道德行为准则（BM 四概念之一）。"},
        {"term_en": "Sustainability", "term_zh": "可持续性", "topic": "BB1.3", "def_zh": "兼顾经济、社会、环境三重底线（BM 四概念之一）。"},
        {"term_en": "Pressure group", "term_zh": "压力团体", "topic": "BB1.4", "def_zh": "影响企业决策的利益团体（环保组织）。"},
        {"term_en": "Horizontal integration", "term_zh": "横向整合", "topic": "BB1.5", "def_zh": "并购同行业同环节企业。"},
        {"term_en": "Vertical integration", "term_zh": "纵向整合", "topic": "BB1.5", "def_zh": "并购供应链上下游企业。"},
        {"term_en": "Conglomerate", "term_zh": "混合并购", "topic": "BB1.5", "def_zh": "跨行业并购（多元化）。"},
        {"term_en": "Strategic alliance", "term_zh": "战略联盟", "topic": "BB1.5", "def_zh": "无股权合并的长期合作。"},
        {"term_en": "Outsourcing", "term_zh": "外包", "topic": "BB1.5", "def_zh": "把非核心业务交外部供应商。"},
        {"term_en": "Glocalization", "term_zh": "全球本土化", "topic": "BB4.7", "def_zh": "全球品牌框架+本地市场适配。"},
        {"term_en": "Force field analysis", "term_zh": "力场分析", "topic": "BB1.6", "def_zh": "驱动力 vs 阻力的变革诊断（HL）。"},
        {"term_en": "Piece rate", "term_zh": "计件工资", "topic": "BB2.2", "def_zh": "按产出付酬（Taylor 科学管理）。"},
        {"term_en": "Profit sharing", "term_zh": "利润分享", "topic": "BB2.2", "def_zh": "把部分利润分给员工。"},
        {"term_en": "Job enrichment", "term_zh": "工作丰富化", "topic": "BB2.2", "def_zh": "增加纵向职责与自主权（Herzberg 激励因素）。"},
        {"term_en": "Empowerment", "term_zh": "授权赋能", "topic": "BB2.2", "def_zh": "给员工决策权与资源。"},
        {"term_en": "Paternalistic", "term_zh": "家长式领导", "topic": "BB2.3", "def_zh": "替员工作决定但以利益为本（HL）。"},
        {"term_en": "Emotional intelligence", "term_zh": "情商", "topic": "BB2.3", "def_zh": "识别管理自我与他人情绪的能力（HL）。"},
        {"term_en": "Matrix structure", "term_zh": "矩阵结构", "topic": "BB2.5", "def_zh": "职能×项目双线汇报。"},
        {"term_en": "Delayering", "term_zh": "削减层级", "topic": "BB2.5", "def_zh": "移除中层管理压缩组织。"},
        {"term_en": "Chain of command", "term_zh": "指挥链", "topic": "BB2.5", "def_zh": "自上而下的职权线。"},
        {"term_en": "Conciliation", "term_zh": "调停", "topic": "BB2.5", "def_zh": "第三方协助劳资双方达成一致。"},
        {"term_en": "Trade credit", "term_zh": "商业信用", "topic": "BB3.1", "def_zh": "供应商允许延期付款（短期融资）。"},
        {"term_en": "Venture capital", "term_zh": "风险投资", "topic": "BB3.1", "def_zh": "投资换取股权，高成长高风险。"},
        {"term_en": "Crowdfunding", "term_zh": "众筹", "topic": "BB3.1", "def_zh": "向大众小额募集项目资金。"},
        {"term_en": "Debenture", "term_zh": "公司债券", "topic": "BB3.1", "def_zh": "长期固定利率借款凭证。"},
        {"term_en": "Retained profit", "term_zh": "留存利润", "topic": "BB3.1", "def_zh": "再投入企业的未分配利润（内部融资）。"},
        {"term_en": "Gross profit", "term_zh": "毛利", "topic": "BB3.3", "def_zh": "收入−销售成本。"},
        {"term_en": "Net profit", "term_zh": "净利润", "topic": "BB3.3", "def_zh": "毛利−营业费用（息税前/后口径注意）。"},
        {"term_en": "Acid test ratio", "term_zh": "速动比率", "topic": "BB3.4", "def_zh": "(流动资产−存货)÷流动负债，目标约 1。"},
        {"term_en": "Gearing", "term_zh": "资本负债率", "topic": "BB3.4", "def_zh": "长期负债÷(负债+权益)，衡量财务风险。"},
        {"term_en": "Stock turnover", "term_zh": "存货周转", "topic": "BB3.5", "def_zh": "销货成本÷平均存货（次/年）（HL）。"},
        {"term_en": "Debtor days", "term_zh": "应收账款天数", "topic": "BB3.5", "def_zh": "应收÷赊销×365（HL）。"},
        {"term_en": "Market share", "term_zh": "市场份额", "topic": "BB4.1", "def_zh": "企业销售占行业总销售的比重。"},
        {"term_en": "Niche market", "term_zh": "利基市场", "topic": "BB4.1", "def_zh": "小而专的细分市场。"},
        {"term_en": "Secondary research", "term_zh": "二手调研", "topic": "BB4.1", "def_zh": "利用已有数据（便宜快但未必贴题）。"},
        {"term_en": "Quantitative data", "term_zh": "定量数据", "topic": "BB4.1", "def_zh": "可统计的数字型信息。"},
        {"term_en": "Qualitative data", "term_zh": "定性数据", "topic": "BB4.1", "def_zh": "观点、动机等非数字信息。"},
        {"term_en": "Brand loyalty", "term_zh": "品牌忠诚", "topic": "BB4.3", "def_zh": "顾客持续选择同一品牌的倾向。"},
        {"term_en": "Extension strategy", "term_zh": "延伸策略", "topic": "BB4.3", "def_zh": "延缓 PLC 成熟期衰退（新包装/新市场）。"},
        {"term_en": "Cost-plus pricing", "term_zh": "成本加成定价", "topic": "BB4.4", "def_zh": "单位成本+固定加成比例。"},
        {"term_en": "Loss leader", "term_zh": "亏本引流品", "topic": "BB4.4", "def_zh": "低/亏本定价带动连带消费。"},
        {"term_en": "Promotional pricing", "term_zh": "促销定价", "topic": "BB4.4", "def_zh": "限时折扣刺激短期销量。"},
        {"term_en": "Above-the-line promotion", "term_zh": "线上广告（ATL）", "topic": "BB4.5", "def_zh": "大众媒体广告（广而告知）。"},
        {"term_en": "Below-the-line promotion", "term_zh": "线下促销（BTL）", "topic": "BB4.5", "def_zh": "可定向可衡量的直接沟通（直邮/推销）。"},
        {"term_en": "Viral marketing", "term_zh": "病毒式营销", "topic": "BB4.5", "def_zh": "借社交网络自传播的内容营销。"},
        {"term_en": "Distribution channel", "term_zh": "分销渠道", "topic": "BB4.6", "def_zh": "产品从生产到消费者的路径。"},
        {"term_en": "E-commerce", "term_zh": "电商", "topic": "BB4.6", "def_zh": "线上交易平台（B2B/B2C 类型）。"},
        {"term_en": "Productivity", "term_zh": "生产率", "topic": "BB5.1", "def_zh": "单位投入的产出。"},
        {"term_en": "Kaizen", "term_zh": "改善", "topic": "BB5.1", "def_zh": "全员持续的小步改进。"},
        {"term_en": "Quality control", "term_zh": "质量检验", "topic": "BB5.3", "def_zh": "事后由专岗检出次品。"},
        {"term_en": "Quality assurance", "term_zh": "质量保证", "topic": "BB5.3", "def_zh": "过程全员预防缺陷（对比 QC）。"},
        {"term_en": "Capacity utilization", "term_zh": "产能利用率", "topic": "BB5.5", "def_zh": "实际产出÷满负荷产出×100%（HL）。"},
        {"term_en": "Just-in-case stock", "term_zh": "保险库存", "topic": "BB5.5", "def_zh": "保留缓冲库存应对不确定性（HL）。"},
    ],
    # ---------------- AL BUSINESS (+39 → 55) ----------------
    "al-bus": [
        {"term_en": "Entrepreneur", "term_zh": "企业家", "topic": "AB1.1", "def_zh": "承担风险组织生产要素的人。"},
        {"term_en": "Risk vs reward", "term_zh": "风险与回报", "topic": "AB1.1", "def_zh": "高风险要求高预期回报补偿。"},
        {"term_en": "Unlimited liability", "term_zh": "无限责任", "topic": "AB1.1", "def_zh": "个人财产为企业债务兜底。"},
        {"term_en": "Incorporation", "term_zh": "法人化", "topic": "AB1.1", "def_zh": "注册为独立法人（有限公司）。"},
        {"term_en": "Franchisee", "term_zh": "受许人", "topic": "AB1.1", "def_zh": "付费获得品牌经营授权的一方。"},
        {"term_en": "Survival objective", "term_zh": "生存目标", "topic": "AB1.1", "def_zh": "初创期压倒一切的首要目标。"},
        {"term_en": "Internal growth", "term_zh": "内生增长", "topic": "AB1.2", "def_zh": "靠自身积累扩张（稳但慢）。"},
        {"term_en": "Takeover", "term_zh": "收购", "topic": "AB1.2", "def_zh": "买入另一企业控制权。"},
        {"term_en": "Holding company", "term_zh": "控股公司", "topic": "AB1.2", "def_zh": "通过持股控制多个子公司的母公司。"},
        {"term_en": "B2B", "term_zh": "企业对企业", "topic": "AB1.2", "def_zh": "面向企业客户的销售模式。"},
        {"term_en": "Management by objectives", "term_zh": "目标管理", "topic": "AB2.2", "def_zh": "上下级共同设定并追踪目标。"},
        {"term_en": "On-the-job training", "term_zh": "在岗培训", "topic": "AB2.1", "def_zh": "工作中边干边学（便宜、缺系统）。"},
        {"term_en": "Appraisal", "term_zh": "绩效评估", "topic": "AB2.1", "def_zh": "定期评价表现并反馈发展。"},
        {"term_en": "Dismissal", "term_zh": "解雇", "topic": "AB2.1", "def_zh": "因过错解除合同（≠裁员）。"},
        {"term_en": "Job rotation", "term_zh": "岗位轮换", "topic": "AB2.1", "def_zh": "轮岗培养多技能、减少单调。"},
        {"term_en": "Flat structure", "term_zh": "扁平结构", "topic": "AB2.2", "def_zh": "层级少、幅度宽、沟通快。"},
        {"term_en": "Centralisation", "term_zh": "集权", "topic": "AB2.2", "def_zh": "决策集中于高层（一致性 vs 灵活）。"},
        {"term_en": "Mass market", "term_zh": "大众市场", "topic": "AB3.1", "def_zh": "面向广泛人群（规模 vs 同质）。"},
        {"term_en": "Brand image", "term_zh": "品牌形象", "topic": "AB3.1", "def_zh": "消费者对品牌的整体感知。"},
        {"term_en": "Product differentiation", "term_zh": "产品差异化", "topic": "AB3.1", "def_zh": "让产品区别于竞品的特征。"},
        {"term_en": "Sampling", "term_zh": "抽样", "topic": "AB3.1", "def_zh": "随机/配额/系统等抽选调研对象。"},
        {"term_en": "Boston matrix", "term_zh": "波士顿矩阵", "topic": "AB3.1", "def_zh": "按市占与增长率分：明星/现金牛/问题/瘦狗。"},
        {"term_en": "Competitive pricing", "term_zh": "竞争导向定价", "topic": "AB3.2", "def_zh": "参照对手价格定价。"},
        {"term_en": "Price elasticity (marketing)", "term_zh": "需求价格弹性", "topic": "AB3.2", "def_zh": "价格敏感度决定提价/降价空间。"},
        {"term_en": "Sales promotion", "term_zh": "营业推广", "topic": "AB3.2", "def_zh": "买赠/折扣/抽奖等短期刺激。"},
        {"term_en": "Public relations", "term_zh": "公共关系", "topic": "AB3.2", "def_zh": "塑造舆论形象的沟通（新闻/事件）。"},
        {"term_en": "Direct marketing", "term_zh": "直接营销", "topic": "AB3.2", "def_zh": "一对一触达（邮件/电话/DM）。"},
        {"term_en": "Job production", "term_zh": "单件生产", "topic": "AB4.1", "def_zh": "按订单一次性生产（定制）。"},
        {"term_en": "Flow production", "term_zh": "流水生产", "topic": "AB4.1", "def_zh": "连续大批量流水线。"},
        {"term_en": "Buffer stock", "term_zh": "缓冲存货", "topic": "AB4.2", "def_zh": "应对需求波动的最低库存。"},
        {"term_en": "Lead time", "term_zh": "供货周期", "topic": "AB4.2", "def_zh": "下单到收货的时间。"},
        {"term_en": "Hire purchase", "term_zh": "分期付款购买", "topic": "AB5.1", "def_zh": "分期付清后取得所有权。"},
        {"term_en": "Business angel", "term_zh": "天使投资人", "topic": "AB5.1", "def_zh": "个人早期股权投资+辅导。"},
        {"term_en": "Working capital cycle", "term_zh": "营运资本循环", "topic": "AB5.1", "def_zh": "现金→存货→应收→现金的循环。"},
        {"term_en": "Gross profit margin", "term_zh": "毛利率", "topic": "AB5.2", "def_zh": "毛利÷收入×100%。"},
        {"term_en": "Creditor days", "term_zh": "应付账款天数", "topic": "AB5.2", "def_zh": "应付÷采购×365。"},
        {"term_en": "Five forces", "term_zh": "波特五力", "topic": "AB6.1", "def_zh": "行业竞争结构：五力决定利润率。"},
        {"term_en": "Force field analysis", "term_zh": "力场分析", "topic": "AB6.2", "def_zh": "变革驱动力 vs 阻抗力诊断。"},
        {"term_en": "Contingency plan", "term_zh": "应急预案", "topic": "AB6.2", "def_zh": "针对突发情景的预定行动方案。"},
    ],
    # ---------------- COMPETITION (+24 → 40) ----------------
    "comp": [
        {"term_en": "Elevator pitch", "term_zh": "电梯演讲", "topic": "CP1.1", "def_zh": "30-60 秒讲清问题-方案-市场。"},
        {"term_en": "Proof of concept", "term_zh": "概念验证", "topic": "CP1.2", "def_zh": "证明核心假设可行的最小证据。"},
        {"term_en": "IP defensibility", "term_zh": "知识产权可防御性", "topic": "CP1.2", "def_zh": "专利/壁垒使创新难以被复制。"},
        {"term_en": "Verification", "term_zh": "查重验证", "topic": "CP1.2", "def_zh": "评委在线检索检验原创性。"},
        {"term_en": "Problem-solution fit", "term_zh": "问题-方案契合", "topic": "CP1.3", "def_zh": "方案确实解决所定义的问题。"},
        {"term_en": "Product-market fit", "term_zh": "产品-市场契合", "topic": "CP3.3", "def_zh": "市场真实需要并愿意付费。"},
        {"term_en": "Pivot", "term_zh": "转型", "topic": "CP3.3", "def_zh": "基于验证结果调整方向。"},
        {"term_en": "Runway", "term_zh": "资金跑道", "topic": "CP1.5", "def_zh": "现金÷月烧钱率＝存活月数。"},
        {"term_en": "Bootstrapping", "term_zh": "自筹资金", "topic": "CP1.5", "def_zh": "不靠外部融资滚动发展。"},
        {"term_en": "Equity", "term_zh": "股权", "topic": "CP1.5", "def_zh": "以公司股份换取投资。"},
        {"term_en": "Valuation", "term_zh": "估值", "topic": "CP1.5", "def_zh": "融资前后的公司价值定价。"},
        {"term_en": "Angel investor", "term_zh": "天使投资人", "topic": "CP1.5", "def_zh": "早期高风险个人投资者。"},
        {"term_en": "Seed round", "term_zh": "种子轮", "topic": "CP1.5", "def_zh": "产品验证期的首笔机构融资。"},
        {"term_en": "Revenue projections", "term_zh": "收入预测", "topic": "CP1.5", "def_zh": "3-5 年收入的假设驱动模型。"},
        {"term_en": "Budget reasonableness", "term_zh": "预算合理性", "topic": "CP1.5", "def_zh": "评委检验成本假设是否有据。"},
        {"term_en": "Investor appeal", "term_zh": "投资人吸引力", "topic": "CP1.2", "def_zh": "叙事维度：值得进一步了解吗。"},
        {"term_en": "Narrative structure", "term_zh": "叙事结构", "topic": "CP1.2", "def_zh": "问题→方案→验证→愿景的起承转合。"},
        {"term_en": "Market insight", "term_zh": "市场洞察", "topic": "CP1.2", "def_zh": "Marketing 维度：真懂客户与场景。"},
        {"term_en": "Entry & adoption", "term_zh": "进入与采纳", "topic": "CP1.2", "def_zh": "客户如何首次接触并采用产品。"},
        {"term_en": "Engagement channels", "term_zh": "触达渠道", "topic": "CP1.2", "def_zh": "持续触达用户的渠道组合。"},
        {"term_en": "WSAP", "term_zh": "BPA 专项赛", "topic": "CP2.1", "def_zh": "Workplace Skill Assessment Program 各方向赛事。"},
        {"term_en": "NLC", "term_zh": "BPA 全国领导力大会", "topic": "CP2.1", "def_zh": "National Leadership Conference 决赛周。"},
        {"term_en": "Objective test scope", "term_zh": "客观题范围", "topic": "CP2.1", "def_zh": "管理/营销/财务/经济/法律通识。"},
        {"term_en": "Case diagnosis", "term_zh": "案例诊断", "topic": "CP2.2", "def_zh": "先用工具定位问题再提方案。"},
    ],
}

# ===========================================================================
# 2. QUIZ EXPANSION
# ===========================================================================

QUIZ_EXTRA = {
    "al-econ": [
        {"q": "YED = −0.3 的商品是？", "opts": ["劣等品", "奢侈品", "必需品", "替代品"], "a": 0, "why": "YED<0 收入升需求降。"},
        {"q": "PES 供给弹性最大的情形是？", "opts": ["长期且有闲置产能", "短期产能满负荷", "无库存", "要素不可替代"], "a": 0, "why": "时间与产能是 PES 两大决定因素。"},
        {"q": "庇古税的理想税率应等于？", "opts": ["边际外部成本", "平均成本", "边际私人成本", "总成本"], "a": 0, "why": "让私人成本=社会成本，产量回到社会最优。"},
        {"q": "边际报酬递减发生在？", "opts": ["短期，可变要素追加于固定要素", "长期所有要素同比例增加", "只有农业", "需求侧"], "a": 0, "why": "短期固定要素被摊薄；长期是规模经济问题。"},
        {"q": "垄断者停业点条件是？", "opts": ["P < AVC", "P < ATC", "P < MC", "TR < TC"], "a": 0, "why": "价格覆盖不了可变成本即应停产。"},
        {"q": "结构性失业的对策是？", "opts": ["再培训与迁移支持", "降息", "减税", "货币贬值"], "a": 0, "why": "技能错配需供给侧（培训）解决。"},
        {"q": "挤出效应发生的渠道是？", "opts": ["政府借款推高利率压投资", "出口减少", "货币升值", "税收增加"], "a": 0, "why": "财政扩张→利率↑→私人投资↓。"},
        {"q": "乘数大小取决于？", "opts": ["边际消费倾向 MPC", "税率", "人口", "汇率"], "a": 0, "why": "乘数=1/(1−MPC)，MPC 越大乘数越大。"},
        {"q": "配额与关税的关键区别是？", "opts": ["配额不产生政府收入", "关税不推高价", "配额更自由", "关税限制数量"], "a": 0, "why": "配额限量，租金归许可持有人。"},
        {"q": "固定汇率制下本币高估时，央行应？", "opts": ["卖出外汇储备买入本币", "买入外汇卖出本币", "提高关税", "不干预"], "a": 0, "why": "支撑本币需消耗储备（不可持续）。"},
        {"q": "以下最能衡量\"发展\"而非\"增长\"的指标是？", "opts": ["HDI", "名义 GDP", "GDP 总量", "出口额"], "a": 0, "why": "HDI 含教育/寿命/收入三维。"},
        {"q": "劳动需求的决定基础是？", "opts": ["MRP（边际收益产品）", "最低工资", "工会力量", "人口总量"], "a": 0, "why": "厂商按劳动带来的收益增量雇佣。"},
        {"q": "限制定价（limit pricing）的目的是？", "opts": ["阻止新企业进入", "最大化短期利润", "清库存", "政府要求"], "a": 0, "why": "牺牲部分当前利润换取长期市场地位。"},
        {"q": "从价税使供给曲线？", "opts": ["绕原点旋转变得更陡", "平行上移", "平行下移", "不变"], "a": 0, "why": "按价格比例征收，价格越高税额越大。"},
        {"q": "等边际原则的公式是？", "opts": ["MUa/Pa = MUb/Pb", "MUa=MUb", "Pa=Pb", "TU 最大时 MU=0"], "a": 0, "why": "单位货币边际效用相等时总效用最大。"},
    ],
    "ib-bus": [
        {"q": "非营利组织的\"利润\"如何处理？", "opts": ["再投入使命", "分配股东", "缴税为主", "存银行"], "a": 0, "why": "NPO 盈余服务于组织宗旨。"},
        {"q": "CSR 与盈利冲突时，BM 四概念提示我们？", "opts": ["用可持续视角做权衡评估", "CSR 优先", "利润优先", "放弃评估"], "a": 0, "why": "新大纲强调概念透镜下的 balanced judgement。"},
        {"q": "纵向整合的目的是？", "opts": ["控制供应链环节", "跨行业分散风险", "减少同业竞争", "提高品牌"], "a": 0, "why": "上游保供、下游控渠道。"},
        {"q": "以下哪个是 Herzberg 的\"激励因素\"？", "opts": ["成就感", "工资", "工作条件", "公司政策"], "a": 0, "why": "激励因素：成就/认可/责任/成长。"},
        {"q": "计件工资的主要问题是？", "opts": ["重数量轻质量", "成本高", "无法计算", "不合法"], "a": 0, "why": "按量计酬可能牺牲质量标准。"},
        {"q": "矩阵结构的最大特点是？", "opts": ["双线汇报", "集权", "无中层", "按职能单一汇报"], "a": 0, "why": "职能+项目交叉管理。"},
        {"q": "长期融资匹配长期用途体现的是？", "opts": ["匹配原则", "谨慎原则", "持续经营", "权责发生制"], "a": 0, "why": "期限错配是流动性风险根源。"},
        {"q": "毛利率下降但净利率稳定，最可能的原因是？", "opts": ["费用率下降", "销售成本上升", "税收减少", "存货增加"], "a": 0, "why": "毛利被费用端改善抵消。"},
        {"q": "速动比率远大于 1 说明？", "opts": ["资金效率可能偏低", "即将破产", "存货太多", "负债过高"], "a": 0, "why": "流动资产闲置，机会成本高。"},
        {"q": "ARR 相对回收期的优势是？", "opts": ["考虑全部年限与利润", "更简单", "考虑时间价值", "忽略现金流"], "a": 0, "why": "回收期只看回本速度与前期现金流。"},
        {"q": "不利差异（adverse variance）出现在？", "opts": ["实际成本高于预算", "实际收入高于预算", "预算等于实际", "成本下降"], "a": 0, "why": "成本超支或收入不及预期。"},
        {"q": "二手（secondary）调研的主要缺点是？", "opts": ["未必贴合具体问题", "成本太高", "速度太慢", "无法数字化"], "a": 0, "why": "现成数据口径与目的可能不匹配。"},
        {"q": "PLC 导入期最适合的促销目标是？", "opts": ["认知（awareness）", "忠诚度", "提醒", "竞争性降价"], "a": 0, "why": "AIDA 前段：先让人知道。"},
        {"q": "渗透定价的适用前提是？", "opts": ["需求弹性大、可快速放量", "技术垄断", "礼品市场", "成本加成"], "a": 0, "why": "低价换量，靠规模摊薄成本。"},
        {"q": "Kaizen 与 TQM 的共同点是？", "opts": ["全员参与的持续改进", "事后检验", "外包质量", "终端把关"], "a": 0, "why": "两者都强调预防与全员文化。"},
    ],
    "al-bus": [
        {"q": "初创企业首要目标通常是？", "opts": ["生存", "利润最大化", "多元化", "上市"], "a": 0, "why": "现金流安全先于扩张。"},
        {"q": "合伙企业相对独资的优势是？", "opts": ["共担风险与互补技能", "有限责任", "免于纳税", "融资渠道不变"], "a": 0, "why": "合伙仍无限责任，但资源更多。"},
        {"q": "控股公司制的核心特征是？", "opts": ["通过持股控制子公司", "只有一层管理", "无股东会", "必须国有"], "a": 0, "why": "母公司以股权纽带控制。"},
        {"q": "集权的主要优点是？", "opts": ["决策一致、战略统一", "响应速度快", "员工自主性高", "沟通层级少"], "a": 0, "why": "代价是灵活性下降。"},
        {"q": "随机抽样优于便利抽样是因为？", "opts": ["减少样本偏差", "更便宜", "更快", "样本更大"], "a": 0, "why": "每位个体被抽中概率相等。"},
        {"q": "波士顿矩阵中\"现金牛\"是？", "opts": ["高市占低增长", "高市占高增长", "低市占高增长", "低市占低增长"], "a": 0, "why": "成熟业务稳定产出现金。"},
        {"q": "销售推广（sales promotion）属于？", "opts": ["短期刺激", "长期品牌建设", "定价策略", "渠道决策"], "a": 0, "why": "折扣/买赠追求即时销量。"},
        {"q": "单件（job）生产的特点是？", "opts": ["高度定制、单位成本高", "大批量低成本", "连续流水", "无库存"], "a": 0, "why": "按订单一次性生产。"},
        {"q": "应收账款天数上升提示？", "opts": ["回款变慢、现金压力", "销售下滑", "存货积压", "毛利改善"], "a": 0, "why": "赊销占款时间拉长。"},
        {"q": "风险投资（VC）适合？", "opts": ["高成长高风险企业", "成熟公用事业", "个体户", "政府项目"], "a": 0, "why": "VC 以股权博高回报。"},
        {"q": "力场分析中要推动变革应？", "opts": ["增强驱动力或削弱阻力", "只加强控制", "忽略阻力", "增加层级"], "a": 0, "why": "Lewin：变革=改变两力对比。"},
        {"q": "\"差异化\"通用战略的风险是？", "opts": ["溢价不足以覆盖成本", "成本失控", "市场太大", "无需品牌"], "a": 0, "why": "独特性维护成本高，需溢价支撑。"},
    ],
    "comp": [
        {"q": "康莱德 Innovation Stage 的核心交付物是？", "opts": ["Innovation Brief", "财务审计", "专利证书", "用户名单"], "a": 0, "why": "Activation 交 Canvas，Innovation 交 Brief。"},
        {"q": "康莱德五大赛道不包括？", "opts": ["房地产科技", "航空航天", "能源环境", "健康营养"], "a": 0, "why": "官方五赛道：航空/网络/能源/健康/水。"},
        {"q": "Storytelling 维度中的 Credibility Boost 指？", "opts": ["团队背景增强可信度", "引用更多论文", " louder 演讲", "更多动画"], "a": 0, "why": "评委看团队是否配得上这个项目。"},
        {"q": "Verification（查重）针对的是？", "opts": ["Innovation 维度的原创性", "财务数字", "演讲时长", "团队分工"], "a": 0, "why": "评委在线检索验证方案是否独特。"},
        {"q": "runway 的计算是？", "opts": ["现金余额÷月烧钱率", "收入×3", "融资额×估值", "用户数÷流失率"], "a": 0, "why": "还能活多久。"},
        {"q": "种子轮（seed）一般在什么阶段？", "opts": ["产品验证期", "IPO 前", "盈利后", "清算时"], "a": 0, "why": "验证 MVP 与早期市场。"},
        {"q": "BPA 案例题\"论证\"环节要求？", "opts": ["利弊权衡+优先级", "只写优点", "复述案例", "引用法条"], "a": 0, "why": "结构化论证优于单边罗列。"},
        {"q": "CBPA 八步研习法的第一步通常是？", "opts": ["选题与方向确认", "路演彩排", "财务建模", "提交答辩"], "a": 0, "why": "从选题到陈述递进式备赛。"},
        {"q": "Pitch Deck 的标准页数参考？", "opts": ["10-15 页", "30-40 页", "3 页", "无限制"], "a": 0, "why": "评委注意力有限，贵精不贵多。"},
        {"q": "以下哪项最能提升 Finances 维度得分？", "opts": ["有依据的成本与收入假设", "更大的融资额", "更多赞助商 logo", "彩色图表"], "a": 0, "why": "评委检验 budget reasonableness。"},
    ],
}

# ===========================================================================
# 3. IA / EE / ESSAY GUIDES (detailed)
# ===========================================================================

IAEE = {
    "ib-econ": {
        "title": "IB 经济学 IA 与 EE 指南",
        "sections": [
            {"h": "IA · 内部评估（评论组合）",
             "items": [
                "结构：3 篇基于真实新闻的评论（每篇正文≤800 词），分别取材于微观、宏观、全球经济三个不同单元（不能同单元重复）。",
                "选文标准：文章发布于提交前 12 个月内；来源可靠（报刊/通讯社）；与教学大纲直接相关且含可引用的经济学内容（数据、政策、价格变化）。",
                "每篇必含：① 关键术语定义（教学大纲措辞）② 两张相关且完全标注的图表 ③ 沿图表展开的因果链分析 ④ 指出假设与局限的评估 ⑤ 引用出处。",
                "写作流程：选文 → 圈出 2-3 个可图解的经济学概念 → 起草因果链 → 画图配文 → 加评估段 → 删到 800 词内（图注、引用不计词）。",
                "高频失分（考官报告）：图表无全轴标注/不引用文章具体数据；只描述不分析；评估空洞（\"取决于情况\"而无判断）；超字数被截断。",
             ]},
            {"h": "EE · 拓展论文（经济学）",
             "items": [
                "研究问题（RQ）是成败关键：聚焦、可争辩、可证。好例：\"X 市 2021-2024 出租车牌照价格下跌在多大程度上可由网约车的进入解释？\"；坏例：\"全球化好吗？\"（过宽、无数据）。",
                "标准结构：引言含 RQ 与背景（~500 词）→ 理论框架（相关模型与图表）→ 证据主体（二手数据为主，可辅访谈/问卷）→ 反方证据与局限 → 有条件结论（~400 词）。",
                "评估标准（34 分制）：A 聚焦与方法 /6 · B 知识理解 /6 · C 批判性思维 /12 · D 呈现 /4 · E 投入（RPPF 反思）/6。C 权重最大——分析>描述。",
                "常见失分：RQ 过宽无法 4000 词内回答；只叙述数据不运用模型；图表与论证脱节；结论与前文证据不匹配；RPPF 流水账无反思。",
                "时间线建议：DP1 下学期定题 → 暑假收集数据写初稿 → DP2 上学期修改定稿（预留导师一轮反馈）。",
             ]},
        ],
        "links": [
            {"label": "→ 查看官方 IA 学生作业示例 + 考官评语（本地 44 份）", "href": "index.html#/ia"},
            {"label": "→ 真题与评分方案（评分语言学习的最佳材料）", "href": "index.html#/papers"},
            {"label": "→ 考官报告（按主题，看官方失分统计）", "href": "index.html#/topic/2.5"},
        ],
    },
    "ib-bus": {
        "title": "IB 商业管理 IA 与 EE 指南",
        "sections": [
            {"h": "IA · 商业研究项目（Business Research Project，2022 大纲）",
             "items": [
                "结构：基于一家真实组织的研究问题，正文约 1800 词；SL 占 25%、HL 占 20%。",
                "三要素缺一不可：① 明确的研究问题（How/Should 型，可调查）② 一手研究（问卷/访谈/观察，须自做）③ 二手研究（公司报告/行业数据）。",
                "分析工具按 RQ 选取 2-3 个即可：SWOT、Ansoff、比率分析、盈亏平衡、PLC/STP、力场分析——工具为论证服务，不要堆砌。",
                "必含结构：标题页 → 研究问题与组织背景 → 方法说明（样本、局限）→ 主体分析（工具+数据）→ 结论与建议 → 文献与附录（问卷原文等）。",
                "高分特征：结论直接回答 RQ 并给出行动建议；诚实指出一手数据的局限（样本小/偏差）；工具之间相互印证。",
                "高频失分：RQ 是\"是什么\"而非\"怎么做\"；只有二手没有一手；工具罗列不使用；结论与证据脱节；超 1800 词被截断。",
             ]},
            {"h": "EE · 拓展论文（商业管理）",
             "items": [
                "RQ 应落在一个具体组织的具体决策：如\"Z 公司是否应通过并购进入东南亚市场？\"——有边界、可证据、可评估。",
                "评估标准与经济 EE 相同（A/6 B/6 C/12 D/4 E/6）：C 批判性思维占 12 分，必须用商业工具+真实数据双向论证。",
                "理论与证据平衡：纯理论堆砌或纯新闻叙述都拿不到 B/C 档；每个工具的输出都要回扣 RQ。",
                "常见失分：选上市公司却只用年报摘要；没有对立观点；建议段与前文分析无关。",
             ]},
        ],
        "links": [],
    },
    "al-econ": {
        "title": "AL 经济 · 无 IA/EE，重点是大题（Essay）写作",
        "sections": [
            {"h": "Paper 4 · 25 分论述文结构",
             "items": [
                "CIE A2 大题评估导向：定义→图表→应用→两面评估→结论，缺项即失分。",
                "标准段落骨架（每论点）：claim（论点句）→ diagram（支撑模型）→ explain（因果链条）→ example（现实案例/数据）→ evaluate（该论点的局限）。",
                "结论必须\"有立场\"：比较两方论点的强弱（权重、时间维度、假设敏感性），再下判断——\"两者都重要\"不给分。",
                "时间管理：25 分题约 35-40 分钟；先花 3 分钟列\"论点-图-例\"提纲再动笔。",
                "高频失分：画图不标注轴/曲线；只用宏观叙事不用模型；评估只写一句话；案例陈旧（10 年前）无数据。",
             ]},
            {"h": "数据题（Paper 2/4 data response）技巧",
             "items": [
                "先读问题再读材料，带着问题定位数据；引用材料时给出具体数字而非\"如材料所示\"。",
                "a/b 问（定义+解释）答题直给，不铺陈；c/d 问（分析+评估）按 essay 骨架压缩。",
                "计算题：写出公式→代入→保留单位→结果给经济含义（如\"PED=0.4 说明涨价可增收\"）。",
             ]},
        ],
        "links": [],
    },
    "al-bus": {
        "title": "AL 商科 · 无 IA/EE，重点是 Paper 3 大案例决策",
        "sections": [
            {"h": "Paper 3 · 案例决策题（3 小时，权重 50%）",
             "items": [
                "题型主线：给定组织背景与数据 → 多个决策选项 → 要求分析并\"建议（recommend/justify）\"。",
                "作答三步：诊断（用 SWOT/比率/Ansoff 定位问题）→ 方案（每个选项用数据算一遍：BEP、比率、现金流）→ 论证（利弊+优先级+风险对冲）。",
                "命令词分级：state/identify 给点即止；explain 要因果链；discuss/evaluate 要两面；justify/recommend 要明确立场+数据支撑。",
                "计算必查：盈亏平衡、毛利率/ROCE、回收期/ARR/NPV、现金流预测——写公式带单位，结果要回到\"对企业意味着什么\"。",
                "高频失分：只描述案例不分析；建议无数据支撑；忽略案例给的限制条件（资金/产能/文化）；时间失控（先做会算的题）。",
             ]},
        ],
        "links": [],
    },
    "comp": {
        "title": "竞赛交付物写作指南（康莱德 & BPA）",
        "sections": [
            {"h": "康莱德 · Lean Canvas 12 问 & Innovation Brief",
             "items": [
                "每题 ≤40 词（Q6 ≤10 词），Portal 硬截断——先写要点再压字数。",
                "Problem 三要素：具体人群 + 量化数据（带年份来源）+ 当季主题词；把 Solution 写进 Problem 是最常见红线。",
                "Innovation Brief 按 6 维评分自查：Theme 呼应了吗？Innovation 查重过吗？Storytelling 有起承转合吗？Practicality 有概念验证证据吗？Marketing 懂客户吗？Finances 假设有据吗？",
                "提交后 Canvas 仍可迭代——保留各版本，评委欣赏\"进化轨迹\"。",
             ]},
            {"h": "BPA · 案例分析写作",
             "items": [
                "结构：诊断（工具）→ 方案（2-3 个选项比较）→ 建议（明确一个）→ 实施要点与风险。",
                "每个论点配数据/案例证据；引用格式规范（APA/Harvard）。",
                "客观题备考：按学科知识树刷商科+经济基础（本站练习问答即可自测）。",
             ]},
        ],
        "links": [
            {"label": "→ 赛代学地图（找写作所需的学科知识点）", "href": "#/s/comp/mapping"},
        ],
    },
}

# ===========================================================================
# 4. TEACHING RESOURCES (textbook chapter maps & readings)
# ===========================================================================

RESOURCES = {
    "ib-econ": {
        "groups": [
            {"h": "本地教材库（69 本，含页级跳转）",
             "items": [
                "主教材：Cambridge Tragakes 3rd (2020) · Oxford Blink & Dorton 3rd (2020) · Hodder Hoang (2020) · Pearson Maley & Welker 2nd (2022)",
                "🎯 学习指南（难点详解）：Oxford Study Guide (Ziogas) · Noema《IB Economics in a Nutshell》(Tragakes) · IB Academy HL/SL Study Guide · OSC Revision Guide · Oxford IB Prepared (2022)",
                "📝 练习册：Hodder Paper 3 Workbook · Quantitative Skills Workbook · Pearson Worksheets · IBID Workbook · Level7 55 套 Paper 3 量化练习",
             ],
             "link": {"label": "→ 打开教材库（封面/章节→主题→原文页）", "href": "index.html#/textbooks"}},
            {"h": "官方与考试资料",
             "items": [
                "Economics Guide 2024（现行大纲）· Specimen Papers · Subject Reports（考官报告，按主题关联）",
                "真题 2022-2025（May/Nov × TZ × SL/HL × Paper 1-3）+ 配套 markscheme",
                "IA 官方示例（21 份学生作业 + 21 份考官评语，配对展示）",
             ],
             "link": {"label": "→ 真题库 / IA 示例", "href": "index.html#/papers"}},
        ],
    },
    "ib-bus": {
        "groups": [
            {"h": "推荐教材与章节映射（思铺备课库）",
             "items": [
                "Pearson BM 2023 (Atkins/Opfer/Navaid)：Ch1.1-1.3 企业与环境 → BB1.1-1.4",
                "Cambridge BM 2015 (Stimpson & Smith)：Ch1.1-1.3 外部环境 → BB1.1/1.4；Ch2.1-2.3 HRM → BB2.1-2.5",
                "Oxford BM Course Companion (Lominé et al.)：Ch1-3 企业基础 → BB1.x；Ch4-6 营销 → BB4.x",
                "Cambridge AS/A Level BM 3rd ed：Ch3.3 盈亏平衡 → BB5.4；Ch4.1-4.7 营销 → BB4.x",
                "共同覆盖：财务三表与比率 → BB3.3-3.8；运营与质量 → BB5.x",
             ]},
            {"h": "竞赛与拓展阅读",
             "items": [
                "《How to Present to Investors》(Sequoia) → Pitch 结构 → BB4.5/竞赛",
                "Business Model Generation (Osterwalder) → BMC 九格 → BB1.5",
                "Lean Startup (Ries) → MVP/验证学习 → BB5.1",
             ]},
        ],
    },
    "al-bus": {
        "groups": [
            {"h": "推荐教材与章节映射（思铺备课库）",
             "items": [
                "Cambridge International AS & A Level Business 3rd ed：全书主体即考纲结构（9609）",
                "Pearson BM 2023 / Cambridge BM 2015 / Oxford BM：作为交叉补强（与 IB BM 共用章节体系）",
                "Cambridge AS/A Business Workbook：章末练习对应 Paper 1/2 题型",
             ]},
            {"h": "指定阅读与案例",
             "items": [
                "行业研究：宠物行业深度报告 · 谷子经济 · 石头科技 TAM/SAM/SOM 案例（思铺 Learning Materials）",
                "BP Sample 与用户访谈实录 → Paper 3 案例分析训练材料",
             ]},
        ],
    },
    "al-econ": {
        "groups": [
            {"h": "推荐教材与章节映射（本地库可直接打开）",
             "items": [
                "Cambridge Tragakes 3rd (2020)：Ch1-2 市场与弹性 → AE1/AE2；Ch7-8 宏观 → AE5",
                "Hodder Hoang (2020)：Ch1-3 市场基础 → AE2；Ch15-16 发展经济 → AE6.3",
                "AL 与 IB 经济高度重叠（约 85%）：本站 IB 经济图表库（28 图）直接适用于 AL 考试画图",
             ],
             "link": {"label": "→ 打开本地教材库（含页级跳转）", "href": "index.html#/textbooks"}},
            {"h": "练习资源",
             "items": [
                "历年 CIE 9708 真题（建议按 topic 刷 Paper 1 MCQ）",
                "本站图表训练（28 图 31 题）+ 五科目练习问答",
             ],
             "link": {"label": "→ 图表解析与训练", "href": "index.html#/diagrams"}},
        ],
    },
    "comp": {
        "groups": [
            {"h": "官方文件（思铺备课库）",
             "items": [
                "Conrad：US Student Guide 2025-2026 · China Student Guide · Lean Canvas 官方模板与介绍手册",
                "BPA：国际官网竞赛介绍 · WSAP 赛事列表 · CBPA 八步研习法 Step 1-8 课件与 Task 文档",
                "评分标准：康莱德 6 维（含 Qwen 审校纠偏版）· BPA 各 event rubric",
             ]},
            {"h": "内部教学沉淀",
             "items": [
                "《康莱德学生写作手册》Lean Canvas 12 问逐题指南（出题意图/句型/自检/红线）",
                "OCP-9 教学大纲与 KSA 能力表（BEST-MVP 商业进阶 11 节次）",
                "2025 康莱德 14 份项目实样（Lean Canvas + Innovation Brief）",
             ]},
        ],
    },
}

# ===========================================================================
# 5. AL-ECON DIAGRAM MAPPING (reuse IB econ diagram images)
# ===========================================================================

DIAGRAM_MAP = {
    "AE1.1": ["ppc"],
    "AE2.1": ["demand_curve", "supply_curve", "equilibrium"],
    "AE2.2": ["ped", "pes"],
    "AE2.3": ["equilibrium"],
    "AE2.4": ["tax", "subsidy"],
    "AE3.1": ["neg_ext_prod", "neg_ext_cons", "pos_ext"],
    "AE3.3": ["price_ceiling", "price_floor"],
    "AE4.3": ["monopoly"],
    "AE5.1": ["circular_flow"],
    "AE5.2": ["ad", "sras", "lras", "adas_gap", "business_cycle"],
    "AE5.3": ["adas_gap"],
    "AE5.5": ["lorenz"],
    "AE5.4": ["monetary_transmission", "supply_side"],
    "AE6.1": ["comparative_advantage", "tariff"],
    "AE6.2": ["exchange_rate", "jcurve"],
}
