"""IGCSE Business Studies (CIE 0450) subject content, aligned with the local
past-paper library (2002-2025, 239 qp / 231 ms / er per year)."""

IGCSE_BUS = {
    "id": "igcse-bus", "name_zh": "IGCSE 商科", "name_en": "IGCSE Business Studies (0450)",
    "accent": "#ec4899", "level_names": {"both": "核心", "core": "Core", "ext": "Extended"},
    "syllabus": [
        {"id": "ig1", "order": 1, "title_en": "Understanding Business Activity", "title_zh": "理解商业活动",
         "short_zh": "商业活动", "topics": [
            {"id": "IG1.1", "title_en": "Business activity, objectives & added value", "title_zh": "商业活动、目标与增值", "level": "both",
             "desc_zh": "需要与欲望、稀缺、机会成本、专业化与分工；企业目标（生存/增长/利润/市场份额）；增值的计算与来源。",
             "key_concepts": ["Added value", "Opportunity cost", "Specialisation", "Business objectives"],
             "exam_tips": ["增值＝产出价值−购入成本，会算并会提\"如何提高增值\"（技术/品牌/服务）。",
                            "机会成本题先答定义\"放弃的次优选择\"，再举企业资源分配的例子。"]},
            {"id": "IG1.2", "title_en": "Types of business organisation", "title_zh": "企业组织形式", "level": "both",
             "desc_zh": "独资/合伙/私人有限公司/公众有限公司；特许经营与合资；无限责任 vs 有限责任；法人化。",
             "key_concepts": ["Sole trader", "Partnership", "Limited liability", "Franchise", "Joint venture"],
             "exam_tips": ["比较组织形式四维度：责任、融资、控制权、利润分配。",
                            "\"为什么要法人化(incorporate)\"＝有限责任+融资渠道+永续经营。"]},
            {"id": "IG1.3", "title_en": "Growth, M&A and scale", "title_zh": "增长、并购与规模", "level": "both",
             "desc_zh": "内生/外延增长；横向/纵向/混合并购；规模经济与规模不经济。",
             "key_concepts": ["Internal growth", "Merger", "Takeover", "Economies of scale"],
             "exam_tips": ["并购成败评估：协同效应 vs 整合成本/文化冲突，两面写。",
                            "规模经济五类（采购/技术/财务/管理/风险）各举一例。"]},
            {"id": "IG1.4", "title_en": "Stakeholders & mixed economy", "title_zh": "利益相关者与混合经济", "level": "both",
             "desc_zh": "内部/外部/关联利益相关者及其冲突；公营/私营/混合经济；政府影响企业的方式。",
             "key_concepts": ["Stakeholder", "Conflict", "Mixed economy", "Privatisation"],
             "exam_tips": ["stakeholder 题先分类再谈\"谁受什么影响\"，别只列名字。"]},
            {"id": "IG1.5", "title_en": "Business communication", "title_zh": "商业沟通", "level": "both",
             "desc_zh": "沟通方式（口头/书面/视觉/电子）与选择因素；沟通障碍与克服。",
             "key_concepts": ["Communication barriers", "Effective communication"],
             "exam_tips": ["科技改善沟通的评估：速度/成本↑ vs 缺乏人情味/信息安全。"]},
        ]},
        {"id": "ig2", "order": 2, "title_en": "People in Business", "title_zh": "商业中的人",
         "short_zh": "人力资源", "topics": [
            {"id": "IG2.1", "title_en": "HR: recruitment, training & contracts", "title_zh": "招聘、培训与雇佣", "level": "both",
             "desc_zh": "劳动力规划；招聘流程（内部/外部）；岗位说明与人员规范；在岗/脱岗培训；雇佣合同；裁员 vs 解雇。",
             "key_concepts": ["Recruitment", "Job description", "Training", "Redundancy", "Dismissal"],
             "exam_tips": ["内部招聘（省钱快、知根知底）vs 外部（新视角、更大池）是高频对比题。",
                            "区分 dismissal（过错解雇）与 redundancy（岗位消失）。"]},
            {"id": "IG2.2", "title_en": "Motivation", "title_zh": "激励", "level": "both",
             "desc_zh": "Taylor 科学管理；Maslow 需求层次；Herzberg 双因素；金钱/非金钱激励方法。",
             "key_concepts": ["Taylor", "Maslow", "Herzberg", "Financial incentives", "Job enrichment"],
             "exam_tips": ["\"金钱是不是最佳激励\"必两面答：行业/岗位/文化不同效果不同。",
                            "非金钱激励清单：轮岗/丰富化/授权/团队/表彰，答题至少给 3 个并说明机制。"]},
            {"id": "IG2.3", "title_en": "Organisation, management & unions", "title_zh": "组织、管理与工会", "level": "both",
             "desc_zh": "组织结构（层级/幅度/指挥链）；集权 vs 分权；领导风格（专制/民主/放任）；工会与集体谈判。",
             "key_concepts": ["Span of control", "Delegation", "Leadership styles", "Trade union"],
             "exam_tips": ["领导风格题绑定情境（危机→专制，创意→民主）。",
                            "工会作用：工资谈判/工作条件/纠纷处理；资方视角的利弊评估。"]},
        ]},
        {"id": "ig3", "order": 3, "title_en": "Marketing", "title_zh": "市场营销",
         "short_zh": "营销", "topics": [
            {"id": "IG3.1", "title_en": "Market & customer needs", "title_zh": "市场与顾客需求", "level": "both",
             "desc_zh": "大众市场 vs 利基市场；市场导向 vs 产品导向；需求弹性入门（价格变化对需求的影响）。",
             "key_concepts": ["Mass market", "Niche market", "Market orientation"],
             "exam_tips": ["利基：小众高溢价低竞争；大众：规模经济但竞争激烈。"]},
            {"id": "IG3.2", "title_en": "Market research", "title_zh": "市场调研", "level": "both",
             "desc_zh": "一手/二手调研；定量/定性方法；抽样与偏差；调研的用途与局限。",
             "key_concepts": ["Primary research", "Secondary research", "Sampling", "Bias"],
             "exam_tips": ["调研方法评估三件套：成本、速度、可靠性/样本。"]},
            {"id": "IG3.3", "title_en": "Marketing mix: product", "title_zh": "营销组合：产品", "level": "both",
             "desc_zh": "产品类型（便利/购物/特色）；品牌与包装；产品生命周期与延伸策略。",
             "key_concepts": ["Product life cycle", "Extension strategy", "Brand"],
             "exam_tips": ["PLC 四阶段各配 4P 策略变化——延伸策略（新包装/新市场/降价）常考。"]},
            {"id": "IG3.4", "title_en": "Marketing mix: price", "title_zh": "营销组合：价格", "level": "both",
             "desc_zh": "成本加成/竞争导向/渗透/撇脂/心理/促销定价；价格与需求关系；定价策略选择。",
             "key_concepts": ["Cost-plus", "Penetration", "Skimming", "Psychological pricing"],
             "exam_tips": ["渗透 vs 撇脂的适用条件（弹性/竞争/形象）必考。"]},
            {"id": "IG3.5", "title_en": "Marketing mix: promotion", "title_zh": "营销组合：促销", "level": "both",
             "desc_zh": "线上广告（大众媒体）vs 线下促销（定向可衡量）；赞助/公关/直销/电商推广。",
             "key_concepts": ["Above-the-line", "Below-the-line", "Sponsorship", "Public relations"],
             "exam_tips": ["促销方式要与目标市场媒体习惯匹配（年轻人→社媒）。"]},
            {"id": "IG3.6", "title_en": "Marketing mix: place & technology", "title_zh": "营销组合：渠道与技术", "level": "both",
             "desc_zh": "分销渠道选择；零售/批发；电商与移动商务对传统渠道的冲击。",
             "key_concepts": ["Distribution channel", "Retailer", "E-commerce"],
             "exam_tips": ["渠道长度取舍：控制/成本/覆盖面三维度。"]},
            {"id": "IG3.7", "title_en": "Marketing strategy & legal controls", "title_zh": "营销战略与法律管制", "level": "both",
             "desc_zh": "营销战略（进入新市场/合理化）；营销中的法律管制（误导广告/价格法/消费者保护）。",
             "key_concepts": ["Marketing strategy", "Consumer protection", "Legal controls"],
             "exam_tips": ["法律管制的影响答\"对消费者/对企业/对竞争\"三方。"]},
        ]},
        {"id": "ig4", "order": 4, "title_en": "Operations Management", "title_zh": "运营管理",
         "short_zh": "运营", "topics": [
            {"id": "IG4.1", "title_en": "Production, productivity & quality", "title_zh": "生产、生产率与质量", "level": "both",
             "desc_zh": "生产方式（单件/批量/流水）；生产率与效率；精益生产与 JIT；质量检验 vs 质量保证；库存管理。",
             "key_concepts": ["Batch production", "Productivity", "Lean production", "JIT", "Quality assurance"],
             "exam_tips": ["JIT 评估：库存成本↓ vs 断供风险↑。",
                            "生产率=产出÷投入，提高途径（培训/技术/动机）要解释因果。"]},
            {"id": "IG4.2", "title_en": "Costs, revenue & break-even", "title_zh": "成本、收入与盈亏平衡", "level": "both",
             "desc_zh": "固定/可变/直接/间接成本；收入与利润；盈亏平衡计算与图解；安全边际；目标利润。",
             "key_concepts": ["Fixed cost", "Variable cost", "Break-even", "Margin of safety", "Contribution"],
             "exam_tips": ["BEP=FC÷(P−VC)；图上必标 FC、TC、TR、BEP 与安全边际。",
                            "盈亏平衡的局限：假设线性/单一产品/常量——评估题必写。"]},
            {"id": "IG4.3", "title_en": "Location & relocation", "title_zh": "选址与迁移", "level": "both",
             "desc_zh": "生产/零售/服务业选址因素（定量+定性）；迁移的利弊；海外选址。",
             "key_concepts": ["Location factors", "Relocation"],
             "exam_tips": ["选址因素按\"成本类 vs 非成本类\"分组作答。"]},
        ]},
        {"id": "ig5", "order": 5, "title_en": "Financial Information & Decisions", "title_zh": "财务信息与决策",
         "short_zh": "财务", "topics": [
            {"id": "IG5.1", "title_en": "Finance needs & sources", "title_zh": "资金需求与来源", "level": "both",
             "desc_zh": "为什么需要资金（启动/扩张/运营）；短期来源（透支/商业信用）vs 长期来源（贷款/发股/留存利润/租赁/风投）。",
             "key_concepts": ["Overdraft", "Trade credit", "Loan capital", "Share capital", "Venture capital", "Micro-finance"],
             "exam_tips": ["匹配原则：短用短借、长用长借——错配是流动性风险根源。",
                            "融资来源对比维度：成本/期限/控制权/风险。"]},
            {"id": "IG5.2", "title_en": "Cash flow & working capital", "title_zh": "现金流与营运资本", "level": "both",
             "desc_zh": "现金流预测（期初/流入/流出/净额/期末）；现金流问题的成因与对策；营运资本含义。",
             "key_concepts": ["Cash flow forecast", "Net cash flow", "Working capital"],
             "exam_tips": ["\"盈利却缺现金\"是经典考点：利润≠现金（赊销/存货/资本开支）。",
                            "改善现金流对策：催收/去库存/延付/透支，各写副作用。"]},
            {"id": "IG5.3", "title_en": "Income statements", "title_zh": "利润表", "level": "both",
             "desc_zh": "利润表结构（收入→销售成本→毛利→费用→净利→股利→留存）；用途与局限。",
             "key_concepts": ["Gross profit", "Net profit", "Retained profit", "Dividend"],
             "exam_tips": ["会读会算：毛利=收入−销售成本；净利=毛利−营业费用。",
                            "利润表局限：历史数据/非现金/会计政策差异。"]},
            {"id": "IG5.4", "title_en": "Balance sheets", "title_zh": "资产负债表", "level": "both",
             "desc_zh": "资产（流动/非流动）与负债；净资产=资产−负债=所有者权益；用途。",
             "key_concepts": ["Current asset", "Non-current asset", "Current liability", "Net assets"],
             "exam_tips": ["恒等式：资产=负债+权益；\"净值\"计算常考。"]},
            {"id": "IG5.5", "title_en": "Ratio analysis", "title_zh": "比率分析", "level": "both",
             "desc_zh": "盈利性（毛利率/净利率/资本回报率）与流动性（流动比率/速动比率）；比率的用途与局限。",
             "key_concepts": ["Gross profit margin", "Net profit margin", "ROCE", "Current ratio", "Acid test"],
             "exam_tips": ["比率题三步：计算→对比（时间/同行）→解释原因。",
                            "局限：历史快照/通胀/会计政策不可比——评估段必写。"]},
            {"id": "IG5.6", "title_en": "Why & how accounts are used", "title_zh": "报表的使用者", "level": "both",
             "desc_zh": "股东/经理人/债权人/员工/政府各自看什么指标、为什么。",
             "key_concepts": ["Stakeholder interests", "Accounts users"],
             "exam_tips": ["按使用者分点作答：银行看流动性、股东看盈利、管理层看效率。"]},
        ]},
        {"id": "ig6", "order": 6, "title_en": "External Influences", "title_zh": "外部影响",
         "short_zh": "外部环境", "topics": [
            {"id": "IG6.1", "title_en": "Economic issues", "title_zh": "经济议题", "level": "both",
             "desc_zh": "经济周期（繁荣/衰退/萧条/复苏）；通胀与通缩；失业；利率与汇率对进出口的影响。",
             "key_concepts": ["Recession", "Inflation", "Unemployment", "Exchange rate", "Interest rate"],
             "exam_tips": ["衰退期的营销/融资/人力资源策略调整是高频综合题。",
                            "本币贬值→出口更有竞争力、进口更贵（企业双向影响）。"]},
            {"id": "IG6.2", "title_en": "Environmental & ethical issues", "title_zh": "环境与伦理议题", "level": "both",
             "desc_zh": "企业活动对环境的影响；伦理决策（成本 vs 责任）；可持续与压力团体。",
             "key_concepts": ["Ethics", "Sustainability", "Pressure group", "External cost"],
             "exam_tips": ["伦理投入的评估：成本↑ vs 品牌与客户忠诚——两面+结论。"]},
            {"id": "IG6.3", "title_en": "Business & international economy", "title_zh": "企业与全球经济", "level": "both",
             "desc_zh": "全球化（市场/生产全球化）；跨国公司(MNC)；国际竞争；多国企业与本国经济。",
             "key_concepts": ["Globalisation", "Multinational", "International competitiveness"],
             "exam_tips": ["MNC 对东道国：就业/技术/税收 vs 本土企业挤压——正负都写。"]},
        ]},
    ],
    "assessment": {
        "note": "CIE 0450（2020+ 考纲；以当季 syllabus 为准）",
        "components": [
            {"id": "p1", "name_zh": "Paper 1 · 短答与数据回应", "time": "1h30m", "marks": 80, "weight": 50,
             "note_zh": "4 题 × 20 分：(a) 定义 2 分 (b) 4 分 (c) 解释 6 分 (d) 论证/建议 8 分（重评估）。"},
            {"id": "p2", "name_zh": "Paper 2 · 案例分析", "time": "1h30m", "marks": 80, "weight": 50,
             "note_zh": "基于案例 insert 的 4 题 × 20 分，结构同 P1，重应用与评估。"},
        ]},
    "glossary": [
        {"term_en": "Added value", "term_zh": "增值", "topic": "IG1.1", "def_zh": "产出价值−购入成本。"},
        {"term_en": "Opportunity cost", "term_zh": "机会成本", "topic": "IG1.1", "def_zh": "放弃的次优选择的价值。"},
        {"term_en": "Division of labour", "term_zh": "分工", "topic": "IG1.1", "def_zh": "将生产拆分为专门工序。"},
        {"term_en": "Limited liability", "term_zh": "有限责任", "topic": "IG1.2", "def_zh": "股东以出资额为限担责。"},
        {"term_en": "Franchise", "term_zh": "特许经营", "topic": "IG1.2", "def_zh": "付费获得品牌与模式授权。"},
        {"term_en": "Joint venture", "term_zh": "合资", "topic": "IG1.2", "def_zh": "两方共资共担的新企业。"},
        {"term_en": "Merger", "term_zh": "合并", "topic": "IG1.3", "def_zh": "两企业合并为一家。"},
        {"term_en": "Takeover", "term_zh": "收购", "topic": "IG1.3", "def_zh": "买入他企业控制权。"},
        {"term_en": "Economies of scale", "term_zh": "规模经济", "topic": "IG1.3", "def_zh": "规模扩大使平均成本下降。"},
        {"term_en": "Stakeholder", "term_zh": "利益相关者", "topic": "IG1.4", "def_zh": "受企业影响或影响企业者。"},
        {"term_en": "Mixed economy", "term_zh": "混合经济", "topic": "IG1.4", "def_zh": "公营+私营并存。"},
        {"term_en": "Privatisation", "term_zh": "私有化", "topic": "IG1.4", "def_zh": "国有资产转私营。"},
        {"term_en": "Job description", "term_zh": "岗位说明", "topic": "IG2.1", "def_zh": "岗位职责与要求的文件。"},
        {"term_en": "Redundancy", "term_zh": "裁员", "topic": "IG2.1", "def_zh": "岗位不再需要的解约。"},
        {"term_en": "Dismissal", "term_zh": "解雇", "topic": "IG2.1", "def_zh": "因过错的解约（≠裁员）。"},
        {"term_en": "Maslow's hierarchy", "term_zh": "马斯洛需求层次", "topic": "IG2.2", "def_zh": "生理→安全→社交→尊重→自我实现。"},
        {"term_en": "Herzberg two-factor", "term_zh": "赫茨伯格双因素", "topic": "IG2.2", "def_zh": "保健因素消除不满，激励因素创造满意。"},
        {"term_en": "Job enrichment", "term_zh": "工作丰富化", "topic": "IG2.2", "def_zh": "增加纵向职责与自主权。"},
        {"term_en": "Span of control", "term_zh": "管理幅度", "topic": "IG2.3", "def_zh": "一名主管直接管辖人数。"},
        {"term_en": "Delegation", "term_zh": "授权", "topic": "IG2.3", "def_zh": "上级把任务与职权下放。"},
        {"term_en": "Trade union", "term_zh": "工会", "topic": "IG2.3", "def_zh": "代表员工集体谈判的组织。"},
        {"term_en": "Niche market", "term_zh": "利基市场", "topic": "IG3.1", "def_zh": "小而专的细分市场。"},
        {"term_en": "Market orientation", "term_zh": "市场导向", "topic": "IG3.1", "def_zh": "以顾客需求驱动决策。"},
        {"term_en": "Primary research", "term_zh": "一手调研", "topic": "IG3.2", "def_zh": "自己收集的新数据。"},
        {"term_en": "Product life cycle", "term_zh": "产品生命周期", "topic": "IG3.3", "def_zh": "开发→导入→成长→成熟→衰退。"},
        {"term_en": "Extension strategy", "term_zh": "延伸策略", "topic": "IG3.3", "def_zh": "延缓成熟期衰退的手段。"},
        {"term_en": "Penetration pricing", "term_zh": "渗透定价", "topic": "IG3.4", "def_zh": "低价入市抢份额。"},
        {"term_en": "Price skimming", "term_zh": "撇脂定价", "topic": "IG3.4", "def_zh": "新品高价逐级降价。"},
        {"term_en": "Above-the-line", "term_zh": "线上（大众）广告", "topic": "IG3.5", "def_zh": "大众媒体付费广告。"},
        {"term_en": "Below-the-line", "term_zh": "线下（定向）促销", "topic": "IG3.5", "def_zh": "可定向衡量的直接沟通。"},
        {"term_en": "Distribution channel", "term_zh": "分销渠道", "topic": "IG3.6", "def_zh": "产品到消费者的路径。"},
        {"term_en": "E-commerce", "term_zh": "电商", "topic": "IG3.6", "def_zh": "线上完成的交易。"},
        {"term_en": "Consumer protection", "term_zh": "消费者保护法", "topic": "IG3.7", "def_zh": "约束误导广告与不安全产品。"},
        {"term_en": "Batch production", "term_zh": "批量生产", "topic": "IG4.1", "def_zh": "分组分批完成订单。"},
        {"term_en": "Lean production", "term_zh": "精益生产", "topic": "IG4.1", "def_zh": "以最少资源消除浪费。"},
        {"term_en": "JIT", "term_zh": "准时制", "topic": "IG4.1", "def_zh": "需要时才进货，近乎零库存。"},
        {"term_en": "Quality assurance", "term_zh": "质量保证", "topic": "IG4.1", "def_zh": "全过程全员预防缺陷。"},
        {"term_en": "Break-even", "term_zh": "盈亏平衡点", "topic": "IG4.2", "def_zh": "FC÷(P−VC)，总收入=总成本。"},
        {"term_en": "Margin of safety", "term_zh": "安全边际", "topic": "IG4.2", "def_zh": "实际产量−BEP 产量。"},
        {"term_en": "Contribution", "term_zh": "贡献", "topic": "IG4.2", "def_zh": "单价−单位可变成本。"},
        {"term_en": "Overdraft", "term_zh": "银行透支", "topic": "IG5.1", "def_zh": "短期灵活负余额融资。"},
        {"term_en": "Trade credit", "term_zh": "商业信用", "topic": "IG5.1", "def_zh": "供应商延期收款。"},
        {"term_en": "Venture capital", "term_zh": "风险投资", "topic": "IG5.1", "def_zh": "股权换高成长资金。"},
        {"term_en": "Micro-finance", "term_zh": "小微金融", "topic": "IG5.1", "def_zh": "面向低收入创业者的微额信贷。"},
        {"term_en": "Cash flow forecast", "term_zh": "现金流预测", "topic": "IG5.2", "def_zh": "未来现金进出的时间表。"},
        {"term_en": "Working capital", "term_zh": "营运资本", "topic": "IG5.2", "def_zh": "流动资产−流动负债。"},
        {"term_en": "Gross profit", "term_zh": "毛利", "topic": "IG5.3", "def_zh": "收入−销售成本。"},
        {"term_en": "Retained profit", "term_zh": "留存利润", "topic": "IG5.3", "def_zh": "未分配再投入的利润。"},
        {"term_en": "Current asset", "term_zh": "流动资产", "topic": "IG5.4", "def_zh": "一年内变现的资产。"},
        {"term_en": "Net assets", "term_zh": "净资产", "topic": "IG5.4", "def_zh": "总资产−总负债=所有者权益。"},
        {"term_en": "ROCE", "term_zh": "资本回报率", "topic": "IG5.5", "def_zh": "营业利润÷资本运用×100%。"},
        {"term_en": "Acid test", "term_zh": "速动比率", "topic": "IG5.5", "def_zh": "(流动资产−存货)÷流动负债。"},
        {"term_en": "Recession", "term_zh": "衰退", "topic": "IG6.1", "def_zh": "GDP 连续两季下滑。"},
        {"term_en": "Inflation", "term_zh": "通胀", "topic": "IG6.1", "def_zh": "物价持续上涨。"},
        {"term_en": "Exchange rate", "term_zh": "汇率", "topic": "IG6.1", "def_zh": "一币兑他币的价格。"},
        {"term_en": "Sustainability", "term_zh": "可持续性", "topic": "IG6.2", "def_zh": "兼顾经济/社会/环境的经营。"},
        {"term_en": "Pressure group", "term_zh": "压力团体", "topic": "IG6.2", "def_zh": "向企业施压的利益组织。"},
        {"term_en": "Globalisation", "term_zh": "全球化", "topic": "IG6.3", "def_zh": "市场与生产的跨国整合。"},
        {"term_en": "Multinational", "term_zh": "跨国公司", "topic": "IG6.3", "def_zh": "在多国经营的巨型企业。"},
    ],
    "quiz": [
        {"q": "增值 (added value) 的计算是？", "opts": ["销售收入−购入成本", "净利润−成本", "资产−负债", "产量×价格"], "a": 0, "why": "产出价值减购入投入成本。"},
        {"q": "与独资企业相比，有限公司的主要优势是？", "opts": ["有限责任", "设立更容易", "税率更低", "决策更快"], "a": 0, "why": "股东以出资额为限担责。"},
        {"q": "特许经营对受许人的主要好处是？", "opts": ["成熟品牌降低风险", "完全自由经营", "无需支付费用", "利润全留"], "a": 0, "why": "买的是被验证的模式。"},
        {"q": "以下哪种属于纵向整合？", "opts": ["收购原料供应商", "收购同业竞争者", "收购异业公司", "内部扩张"], "a": 0, "why": "纵向=供应链上下游。"},
        {"q": "规模不经济的主要原因是？", "opts": ["管理与沟通效率下降", "采购量太大", "员工太少", "市场太大"], "a": 0, "why": "组织过大导致协调成本上升。"},
        {"q": "裁员 (redundancy) 与解雇 (dismissal) 的区别是？", "opts": ["裁员因岗位消失", "解雇更体面", "裁员给钱更多", "没有区别"], "a": 0, "why": "dismissal 因员工过错。"},
        {"q": "Herzberg 理论中，工资属于？", "opts": ["保健因素", "激励因素", "成就需要", "自我实现"], "a": 0, "why": "保健因素只消除不满。"},
        {"q": "管理幅度变宽意味着？", "opts": ["每个主管管辖更多下属", "层级更多", "沟通更慢", "集权更强"], "a": 0, "why": "幅度=直接下属数。"},
        {"q": "以下哪个是非金钱激励？", "opts": ["工作丰富化", "计件工资", "奖金", "利润分享"], "a": 0, "why": "丰富化属职责层面的激励。"},
        {"q": "利基市场 (niche market) 的特征是？", "opts": ["小众专精、竞争较少", "面向所有人", "只在线销售", "必须低价"], "a": 0, "why": "细分定位换取专业溢价。"},
        {"q": "一手调研的主要优点是？", "opts": ["数据贴合具体问题", "成本最低", "速度最快", "永远可靠"], "a": 0, "why": "为自己问题定制。"},
        {"q": "产品生命周期\"成熟期\"应该？", "opts": ["用延伸策略延缓衰退", "加大研发投入", "退出市场", "提高单价"], "a": 0, "why": "新包装/新市场/降价延长成熟。"},
        {"q": "撇脂定价适合？", "opts": ["创新品早期采用者", "日用品", "价格敏感市场", "清库存"], "a": 0, "why": "创新+低弹性撑得起高价。"},
        {"q": "线上广告 (above-the-line) 的特点是？", "opts": ["大众媒体广覆盖", "一对一精准", "成本最低", "无法衡量"], "a": 0, "why": "ATL 走大众媒体。"},
        {"q": "JIT 的主要风险是？", "opts": ["供应链中断", "库存过多", "质量下降", "租金上升"], "a": 0, "why": "零库存依赖供应稳定。"},
        {"q": "盈亏平衡产量公式是？", "opts": ["固定成本÷(单价−单位可变成本)", "固定成本×可变成本", "总收入−总成本", "(单价−可变成本)÷固定成本"], "a": 0, "why": "贡献覆盖固定成本之点。"},
        {"q": "安全边际的含义是？", "opts": ["实际销量超过BEP的部分", "利润率", "库存量", "市场份额"], "a": 0, "why": "距离亏损的缓冲。"},
        {"q": "透支 (overdraft) 适合？", "opts": ["短期小额资金缺口", "购买厂房", "长期研发", "并购融资"], "a": 0, "why": "期限匹配原则。"},
        {"q": "\"盈利的企业也可能现金枯竭\"是因为？", "opts": ["赊销占款与存货压资", "利润是假的", "会计出错", "税太重"], "a": 0, "why": "利润≠现金。"},
        {"q": "速动比率剔除存货是因为？", "opts": ["存货变现慢且不确定", "存货无价值", "准则要求", "存货是负债"], "a": 0, "why": "流动性最差的项目。"},
        {"q": "ROCE 衡量？", "opts": ["长期资本的回报效率", "流动性", "库存周转", "股价"], "a": 0, "why": "营业利润÷资本运用。"},
        {"q": "本币贬值对出口企业的影响是？", "opts": ["出口更有价格竞争力", "出口更贵", "无影响", "进口成本下降"], "a": 0, "why": "外币计价更便宜。"},
        {"q": "衰退期企业最可能？", "opts": ["削减非必要开支与库存", "大量招聘", "提高广告预算", "加价"], "a": 0, "why": "保现金流过冬。"},
        {"q": "跨国公司对东道国的潜在负面是？", "opts": ["挤压本土企业", "带来就业", "转移技术", "增加税收"], "a": 0, "why": "规模与资金优势碾压本地对手。"},
        {"q": "伦理与环保投入的商业回报主要是？", "opts": ["品牌声誉与客户忠诚", "立即降价", "减少税收", "提高工资"], "a": 0, "why": "长期无形资产积累。"},
    ],
}

# ---------------------------------------------------------------------------
# IA/EE-equivalent writing guide + teaching resources for 0450
# ---------------------------------------------------------------------------

IAEE_IG = {
    "title": "IGCSE 商科 · Paper 1/2 大题写作指南（0450 无 IA/EE）",
    "sections": [
        {"h": "题型结构与分值（2020+ 考纲）",
         "items": [
            "Paper 1 与 Paper 2 均为 1h30m、80 分、各占 50%：4 大题 × 20 分，每题结构相同。",
            "标准小题阶梯：(a) 定义/识记 2 分 → (b) 简答/识记应用 4 分 → (c) 解释分析 6 分 → (d) 论证/建议 8 分（重评估）。",
            "Paper 2 基于案例 insert（一份完整企业背景材料）出题——答案必须引用案例中的具体企业名、数据与情境，否则拿不到应用分。",
            "时间管理：80 分 × 约 1.1 分钟/分 → 每大题约 20 分钟，(d) 题留 7-8 分钟。",
         ]},
        {"h": "四类技能与对应小题（CIE 评分的 K/A/An/E）",
         "items": [
            "知识 Knowledge（(a) 2 分）：准确定义——用考纲术语，配一个小例子最稳。",
            "应用 Application（(b) 4 分 + 全卷）：引用案例企业/数据/国家情境；写答案时自问\"这句话放到别的企业还成立吗？\"成立=没应用。",
            "分析 Analysis（(c) 6 分）：因果链\"因为…导致…进而…\"；每个论点用理论工具（BEP、生命周期、激励理论）撑开。",
            "评估 Evaluation（(d) 8 分）：两面论证 + 明确建议 + 理由 + 风险/条件（\"取决于弹性/现金流/竞争反应\"）。",
         ]},
        {"h": "(d) 题 8 分模板",
         "items": [
            "五段式：① 立场句（I recommend X because…）② 支持论点 1+因果 ③ 支持论点 2+数据 ④ 反方观点+为何不采 ⑤ 实施条件与风险（短期 vs 长期）。",
            "必须有明确决定：\"两者结合\"\"视情况\"不给高分——选一个并论证取舍。",
         ]},
        {"h": "高频失分（考官报告 er 常年指出）",
         "items": [
            "(a) 定义用自己的话写丢术语；(b) 只抄材料不加解释；(c) 罗列要点无因果链；(d) 无结论或结论与前文脱节。",
            "Paper 2 通篇不提案例企业名（应用 0 分）；计算题不写公式/单位；画图（BEP）不标轴与线名。",
         ]},
    ],
}

RESOURCES_IG = {
    "groups": [
        {"h": "本地真题库（2002–2025 全 239 份 + 评分方案 + 考官报告）",
         "items": [
            "结构：<年份>/<考季>/0450_<s|w|m><yy>_<qp|ms|er|gt|in>_<variant>.pdf（qp=真题 · ms=评分 · er=考官报告 · gt=分数线 · in=案例插入卷）",
            "考季：May/June（s）· Oct/Nov（w）· March（m）；variant 1x=Paper 1，2x=Paper 2",
            "建议刷法：近 5 年全刷；更早年份按主题挑（结合本站\"真题库\"页的考点频次图）",
            "每套题做完必须对照 ms 的 level 描述自评，再看 er 的整体失分统计",
         ],
         "link": None},
        {"h": "推荐教材",
         "items": [
            "Cambridge IGCSE & O Level Business Studies (Borrington & Jaramillo, Hodder)：按 6 大节与考纲一一对应",
            "Cambridge IGCSE Business Studies 5th ed (Borrington & Stimpson, CUP)：经典版本，练习丰富",
            "与 AL 商科（9609）高度衔接：0450 学完可直接衔接 AS 内容",
         ]},
    ],
}

