# -*- coding: utf-8 -*-
"""策展型「常见考题」：用于本地没有真题库的科目（AL 经济 9708 / IB 商管 / AL 商科 9609 / 竞赛）。
题型与分值按各科官方卷型整理；答案按官方评分逻辑（给分点 + 评价线 + 等级描述）撰写。
每条：{topic, q, marks, tag 卷型, aos 能力维度, answer 答题要点}
"""

EXAMQ_CURATED = {
    # ------------------------------------------------------------------ AL 经济（CIE 9708）
    "al-econ": {
        "note": "按 CIE 9708 卷型整理的典型考题（P2 数据回应 a/b/c 递进 2/8/12，P3/P4 大 essay 12/20 分）。"
                "a 定义题答『精确公式/定义+一个例子』；b 分析题答『链条 3 步+图』；c 论述题必须有双边+结论。",
        "items": [
            {"topic": "AE1.1", "q": "Define the term 'opportunity cost'. [2]", "marks": 2, "tag": "P2(a) 定义",
             "aos": "AO1", "answer": "给分点：做出选择时被放弃的次优替代方案的价值（1 分）＋任何准确表述或例子（1 分）。常见丢分：把『所有被放弃选项之和』当机会成本；只写中文式意译不点『次优 next best』。"},
            {"topic": "AE2.2", "q": "Explain two determinants of the price elasticity of demand for a product such as coffee. [8]", "marks": 8, "tag": "P2(b) 分析",
             "aos": "AO1+AO3", "answer": "每因素 4 分：识别（1）+解释如何影响弹性（2）+联系咖啡语境（1）。常用因素：替代品数量与接近度、支出占收入比重、必需程度、时间长短。高分要求两因素各自成段并落到咖啡，不要写成『PED 是什么』的定义堆砌。"},
            {"topic": "AE2.4", "q": "Discuss whether a government should always use a subsidy rather than a tax to correct market failure. [12]", "marks": 12, "tag": "P2(c)/P4 论述",
             "aos": "AO3+AO4", "answer": "框架：先分外部性类型（负外部性用税、正外部性用补贴——『always』不成立的一半证据）；再评补贴的局限（财政负担、测度 MEC/MEB 困难、可能被企业吸收而非降价）；结论必须直接回答『是否 always』并给出条件式判断（如『取决于外部性方向与政府财政能力』）。画 MSC/MSB 图至少一张。"},
            {"topic": "AE3.1", "q": "Analyse how a fall in interest rates might affect aggregate demand. [8]", "marks": 8, "tag": "P2(b) 分析",
             "aos": "AO2+AO3", "answer": "传导链：借贷成本↓→C 与 I ↑→AD=C+I+G+X−M 右移（2 分链+图 2 分）；再补汇率渠道（利率↓→资本流出→本币贬值→净出口↑）与财富渠道任一。AD 图标注 AD1→AD2、均衡 P/Y 变化。丢分点：只说『刺激经济』没有传导机制。"},
            {"topic": "AE4.2", "q": "Evaluate the view that the Phillips curve trade-off no longer exists. [20]", "marks": 20, "tag": "P4 大论述",
             "aos": "AO3+AO4", "answer": "正方：预期附加的长期菲利普斯曲线垂直（自然率假说）；滞胀年代曲线外移；平坦化证据（低失业低通胀并存）。反方：短期取舍仍存在；央行行为本身（通胀目标制）可能正是压平曲线的原因。结论：区分短期（存在但 weaker）与长期（取决于预期形成方式）。要求两张图（短期曲线移动+长期垂直）与真实例（如 2021-23 通胀回归）。"},
            {"topic": "AE2.1", "q": "Explain, using a diagram, the difference between a movement along and a shift of the demand curve. [8]", "marks": 8, "tag": "P2(b)",
             "aos": "AO1+AO2", "answer": "沿线移动=自身价格变动引起（图上 D 上 A→B 点，1+2 分）；整线移动=非价格因素（收入/相关品/偏好/预期）引起（D→D1 平移，1+2 分）；各配一个例子再加 2 分。两图分开画，标注轴与曲线。"},
            {"topic": "AE3.3", "q": "Discuss whether an increase in the rate of inflation always benefits borrowers at the expense of savers. [12]", "marks": 12, "tag": "论述",
             "aos": "AO3+AO4", "answer": "支持面：未预期通胀侵蚀实际利率→固定利率借款人实际负担减轻。反对面：若利率已含通胀预期（费雪方程）则无再分配；浮动利率贷款随通胀上调；政府指数化债券保护储户。结论：『always』不成立，取决于通胀是否被预期、利率调整速度与债务合同类型。"},
            {"topic": "AE4.1", "q": "Explain two causes of structural unemployment. [8]", "marks": 8, "tag": "P2(b)",
             "aos": "AO1+AO3", "answer": "每因 4 分（识别+机制+例子）：技能不匹配（技术变革淘汰旧岗位）、行业衰退（需求长期转移）、地理流动性障碍、最低工资高于均衡（如适用）。高分需说明『为什么市场自身无法快速调整』（再培训需要时间）。"},
            {"topic": "AE2.3", "q": "Analyse how a monopolist determines its profit-maximising price and output. [8]", "marks": 8, "tag": "P2(b)",
             "aos": "AO2+AO3", "answer": "MR=MC 定产量 Qm（2）+需求曲线定价格 Pm（2）+图完整标注（2）+说明 P>MC 与超正常利润块（2）。丢分点：把 P=MC（完全竞争规则）错用到垄断。"},
            {"topic": "AE4.4", "q": "Discuss whether joining a monetary union is always beneficial for an economy. [12]", "marks": 12, "tag": "论述",
             "aos": "AO3+AO4", "answer": "收益：消除汇率风险与交易成本、价格透明、促进贸易投资。代价：丧失独立货币政策（利率不能再按本国周期调整）、失去汇率贬值这一调整工具、最优货币区条件（要素流动、经济周期同步）未必满足（欧元区危机例）。结论：取决于贸易一体化程度与经济周期同步性。"},
            {"topic": "AE1.2", "q": "Explain how the price mechanism allocates resources in a free market. [8]", "marks": 8, "tag": "P2(b)",
             "aos": "AO1+AO2", "answer": "三大功能各 2-3 分：信号（价格变动传递稀缺信息）、激励（价格影响生产与消费动机）、配给（价高者得）。配一张超额需求→价格上升→新均衡的图。"},
            {"topic": "AE4.3", "q": "Evaluate the view that free trade always benefits developing countries. [20]", "marks": 20, "tag": "P4 大论述",
             "aos": "AO3+AO4", "answer": "支持：比较优势分工、市场规模、技术溢出、竞争促效率。反对：初级产品贸易条件长期恶化（Prebisch-Singer）、幼稚产业被扼杀、依赖单一出口的脆弱性、发达国家补贴扭曲农产品市场。结论：有条件受益——取决于出口结构多元化与制度质量；可提及 WTO 特殊与差别待遇。"},
        ],
    },
    # ------------------------------------------------------------------ IB 商业管理（BM 2022+）
    "ib-bus": {
        "note": "按 BM 2022+ 卷型整理：P1 短答 (a)2/(b)4，P1/P2 论述 10 分，HL P3 决策线 20 分。"
                "SAQ 答题公式：定义(1)+工具/理论应用(2-3)+案例引用(1)；10 分题=两个论点各配『案例证据+影响分析』；20 分题必须有明确结论+至少两个维度的权衡。",
        "items": [
            {"topic": "BB1.4", "q": "Explain the difference between internal and external stakeholders, using X organization. [4]", "marks": 4, "tag": "P1(b) 短答",
             "aos": "AO1+AO2", "answer": "定义内部（员工/股东/管理层，1 分）与外部（顾客/供应商/政府/社区，1 分）＋各配 X 组织具体成员（2 分）。丢分：只给定义不联系案例（AO2 为零）。"},
            {"topic": "BB2.2", "q": "Discuss whether financial rewards are the best way to motivate employees. [10]", "marks": 10, "tag": "P1/P2 论述",
             "aos": "AO2+AO3", "answer": "正方：Taylor 科学管理、计件/绩效奖金直接绑定产出、满足 Maslow 生理与安全层。反方：Herzberg——钱是保健因素，涨薪止不满不创造激励；非财务（授权/工作丰富化/认可）更持久；成本刚性。结论需条件化：低技能标准化岗位 vs 知识型员工的适用性不同，最好结合案例行业回答。"},
            {"topic": "BB1.6", "q": "Using the Ansoff matrix, analyse X's option of entering a new market with its existing products. [10]", "marks": 10, "tag": "论述",
             "aos": "AO2+AO3", "answer": "先定位：现有产品+新市场=市场开发（象限与风险级，2 分）；收益论点（收入多元化、规模摊薄、品牌延伸，各配案例证据）；风险论点（新市场进入壁垒、文化/法规不熟悉、渠道重建成本）。10 分题必须每个论点都引案例数据/事实。"},
            {"topic": "BB3.4", "q": "Calculate and interpret X's current ratio for 2023. [4]", "marks": 4, "tag": "P1(a/b) 计算",
             "aos": "AO2+AO3", "answer": "公式 Current ratio=流动资产÷流动负债（1 分）＋正确代入数据得数（1 分）＋解读：>1 短期偿付有保障，与上一年或行业基准比较（2 分）。别忘单位与保留两位小数。"},
            {"topic": "BB5.4", "q": "Explain one advantage and one disadvantage to X of using break-even analysis. [4]", "marks": 4, "tag": "P1(b)",
             "aos": "AO2", "answer": "优势：确定最低销量目标/评估抗风险能力（1+联系 X 1 分）；劣势：假设线性、单一产品、产量=销量的理想化（1+联系 X 1 分）。每点都要落到 X 的具体情境。"},
            {"topic": "BB4.4", "q": "Discuss whether X should use penetration pricing when entering Country Y. [10]", "marks": 10, "tag": "论述",
             "aos": "AO2+AO3", "answer": "支持：快速抢份额、适合弹性大的大众市场、形成规模经济门槛。反对：低价锚定品牌形象难提价、引发价格战、Y 国消费者可能把低价等同低质（结合 Y 国收入水平分析）。结论：取决于 Y 国竞争格局与 X 的成本优势，给出替代方案（skimming/竞争定价）比较更佳。"},
            {"topic": "BB2.3", "q": "To what extent is X's leadership style appropriate for its planned expansion? [20]", "marks": 20, "tag": "P2/P3 大论述",
             "aos": "AO3+AO4", "answer": "结构：识别现任风格（专制/民主/放任，引案例行为证据）→ 扩张需要的领导特质（授权、跨市场协调、变革推动）→ 匹配度分析两维度（优势情境/失灵情境）→ 结论明确『to what extent』（完全/部分/不适当+条件）。20 分必须含至少两个管理理论工具（情境领导、Tannenbaum-Schmidt 谱系）与跨单元连接（激励、文化）。"},
            {"topic": "BB3.6", "q": "Analyse two strategies X could use to improve its cash flow. [6]", "marks": 6, "tag": "P1(b)/P2",
             "aos": "AO2+AO3", "answer": "每策略 3 分：命名+机制+对 X 的适用性。可选：缩短应收账期（提供折扣）、延长应付账期（谈判）、削减存货（JIT）、透支额度、售后预付。指出权衡（折扣压毛利、赊账伤供应商关系）可上探 AO3。"},
            {"topic": "BB5.2", "q": "Evaluate X's decision to relocate production to a lower-cost country. [10]", "marks": 10, "tag": "论述",
             "aos": "AO2+AO3", "answer": "收益：单位成本↓、贴近新兴市场、税收优惠。风险：供应链长度与脆弱性、质量控制、品牌形象（本地就业流失）、隐性成本（沟通/文化/合规）。结论需权衡短长期并联系案例财务与运营数据。"},
            {"topic": "BB1.3", "q": "Explain the difference between X's mission statement and its strategic objectives. [4]", "marks": 4, "tag": "P1(b)",
             "aos": "AO1+AO2", "answer": "使命=长期存在的目的与身份（1），战略目标=可衡量可操作的具体方向 SMART（1）；各引 X 原文/事实（2）。"},
            {"topic": "BB4.2", "q": "Discuss whether the marketing mix (4Ps) of X is consistent with its target market. [10]", "marks": 10, "tag": "论述",
             "aos": "AO2+AO3", "answer": "逐 P 对照目标市场特征：产品匹配度、价格与购买力、渠道可达性、促销触达习惯。指出不一致处（如高端产品配地摊渠道）是高分关键。结论：一致性判断+调整建议。"},
            {"topic": "BB2.5", "q": "Explain two roles of trade unions in X's industry. [4]", "marks": 4, "tag": "P1(b)",
             "aos": "AO1+AO2", "answer": "集体谈判工资与条件（1+案例 1）、保护成员免受不公正解雇/代表申诉（1+案例 1）。可提工业行动作为杠杆。"},
        ],
    },
    # ------------------------------------------------------------------ AL 商科（CIE 9609，2026+ 卷型）
    "al-bus": {
        "note": "按 9609 2026-2028 卷型整理：P1 Section A 5 分短答 / Section B 20 分 essay；P2 数据回应 30 分（6 小问，末问评价）；"
                "P3 案例 8/16/12；P4 战略 essay 20 分×2。5 分题=定义(2)+解释/例(3)；essay 用 AO 四层：知识→应用→分析（因果链）→评价（判断+条件）。",
        "items": [
            {"topic": "AB1.1", "q": "Define 'opportunity cost'. [5]", "marks": 5, "tag": "P1 SecA 短答",
             "aos": "AO1", "answer": "定义：选择时被放弃的次优选项价值（2 分）；解释商业语境：资金/时间投向 A 即放弃 B 的回报，配一个商业决策例子（3 分）。5 分短答必须写足三层：术语精确+展开+例子。"},
            {"topic": "AB6.1", "q": "Evaluate whether X should pursue market development as a growth strategy. [20]", "marks": 20, "tag": "P1 SecB / P4 essay",
             "aos": "AO1-AO4", "answer": "Ansoff 定位（市场开发=新产品市场组合中的老产品新市场，中高风险）→ 收益分析（收入来源多元化、产能利用、品牌溢价）配 X 案例数据 → 风险分析（新市场进入壁垒、法规、文化适配、渠道成本、分散管理注意力的机会成本）→ 评价：比较备选（渗透/产品开发）后下明确判断，并给成立条件（如『若 X 具备可复制的渠道能力则值得』）。"},
            {"topic": "AB3.1", "q": "Analyse how X could use market segmentation to increase sales. [8]", "marks": 8, "tag": "P2 数据回应",
             "aos": "AO2+AO3", "answer": "细分维度选择（地理/人口/心理/行为）+ 每维对 X 的具体切分 + 针对性组合调整（产品版本/定价/渠道）如何转化为销量。因果链必须完整：细分→更精准匹配需求→支付意愿提升→销量。"},
            {"topic": "AB4.1", "q": "Discuss whether X should outsource its transport operations. [16]", "marks": 16, "tag": "P3 案例题",
             "aos": "AO2-AO4", "answer": "三层：成本对比（固定车队成本 vs 变动外包费，引用案例数字）、能力对比（专业物流公司的网络与时效 vs 控制力与服务质量）、战略对比（聚焦核心能力 vs 依赖第三方风险）。16 分题评价部分要给决策建议+风险对冲（如双供应商）。"},
            {"topic": "AB5.2", "q": "Analyse two limitations of ratio analysis when assessing X's performance. [8]", "marks": 8, "tag": "P2/P3",
             "aos": "AO3", "answer": "每限 4 分：历史成本数据滞后、会计政策差异扭曲可比、不含非财务维度（品牌/人才）、窗口粉饰（year-end window dressing）。各配 X 场景说明为何影响判断。"},
            {"topic": "AB2.1", "q": "Evaluate whether financial methods of motivation are always the most effective for X's workforce. [12]", "marks": 12, "tag": "P3 案例",
             "aos": "AO2-AO4", "answer": "财务法（计件/奖金/利润分享）适用低收入标准化岗位；非财务（授权/JR 晋升）适用知识型员工（Herzberg 框架）。结合 X 的员工结构数据判断，结论给出『分群激励』的混合方案更佳。"},
            {"topic": "AB1.3", "q": "Analyse how a rise in interest rates might affect X. [8]", "marks": 8, "tag": "P2",
             "aos": "AO2+AO3", "answer": "双链条：融资成本↑（浮动利率债务利息↑→利润↓）+ 需求端（客户信贷消费↓→X 销量↓）。若 X 是高 gearing 或耐用品行业影响更大——用案例数据定性。"},
            {"topic": "AB6.2", "q": "Discuss how X's managers could overcome resistance to the introduction of new technology. [12]", "marks": 12, "tag": "P3",
             "aos": "AO2-AO4", "answer": "阻力来源（恐惧失业/技能不足/习惯）对应策略：沟通愿景（Lewin 解冻）、培训与再就业保障、参与式试点、激励绑定、再冻结（纳入考核）。评价：策略组合比单一强推有效，注意时间与成本约束。"},
            {"topic": "AB5.1", "q": "Explain two factors X should consider when choosing between a bank loan and venture capital. [5]", "marks": 5, "tag": "P1 SecA",
             "aos": "AO1+AO2", "answer": "每因 2-3 分：控制权稀释（VC 要股权/董事会席位）、偿债压力（贷款固定利息 vs VC 无固定偿还）、规模与速度、附带资源（VC 导师/网络）。"},
            {"topic": "AB2.2", "q": "Analyse two advantages of a wide span of control for X. [8]", "marks": 8, "tag": "P2/P3",
             "aos": "AO3", "answer": "每优势 4 分：管理成本降低（更少中层薪酬）、沟通链短决策快、下属自主性提升（联动激励）。配 X 的规模/任务标准化程度语境；提一句适用前提（下属成熟度）可上评价。"},
            {"topic": "AB3.2", "q": "Evaluate whether X should use price discrimination between its two market segments. [12]", "marks": 12, "tag": "P3",
             "aos": "AO2-AO4", "answer": "条件：市场可分、弹性不同、无转售。收益：各段按弹性定价最大化收入（弹性段低价放量、低弹性段高价收割）。风险：品牌形象、套利、法律（某些司法辖区）。结论：结合 X 两段的弹性证据与分隔可行性判断。"},
            {"topic": "AB4.2", "q": "Discuss whether lean production is always appropriate for a business such as X. [16]", "marks": 16, "tag": "P3/P4",
             "aos": "AO2-AO4", "answer": "收益（库存成本、浪费消除、周转）vs 风险（供应链中断、需求波动下的缺货、员工压力）+ X 的行业特征（需求稳定？供应商半径？产品生命周期？）。『always』类题结论必须条件化：稳定需求+本地供应商=适合；波动需求+长链条=需混合（JIT+安全库存）。"},
        ],
    },
    # ------------------------------------------------------------------ 竞赛（康莱德 & BPA 评委问答）
    "comp": {
        "note": "竞赛没有标准化笔试——「考题」即评委问答与评审追问。以下为康莱德/BPA 现场高频问题与满分应答框架。"
                "答题公式：直接回答（一句话结论）→ 证据（数据/访谈/测试）→ 承认局限 → 给出下一步验证计划。",
        "items": [
            {"topic": "CP1.3", "q": "评委问：你的问题是真的吗？有多少人愿意付钱？", "marks": 0, "tag": "康莱德 Q&A",
             "aos": "Problem-Solution Fit", "answer": "用行为证据而非意愿声明：访谈中 N 人上月已为该问题花钱/花时间（给出数字）；假门测试点击率；竞品现有销量。忌答『很多人都有这个问题』而无数据。"},
            {"topic": "CP1.3", "q": "评委问：大公司抄你怎么办？", "marks": 0, "tag": "康莱德 Q&A",
             "aos": "Unfair advantage", "answer": "三层回答：门槛（独家数据/社区网络效应/专利/独家合作）→ 为什么大厂看不上或不值得抄（市场初期小、模式冲突）→ 时间窗口（先发+迭代速度）。承认『没有永久壁垒，但有 18 个月窗口』比硬撑更可信。"},
            {"topic": "CP1.5", "q": "评委问：你的市场到底有多大？SOM 怎么算的？", "marks": 0, "tag": "康莱德/BPA",
             "aos": "TAM/SAM/SOM", "answer": "自下而上：可触达学校/社区数 × 渗透率 × 客单价 × 频次，每年给来源与假设；与竞品已占份额交叉验证。忌直接引用行业报告总盘当 SOM。"},
            {"topic": "CP1.5", "q": "评委问：你的财务预测凭什么可信？", "marks": 0, "tag": "BPA 财务线",
             "aos": "Budget reasonableness", "answer": "三件套：单位经济（LTV/CAC、毛利结构）先跑通 → 增长假设来自试点/类比公司轨迹 → 给出悲观/中性/乐观三情景。主动指出最脆弱的假设与监测指标。"},
            {"topic": "CP1.5", "q": "评委问：你要烧多少钱？钱花在哪？", "marks": 0, "tag": "康莱德 Q&A",
             "aos": "Burn rate / Runway", "answer": "月度 burn × runway 月数 + 资金用途饼图（研发/获客/运营占比）+ 里程碑挂钩（这笔钱恰好够验证 X 假设、达到 Y 指标，从而打开下一轮融资）。"},
            {"topic": "CP2.2", "q": "BPA 案例题：给出 90 天行动方案", "marks": 0, "tag": "BPA Case",
             "aos": "Case diagnosis", "answer": "结构化三板斧：诊断（用 SWOT/财务比率定位最致命问题，引用案例数据）→ 三个优先行动（每条：动作-负责人-可测目标-时间点）→ 风险与备选。90 天要分 0-30/31-60/61-90 节奏。"},
            {"topic": "CP2.2", "q": "BPA 案例题：该公司应该涨价还是降价？", "marks": 0, "tag": "BPA Case",
             "aos": "Elasticity / Pricing", "answer": "先判断弹性证据（客户集中度、替代品、支出占比）→ 算两个方向的贡献影响（量×价）→ 结合定位与竞争反应给结论。永远不要只答一边。"},
            {"topic": "CP3.2", "q": "评委问：你们团队怎么分工的？为什么这样分？", "marks": 0, "tag": "通用 Q&A",
             "aos": "Team", "answer": "按交付物倒推分工（调研/产品/财务/路演），每人的专长与负责模块对应，给出协作机制（每周例会+共享看板）。展示互补性而非平均分配。"},
            {"topic": "CP3.1", "q": "评委问：你的方案对环境/社会有什么影响？", "marks": 0, "tag": "康莱德",
             "aos": "SDG / ESG", "answer": "对齐具体 SDG 编号 + 量化影响（减排吨数/受益人数/节约资源量）+ 商业可持续性说明（不靠情怀赚钱）。避免空泛贴标签。"},
            {"topic": "CP1.1", "q": "评委问：如果这个想法失败了，你们的 Plan B 是什么？", "marks": 0, "tag": "康莱德 Q&A",
             "aos": "Pivot", "answer": "展示 pivot 逻辑而非慌乱：预先识别的关键假设 + 失败信号（指标阈值）+ 相邻转型方向（同一能力的其他应用场景）。体现『科学式迭代』思维。"},
            {"topic": "CP1.2", "q": "评委问：用一句话说清你们是做什么的。", "marks": 0, "tag": "Elevator pitch",
             "aos": "UVP", "answer": "模板：为（目标客户）解决（具体问题）的（产品形态），与（现有方案）相比（量化差异）。全程控制在 20 秒内，数字要具体。"},
            {"topic": "CP2.3", "q": "BPA 客观题：概念辨析类（如 4P 归属、比率计算）", "marks": 0, "tag": "BPA Objective",
             "aos": "Objective test scope", "answer": "以官方考纲定义为准（本站术语表已对齐）；计算题先写公式再代入；易混对：marketing vs selling concept、QA vs QC、cash vs profit、mark-up vs margin。"},
        ],
    },
}
