"""Curated IB Economics content: syllabus tree, glossary, assessment, command terms.

This is the authoritative "knowledge" layer used to build the knowledge base.
Syllabus follows the IB Economics guide (first assessment 2022 / 2024 update),
i.e. the latest exam specification. Levels: "both" = SL & HL, "hl" = HL only.
"""

# ---------------------------------------------------------------------------
# Syllabus: units -> topics
# ---------------------------------------------------------------------------

SYLLABUS = [
    {
        "id": "intro",
        "order": 1,
        "title_en": "Introduction to Economics",
        "title_zh": "经济学导论",
        "short_en": "Introduction",
        "short_zh": "导论",
        "desc_en": "Introduces the fundamental economic problem of scarcity, choice, and opportunity cost, and how economists approach the world as a social science.",
        "desc_zh": "介绍稀缺性、选择与机会成本这一基本经济问题，以及经济学家如何将经济学作为一门社会科学来研究世界。",
        "topics": [
            {"id": "1.1", "title_en": "What is economics?", "title_zh": "什么是经济学？", "level": "both",
             "desc_en": "Economics as a social science; scarcity, choice, opportunity cost, the factors of production, and the basic economic questions.",
             "desc_zh": "经济学作为社会科学；稀缺性、选择、机会成本、生产要素与基本经济问题。",
             "key_concepts": ["Scarcity", "Opportunity cost", "Factors of production", "Ceteris paribus", "Economic goods", "Free goods"]},
            {"id": "1.2", "title_en": "How do economists approach the world?", "title_zh": "经济学家如何研究世界？", "level": "both",
             "desc_en": "Economic methodology — models, positive vs normative statements, and the role of assumptions.",
             "desc_zh": "经济学方法论——模型、实证与规范陈述，以及假设的作用。",
             "key_concepts": ["Positive economics", "Normative economics", "Economic model"]},
        ],
    },
    {
        "id": "micro",
        "order": 2,
        "title_en": "Microeconomics",
        "title_zh": "微观经济学",
        "short_en": "Micro",
        "short_zh": "微观",
        "desc_en": "The behaviour of consumers and firms, markets and price determination, and the causes and consequences of market failure and government intervention.",
        "desc_zh": "消费者与企业的行为、市场与价格决定，以及市场失灵的成因与后果及政府干预。",
        "topics": [
            {"id": "2.1", "title_en": "Demand", "title_zh": "需求", "level": "both",
             "desc_en": "The law of demand, the demand curve, and the non-price determinants of demand.",
             "desc_zh": "需求定律、需求曲线以及需求的非价格决定因素。",
             "key_concepts": ["Demand", "Law of demand"]},
            {"id": "2.2", "title_en": "Supply", "title_zh": "供给", "level": "both",
             "desc_en": "The law of supply, the supply curve, and the non-price determinants of supply.",
             "desc_zh": "供给定律、供给曲线以及供给的非价格决定因素。",
             "key_concepts": ["Supply", "Law of supply"]},
            {"id": "2.3", "title_en": "Competitive market equilibrium", "title_zh": "竞争性市场均衡", "level": "both",
             "desc_en": "Market equilibrium, excess demand and supply, the price mechanism, and consumer/producer surplus.",
             "desc_zh": "市场均衡、超额需求与供给、价格机制以及消费者/生产者剩余。",
             "key_concepts": ["Market equilibrium", "Price mechanism", "Consumer surplus", "Producer surplus", "Allocative efficiency"]},
            {"id": "2.4", "title_en": "Critique of the maximizing behaviour of consumers and producers", "title_zh": "对消费者与生产者最大化行为的批判", "level": "both",
             "desc_en": "Rationality, behavioural economics, and limitations of the maximizing assumption (nudges, biases, alternative business objectives).",
             "desc_zh": "理性假设、行为经济学以及最大化假设的局限（助推、认知偏差、企业的替代目标）。",
             "key_concepts": ["Behavioural economics", "Rational choice"]},
            {"id": "2.5", "title_en": "Elasticity of demand", "title_zh": "需求弹性", "level": "both",
             "desc_en": "Price elasticity of demand (PED), income elasticity (YED), and cross-price elasticity (XED).",
             "desc_zh": "需求价格弹性（PED）、需求收入弹性（YED）与需求交叉弹性（XED）。",
             "key_concepts": ["Price elasticity of demand", "Income elasticity of demand", "Cross-price elasticity of demand"]},
            {"id": "2.6", "title_en": "Elasticity of supply", "title_zh": "供给弹性", "level": "both",
             "desc_en": "Price elasticity of supply (PES) and its determinants.",
             "desc_zh": "供给价格弹性（PES）及其决定因素。",
             "key_concepts": ["Price elasticity of supply"]},
            {"id": "2.7", "title_en": "Role of government in microeconomics", "title_zh": "政府在微观经济中的作用", "level": "both",
             "desc_en": "Indirect taxes, subsidies, and price controls (price ceilings and floors).",
             "desc_zh": "间接税、补贴以及价格管制（最高/最低限价）。",
             "key_concepts": ["Indirect tax", "Subsidy", "Price ceiling", "Price floor"]},
            {"id": "2.8", "title_en": "Market failure — externalities and common pool resources", "title_zh": "市场失灵——外部性与公共池塘资源", "level": "both",
             "desc_en": "Positive and negative externalities of production and consumption; common pool/common access resources and sustainability.",
             "desc_zh": "生产与消费的正负外部性；公共池塘/公共获取资源与可持续性。",
             "key_concepts": ["Market failure", "Externality", "Negative externality of production", "Negative externality of consumption", "Positive externality", "Common pool resources"]},
            {"id": "2.9", "title_en": "Market failure — public goods", "title_zh": "市场失灵——公共物品", "level": "both",
             "desc_en": "Public goods, the free-rider problem, and the distinction from private and common goods.",
             "desc_zh": "公共物品、搭便车问题以及与私人物品、公共资源的区别。",
             "key_concepts": ["Public goods", "Merit goods", "Demerit goods", "Free-rider problem"]},
            {"id": "2.10", "title_en": "Market failure — asymmetric information", "title_zh": "市场失灵——信息不对称", "level": "hl",
             "desc_en": "Adverse selection and moral hazard; responses to asymmetric information. (HL only)",
             "desc_zh": "逆向选择与道德风险；对信息不对称的应对。（仅 HL）",
             "key_concepts": ["Asymmetric information", "Adverse selection", "Moral hazard"]},
            {"id": "2.11", "title_en": "Market failure — market power", "title_zh": "市场失灵——市场力量", "level": "hl",
             "desc_en": "Monopoly, oligopoly and other forms of market power; barriers to entry and government regulation. (HL only)",
             "desc_zh": "垄断、寡头及其他市场力量形式；进入壁垒与政府监管。（仅 HL）",
             "key_concepts": ["Market power", "Monopoly", "Oligopoly", "Barriers to entry"]},
            {"id": "2.12", "title_en": "The market's inability to achieve equity", "title_zh": "市场无法实现公平", "level": "hl",
             "desc_en": "Equity vs equality; how markets may produce unequal outcomes and policies to address them. (HL only)",
             "desc_zh": "公平与平等；市场如何产生不平等结果及应对政策。（仅 HL）",
             "key_concepts": ["Equity", "Equality", "Redistribution of income"]},
        ],
    },
    {
        "id": "macro",
        "order": 3,
        "title_en": "Macroeconomics",
        "title_zh": "宏观经济学",
        "short_en": "Macro",
        "short_zh": "宏观",
        "desc_en": "The economy as a whole: measuring activity, aggregate demand and supply, macroeconomic objectives, and demand- and supply-side policies.",
        "desc_zh": "整体经济：衡量经济活动、总需求与总供给、宏观经济目标以及需求侧与供给侧政策。",
        "topics": [
            {"id": "3.1", "title_en": "Measuring economic activity", "title_zh": "衡量经济活动", "level": "both",
             "desc_en": "GDP, GNI, nominal vs real values, and the circular flow of income.",
             "desc_zh": "GDP、GNI、名义与实际值，以及收入循环流。",
             "hl_extensions": ["Alternative measures of well-being (OECD Better Life Index, Happy Planet Index, ISEW)",
                               "替代性福祉衡量指标（OECD 更美好生活指数、快乐星球指数、可持续经济福利指数）"],
             "key_concepts": ["Gross Domestic Product", "Gross National Income", "Real vs nominal GDP", "Circular flow of income"]},
            {"id": "3.2", "title_en": "Variations in economic activity — AD & AS", "title_zh": "经济活动的变动——总需求与总供给", "level": "both",
             "desc_en": "Aggregate demand and aggregate supply, short-run and long-run equilibrium, and the business cycle.",
             "desc_zh": "总需求与总供给、短期与长期均衡以及经济周期。",
             "hl_extensions": ["Monetarist/new classical vs Keynesian long-run AS; inflationary and deflationary gaps",
                               "货币主义/新古典与凯恩斯的长期总供给；通胀缺口与通缩缺口"],
             "key_concepts": ["Aggregate demand", "Aggregate supply", "Business cycle", "Short-run", "Long-run"]},
            {"id": "3.3", "title_en": "Macroeconomic objectives", "title_zh": "宏观经济目标", "level": "both",
             "desc_en": "Low and stable inflation, low unemployment, economic growth, and equity in the distribution of income.",
             "desc_zh": "低而稳定的通胀、低失业、经济增长以及收入分配的公平。",
             "key_concepts": ["Inflation", "Deflation", "Unemployment", "Economic growth", "Inflation rate"]},
            {"id": "3.4", "title_en": "Economics of inequality and poverty", "title_zh": "不平等与贫困经济学", "level": "both",
             "desc_en": "Measuring inequality (Lorenz curve, Gini coefficient) and poverty; causes and consequences.",
             "desc_zh": "衡量不平等（洛伦兹曲线、基尼系数）与贫困；成因与后果。",
             "key_concepts": ["Income inequality", "Poverty", "Lorenz curve", "Gini coefficient"]},
            {"id": "3.5", "title_en": "Demand management — monetary policy", "title_zh": "需求管理——货币政策", "level": "both",
             "desc_en": "Central banks, interest rates, money supply, and expansionary/contractionary monetary policy.",
             "desc_zh": "中央银行、利率、货币供应以及扩张性/紧缩性货币政策。",
             "hl_extensions": ["Evaluation of monetary policy; central bank independence and credibility",
                               "货币政策的评估；央行的独立性与可信度"],
             "key_concepts": ["Monetary policy", "Interest rate", "Central bank"]},
            {"id": "3.6", "title_en": "Demand management — fiscal policy", "title_zh": "需求管理——财政政策", "level": "both",
             "desc_en": "Government spending, taxation, budget balances, and expansionary/contractionary fiscal policy.",
             "desc_zh": "政府支出、税收、预算平衡以及扩张性/紧缩性财政政策。",
             "hl_extensions": ["Evaluation of fiscal policy; crowding out; automatic stabilizers; public debt sustainability",
                               "财政政策的评估；挤出效应；自动稳定器；公共债务可持续性"],
             "key_concepts": ["Fiscal policy", "Taxation", "Government spending", "Budget deficit"]},
            {"id": "3.7", "title_en": "Supply-side policies", "title_zh": "供给侧政策", "level": "both",
             "desc_en": "Market-based and interventionist supply-side policies to raise productive capacity.",
             "desc_zh": "基于市场与干预主义的供给侧政策，以提高生产能力。",
             "hl_extensions": ["Evaluation of supply-side policies (strengths and limitations)",
                               "供给侧政策的评估（优势与局限）"],
             "key_concepts": ["Supply-side policy", "Productive capacity"]},
        ],
    },
    {
        "id": "global",
        "order": 4,
        "title_en": "The Global Economy",
        "title_zh": "全球经济",
        "short_en": "Global",
        "short_zh": "全球",
        "desc_en": "International trade, exchange rates and the balance of payments, plus development economics: growth, development and sustainability.",
        "desc_zh": "国际贸易、汇率与国际收支，以及发展经济学：增长、发展与可持续性。",
        "topics": [
            {"id": "4.1", "title_en": "Benefits of international trade", "title_zh": "国际贸易的收益", "level": "both",
             "desc_en": "Absolute and comparative advantage, the gains from trade, and the sources of comparative advantage.",
             "desc_zh": "绝对优势与比较优势、贸易收益以及比较优势的来源。",
             "key_concepts": ["Absolute advantage", "Comparative advantage", "Free trade"]},
            {"id": "4.2", "title_en": "Types of trade protection", "title_zh": "贸易保护的类型", "level": "both",
             "desc_en": "Tariffs, quotas, subsidies, and administrative barriers.",
             "desc_zh": "关税、配额、补贴以及行政壁垒。",
             "key_concepts": ["Tariff", "Quota", "Trade protection"]},
            {"id": "4.3", "title_en": "Arguments for and against trade protection", "title_zh": "支持与反对贸易保护的论点", "level": "both",
             "desc_en": "Evaluating protectionism: protecting jobs and infant industries vs higher prices and retaliation.",
             "desc_zh": "评估保护主义：保护就业与幼稚产业 vs 抬高价格与报复。",
             "key_concepts": ["Infant industry", "Trade protection"]},
            {"id": "4.4", "title_en": "Economic integration", "title_zh": "经济一体化", "level": "both",
             "desc_en": "Free trade areas, customs unions, common markets, and monetary unions.",
             "desc_zh": "自由贸易区、关税同盟、共同市场与货币联盟。",
             "hl_extensions": ["Monetary union — advantages and disadvantages",
                               "货币联盟——优势与劣势"],
             "key_concepts": ["Economic integration", "Free trade area", "Customs union", "Common market", "Monetary union"]},
            {"id": "4.5", "title_en": "Exchange rates", "title_zh": "汇率", "level": "both",
             "desc_en": "Floating and fixed exchange rates, appreciation/depreciation, and their effects.",
             "desc_zh": "浮动与固定汇率、升值/贬值及其影响。",
             "key_concepts": ["Exchange rate", "Appreciation", "Depreciation"]},
            {"id": "4.6", "title_en": "Balance of payments", "title_zh": "国际收支", "level": "both",
             "desc_en": "The current account, financial account, and the links between them.",
             "desc_zh": "经常账户、金融账户及其联系。",
             "hl_extensions": ["Marshall–Lerner condition and the J-curve effect",
                               "马歇尔–勒纳条件与 J 曲线效应"],
             "key_concepts": ["Balance of payments", "Current account", "Trade deficit", "Trade surplus"]},
            {"id": "4.7", "title_en": "Sustainable development", "title_zh": "可持续发展", "level": "both",
             "desc_en": "The meaning of sustainable development and the relationship between growth and sustainability.",
             "desc_zh": "可持续发展的含义以及增长与可持续性之间的关系。",
             "key_concepts": ["Sustainable development", "Sustainability"]},
            {"id": "4.8", "title_en": "Measuring development", "title_zh": "衡量发展", "level": "both",
             "desc_en": "Economic development, the Human Development Index (HDI), and its strengths and limitations.",
             "desc_zh": "经济发展、人类发展指数（HDI）及其优势与局限。",
             "key_concepts": ["Economic development", "Human Development Index"]},
            {"id": "4.9", "title_en": "Barriers to economic growth and/or development", "title_zh": "经济增长/发展的障碍", "level": "both",
             "desc_en": "Poverty traps, poor infrastructure, inequality, and other barriers to growth and development.",
             "desc_zh": "贫困陷阱、基础设施落后、不平等及其他增长与发展障碍。",
             "key_concepts": ["Poverty trap", "Economic growth"]},
            {"id": "4.10", "title_en": "Economic growth and/or development strategies", "title_zh": "经济增长/发展战略", "level": "both",
             "desc_en": "Trade strategies, FDI, foreign aid (ODA), and market-led vs interventionist strategies.",
             "desc_zh": "贸易战略、外商直接投资、对外援助（ODA），以及市场主导 vs 干预主义战略。",
             "key_concepts": ["Foreign direct investment", "Official development assistance", "Multinational corporation"]},
        ],
    },
]

# ---------------------------------------------------------------------------
# Glossary (bilingual)
# ---------------------------------------------------------------------------

GLOSSARY = [
    # Introduction
    {"term_en": "Scarcity", "term_zh": "稀缺性", "topic": "1.1",
     "def_en": "The fundamental economic problem: unlimited wants but limited resources.",
     "def_zh": "基本经济问题：无限的欲望与有限的资源。"},
    {"term_en": "Opportunity cost", "term_zh": "机会成本", "topic": "1.1",
     "def_en": "The value of the next best alternative foregone when a choice is made.",
     "def_zh": "做出选择时所放弃的次优替代方案的价值。"},
    {"term_en": "Factors of production", "term_zh": "生产要素", "topic": "1.1",
     "def_en": "Resources used to produce goods and services: land, labour, capital, and entrepreneurship.",
     "def_zh": "用于生产商品与服务的资源：土地、劳动、资本与企业家才能。"},
    {"term_en": "Ceteris paribus", "term_zh": "其他条件不变", "topic": "1.2",
     "def_en": "The assumption that all other variables are held constant when analysing one variable.",
     "def_zh": "分析某一变量时假定其他变量保持不变的假设。"},
    {"term_en": "Economic goods", "term_zh": "经济物品", "topic": "1.1",
     "def_en": "Goods that are scarce and therefore command a price.",
     "def_zh": "具有稀缺性、因而需要付出代价的商品。"},
    {"term_en": "Free goods", "term_zh": "免费物品", "topic": "1.1",
     "def_en": "Goods that are abundant with no opportunity cost (e.g. air).",
     "def_zh": "充裕且无机会成本的物品（如空气）。"},
    {"term_en": "Positive economics", "term_zh": "实证经济学", "topic": "1.2",
     "def_en": "Objective, testable statements about how the economy works (what is).",
     "def_zh": "关于经济如何运行的客观、可检验的陈述（是什么）。"},
    {"term_en": "Normative economics", "term_zh": "规范经济学", "topic": "1.2",
     "def_en": "Subjective, value-based statements about what should be.",
     "def_zh": "关于应该怎样的主观、价值判断的陈述。"},
    {"term_en": "Economic model", "term_zh": "经济模型", "topic": "1.2",
     "def_en": "A simplified representation of reality used to analyse economic behaviour.",
     "def_zh": "用于分析经济行为的简化现实表示。"},

    # Microeconomics
    {"term_en": "Demand", "term_zh": "需求", "topic": "2.1",
     "def_en": "The quantity of a good consumers are willing and able to buy at each price over a period.",
     "def_zh": "在一定时期内，消费者在各价格水平上愿意且能够购买的数量。"},
    {"term_en": "Law of demand", "term_zh": "需求定律", "topic": "2.1",
     "def_en": "As price falls, quantity demanded rises (ceteris paribus).",
     "def_zh": "价格下降，需求量上升（其他条件不变）。"},
    {"term_en": "Supply", "term_zh": "供给", "topic": "2.2",
     "def_en": "The quantity of a good producers are willing and able to sell at each price over a period.",
     "def_zh": "在一定时期内，生产者在各价格水平上愿意且能够出售的数量。"},
    {"term_en": "Law of supply", "term_zh": "供给定律", "topic": "2.2",
     "def_en": "As price rises, quantity supplied rises (ceteris paribus).",
     "def_zh": "价格上升，供给量上升（其他条件不变）。"},
    {"term_en": "Market equilibrium", "term_zh": "市场均衡", "topic": "2.3",
     "def_en": "The price and quantity where quantity demanded equals quantity supplied.",
     "def_zh": "需求量等于供给量时的价格与数量。"},
    {"term_en": "Price mechanism", "term_zh": "价格机制", "topic": "2.3",
     "def_en": "How price signals and incentives allocate scarce resources in a market.",
     "def_zh": "价格信号与激励如何在市场中配置稀缺资源。"},
    {"term_en": "Consumer surplus", "term_zh": "消费者剩余", "topic": "2.3",
     "def_en": "The extra benefit consumers gain by paying less than they were willing to pay.",
     "def_zh": "消费者因支付价格低于其意愿价格而获得的额外收益。"},
    {"term_en": "Producer surplus", "term_zh": "生产者剩余", "topic": "2.3",
     "def_en": "The extra benefit producers gain by receiving more than their minimum acceptable price.",
     "def_zh": "生产者因收取价格高于其最低可接受价格而获得的额外收益。"},
    {"term_en": "Allocative efficiency", "term_zh": "配置效率", "topic": "2.3",
     "def_en": "Resources are allocated to match consumer preferences; price equals marginal cost.",
     "def_zh": "资源配置与消费者偏好相匹配；价格等于边际成本。"},
    {"term_en": "Behavioural economics", "term_zh": "行为经济学", "topic": "2.4",
     "def_en": "The study of how psychological factors cause people to deviate from rational choice.",
     "def_zh": "研究心理因素如何使人们偏离理性选择。"},
    {"term_en": "Rational choice", "term_zh": "理性选择", "topic": "2.4",
     "def_en": "The assumption that consumers and producers act to maximize their own utility or profit.",
     "def_zh": "假定消费者与生产者以实现自身效用或利润最大化为目标。"},
    {"term_en": "Price elasticity of demand", "term_zh": "需求价格弹性", "topic": "2.5",
     "def_en": "The responsiveness of quantity demanded to a change in price (PED).",
     "def_zh": "需求量对价格变动的反应程度（PED）。"},
    {"term_en": "Income elasticity of demand", "term_zh": "需求收入弹性", "topic": "2.5",
     "def_en": "The responsiveness of demand to a change in income (YED).",
     "def_zh": "需求对收入变动的反应程度（YED）。"},
    {"term_en": "Cross-price elasticity of demand", "term_zh": "需求交叉弹性", "topic": "2.5",
     "def_en": "The responsiveness of demand for one good to a change in the price of another (XED).",
     "def_zh": "一种商品需求对另一种商品价格变动的反应程度（XED）。"},
    {"term_en": "Price elasticity of supply", "term_zh": "供给价格弹性", "topic": "2.6",
     "def_en": "The responsiveness of quantity supplied to a change in price (PES).",
     "def_zh": "供给量对价格变动的反应程度（PES）。"},
    {"term_en": "Indirect tax", "term_zh": "间接税", "topic": "2.7",
     "def_en": "A tax on expenditure (e.g. VAT, excise) that can be passed on to consumers.",
     "def_zh": "对支出征收的税（如增值税、消费税），可转嫁给消费者。"},
    {"term_en": "Subsidy", "term_zh": "补贴", "topic": "2.7",
     "def_en": "Government financial support to producers, lowering cost and raising output.",
     "def_zh": "政府对生产者的财政支持，降低成本、提高产量。"},
    {"term_en": "Price ceiling", "term_zh": "最高限价", "topic": "2.7",
     "def_en": "A legal maximum price set below equilibrium (e.g. rent control), causing excess demand.",
     "def_zh": "设定在均衡价格之下的法定最高价（如租金管制），造成超额需求。"},
    {"term_en": "Price floor", "term_zh": "最低限价", "topic": "2.7",
     "def_en": "A legal minimum price set above equilibrium (e.g. minimum wage), causing excess supply.",
     "def_zh": "设定在均衡价格之上的法定最低价（如最低工资），造成超额供给。"},
    {"term_en": "Market failure", "term_zh": "市场失灵", "topic": "2.8",
     "def_en": "When the free market fails to allocate resources efficiently.",
     "def_zh": "自由市场未能有效配置资源的情况。"},
    {"term_en": "Externality", "term_zh": "外部性", "topic": "2.8",
     "def_en": "A cost or benefit imposed on a third party not involved in a transaction.",
     "def_zh": "强加于交易无关第三方的成本或收益。"},
    {"term_en": "Negative externality of production", "term_zh": "生产负外部性", "topic": "2.8",
     "def_en": "A spillover cost from production (e.g. pollution) not reflected in price.",
     "def_zh": "生产中未反映在价格中的溢出成本（如污染）。"},
    {"term_en": "Negative externality of consumption", "term_zh": "消费负外部性", "topic": "2.8",
     "def_en": "A spillover cost from consumption (e.g. passive smoking).",
     "def_zh": "消费中产生的溢出成本（如二手烟）。"},
    {"term_en": "Positive externality", "term_zh": "正外部性", "topic": "2.8",
     "def_en": "A spillover benefit (e.g. education, vaccination) under-provided by the market.",
     "def_zh": "市场供给不足的溢出收益（如教育、疫苗接种）。"},
    {"term_en": "Common pool resources", "term_zh": "公共池塘资源", "topic": "2.8",
     "def_en": "Rivalrous but non-excludable resources (e.g. fish stocks) prone to overuse.",
     "def_zh": "具有竞争性但非排他性的资源（如鱼类资源），易被过度使用。"},
    {"term_en": "Public goods", "term_zh": "公共物品", "topic": "2.9",
     "def_en": "Non-rivalrous and non-excludable goods (e.g. national defence) under-provided by markets.",
     "def_zh": "非竞争且非排他的物品（如国防），市场供给不足。"},
    {"term_en": "Free-rider problem", "term_zh": "搭便车问题", "topic": "2.9",
     "def_en": "People benefiting from a public good without paying for it.",
     "def_zh": "人们享用公共物品却不为其付费。"},
    {"term_en": "Merit goods", "term_zh": "优值品", "topic": "2.9",
     "def_en": "Goods under-consumed because people undervalue their benefits (e.g. education).",
     "def_zh": "因人们低估其收益而被消费不足的商品（如教育）。"},
    {"term_en": "Demerit goods", "term_zh": "劣值品", "topic": "2.9",
     "def_en": "Goods over-consumed because people underestimate their harm (e.g. cigarettes).",
     "def_zh": "因人们低估其危害而被过度消费的商品（如香烟）。"},
    {"term_en": "Asymmetric information", "term_zh": "信息不对称", "topic": "2.10",
     "def_en": "One party in a transaction has more information than the other. (HL)",
     "def_zh": "交易中一方比另一方掌握更多信息。（HL）"},
    {"term_en": "Adverse selection", "term_zh": "逆向选择", "topic": "2.10",
     "def_en": "A situation where asymmetric information causes low-quality participants to dominate a market. (HL)",
     "def_zh": "信息不对称导致低质量参与者主导市场的情况。（HL）"},
    {"term_en": "Moral hazard", "term_zh": "道德风险", "topic": "2.10",
     "def_en": "Riskier behaviour when a party is insulated from consequences. (HL)",
     "def_zh": "一方因不承担后果而采取更冒险行为。（HL）"},
    {"term_en": "Market power", "term_zh": "市场力量", "topic": "2.11",
     "def_en": "The ability of a firm to influence price and restrict competition. (HL)",
     "def_zh": "企业影响价格、限制竞争的能力。（HL）"},
    {"term_en": "Monopoly", "term_zh": "垄断", "topic": "2.11",
     "def_en": "A single dominant firm with significant market power. (HL)",
     "def_zh": "具有显著市场力量的单一主导企业。（HL）"},
    {"term_en": "Oligopoly", "term_zh": "寡头", "topic": "2.11",
     "def_en": "A market dominated by a few large interdependent firms. (HL)",
     "def_zh": "由少数几家相互依存的大企业主导的市场。（HL）"},
    {"term_en": "Barriers to entry", "term_zh": "进入壁垒", "topic": "2.11",
     "def_en": "Obstacles that prevent new firms entering a market. (HL)",
     "def_zh": "阻止新企业进入市场的障碍。（HL）"},
    {"term_en": "Equity", "term_zh": "公平", "topic": "2.12",
     "def_en": "Fairness in the distribution of income and opportunity. (HL)",
     "def_zh": "收入与机会分配的公平性。（HL）"},
    {"term_en": "Equality", "term_zh": "平等", "topic": "2.12",
     "def_en": "Everyone receiving the same, regardless of circumstances. (HL)",
     "def_zh": "无论情况如何，人人获得相同待遇。（HL）"},
    {"term_en": "Redistribution of income", "term_zh": "收入再分配", "topic": "2.12",
     "def_en": "Government policies (taxes and transfers) to reduce inequality. (HL)",
     "def_zh": "政府为减少不平等而采取的政策（税收与转移支付）。（HL）"},

    # Macroeconomics
    {"term_en": "Gross Domestic Product", "term_zh": "国内生产总值（GDP）", "topic": "3.1",
     "def_en": "The total value of final goods and services produced within a country in a period.",
     "def_zh": "一国在一段时期内生产的最终商品与服务的总价值。"},
    {"term_en": "Gross National Income", "term_zh": "国民总收入（GNI）", "topic": "3.1",
     "def_en": "GDP plus net income from abroad.",
     "def_zh": "GDP 加上来自国外的净收入。"},
    {"term_en": "Real vs nominal GDP", "term_zh": "实际与名义 GDP", "topic": "3.1",
     "def_en": "Real GDP is adjusted for inflation; nominal GDP is not.",
     "def_zh": "实际 GDP 经通胀调整；名义 GDP 未经调整。"},
    {"term_en": "Circular flow of income", "term_zh": "收入循环流", "topic": "3.1",
     "def_en": "The flow of income between households and firms, with leakages and injections.",
     "def_zh": "家庭与企业之间的收入流动，含漏出与注入。"},
    {"term_en": "Aggregate demand", "term_zh": "总需求（AD）", "topic": "3.2",
     "def_en": "Total spending on domestic goods and services: C + I + G + (X − M).",
     "def_zh": "对国内商品与服务的总支出：C + I + G + (X − M)。"},
    {"term_en": "Aggregate supply", "term_zh": "总供给（AS）", "topic": "3.2",
     "def_en": "Total output producers are willing and able to supply at each price level.",
     "def_zh": "生产者在各价格水平上愿意且能够供给的总产出。"},
    {"term_en": "Business cycle", "term_zh": "经济周期", "topic": "3.2",
     "def_en": "Fluctuations in economic activity: expansion, peak, contraction, trough.",
     "def_zh": "经济活动的波动：扩张、顶峰、收缩、谷底。"},
    {"term_en": "Short-run", "term_zh": "短期", "topic": "3.2",
     "def_en": "A period in which at least one factor of production is fixed.",
     "def_zh": "至少一种生产要素固定的时期。"},
    {"term_en": "Long-run", "term_zh": "长期", "topic": "3.2",
     "def_en": "A period in which all factors of production are variable.",
     "def_zh": "所有生产要素均可变的时期。"},
    {"term_en": "Inflation", "term_zh": "通货膨胀", "topic": "3.3",
     "def_en": "A sustained rise in the general price level.",
     "def_zh": "总体价格水平的持续上升。"},
    {"term_en": "Deflation", "term_zh": "通货紧缩", "topic": "3.3",
     "def_en": "A sustained fall in the general price level.",
     "def_zh": "总体价格水平的持续下降。"},
    {"term_en": "Unemployment", "term_zh": "失业", "topic": "3.3",
     "def_en": "People actively seeking work but unable to find employment.",
     "def_zh": "积极寻找工作但无法就业的人群。"},
    {"term_en": "Economic growth", "term_zh": "经济增长", "topic": "3.3",
     "def_en": "An increase in real output (GDP) over time.",
     "def_zh": "实际产出（GDP）随时间的增长。"},
    {"term_en": "Inflation rate", "term_zh": "通货膨胀率", "topic": "3.3",
     "def_en": "The percentage change in a price index (CPI) over a period.",
     "def_zh": "物价指数（CPI）在一段时期内的百分比变化。"},
    {"term_en": "Income inequality", "term_zh": "收入不平等", "topic": "3.4",
     "def_en": "The uneven distribution of income across a population.",
     "def_zh": "收入在人口中分配不均。"},
    {"term_en": "Poverty", "term_zh": "贫困", "topic": "3.4",
     "def_en": "Absolute poverty is income below a subsistence level; relative poverty is relative to society's median.",
     "def_zh": "绝对贫困指收入低于生存水平；相对贫困指相对于社会中位数。"},
    {"term_en": "Lorenz curve", "term_zh": "洛伦兹曲线", "topic": "3.4",
     "def_en": "A graph showing the cumulative distribution of income across a population.",
     "def_zh": "显示人口累计收入分配的图形。"},
    {"term_en": "Gini coefficient", "term_zh": "基尼系数", "topic": "3.4",
     "def_en": "A measure of inequality (0 = perfect equality, 1 = perfect inequality).",
     "def_zh": "衡量不平等的指标（0 = 完全平等，1 = 完全不平等）。"},
    {"term_en": "Monetary policy", "term_zh": "货币政策", "topic": "3.5",
     "def_en": "Central bank control of interest rates and money supply to manage demand.",
     "def_zh": "央行通过调控利率与货币供应来管理需求。"},
    {"term_en": "Interest rate", "term_zh": "利率", "topic": "3.5",
     "def_en": "The cost of borrowing / reward for saving, set by the central bank.",
     "def_zh": "借款成本/储蓄回报，由央行设定。"},
    {"term_en": "Central bank", "term_zh": "中央银行", "topic": "3.5",
     "def_en": "The institution responsible for monetary policy and financial stability.",
     "def_zh": "负责货币政策与金融稳定的机构。"},
    {"term_en": "Fiscal policy", "term_zh": "财政政策", "topic": "3.6",
     "def_en": "Government use of spending and taxation to influence the economy.",
     "def_zh": "政府运用支出与税收影响经济。"},
    {"term_en": "Taxation", "term_zh": "税收", "topic": "3.6",
     "def_en": "Compulsory payments to government: direct (on income) or indirect (on spending).",
     "def_zh": "向政府缴纳的强制性款项：直接（对收入）或间接（对支出）。"},
    {"term_en": "Government spending", "term_zh": "政府支出", "topic": "3.6",
     "def_en": "Expenditure on public goods, services, and transfers.",
     "def_zh": "用于公共物品、服务与转移支付的支出。"},
    {"term_en": "Budget deficit", "term_zh": "财政赤字", "topic": "3.6",
     "def_en": "When government spending exceeds tax revenue in a period.",
     "def_zh": "一段时期内政府支出超过税收收入。"},
    {"term_en": "Supply-side policy", "term_zh": "供给侧政策", "topic": "3.7",
     "def_en": "Policies to increase the economy's productive capacity and long-run growth.",
     "def_zh": "提高经济生产能力与长期增长的政策。"},
    {"term_en": "Productive capacity", "term_zh": "生产能力", "topic": "3.7",
     "def_en": "The maximum output an economy can produce with its resources.",
     "def_zh": "经济利用其资源所能生产的最大产出。"},

    # Global economy
    {"term_en": "Absolute advantage", "term_zh": "绝对优势", "topic": "4.1",
     "def_en": "The ability to produce a good using fewer resources than another country.",
     "def_zh": "以比另一国更少的资源生产某种商品的能力。"},
    {"term_en": "Comparative advantage", "term_zh": "比较优势", "topic": "4.1",
     "def_en": "The ability to produce a good at a lower opportunity cost than another country.",
     "def_zh": "以比另一国更低的机会成本生产某种商品的能力。"},
    {"term_en": "Free trade", "term_zh": "自由贸易", "topic": "4.1",
     "def_en": "International trade without government-imposed barriers.",
     "def_zh": "没有政府设置的壁垒的国际贸易。"},
    {"term_en": "Tariff", "term_zh": "关税", "topic": "4.2",
     "def_en": "A tax on imported goods, raising their domestic price.",
     "def_zh": "对进口商品征收的税，提高其国内价格。"},
    {"term_en": "Quota", "term_zh": "配额", "topic": "4.2",
     "def_en": "A quantitative limit on the amount of a good that may be imported.",
     "def_zh": "对可进口商品数量的定量限制。"},
    {"term_en": "Trade protection", "term_zh": "贸易保护", "topic": "4.2",
     "def_en": "Policies that restrict imports to protect domestic producers.",
     "def_zh": "为保护国内生产者而限制进口的政策。"},
    {"term_en": "Infant industry", "term_zh": "幼稚产业", "topic": "4.3",
     "def_en": "A new industry that needs temporary protection to become competitive.",
     "def_zh": "需要临时保护才能具备竞争力的新兴产业。"},
    {"term_en": "Economic integration", "term_zh": "经济一体化", "topic": "4.4",
     "def_en": "The process of countries reducing trade barriers and coordinating policies.",
     "def_zh": "各国降低贸易壁垒并协调政策的过程。"},
    {"term_en": "Free trade area", "term_zh": "自由贸易区", "topic": "4.4",
     "def_en": "Members remove trade barriers among themselves but keep independent external tariffs.",
     "def_zh": "成员间取消贸易壁垒，但各自保留独立的对外关税。"},
    {"term_en": "Customs union", "term_zh": "关税同盟", "topic": "4.4",
     "def_en": "A free trade area with a common external tariff on non-members.",
     "def_zh": "自由贸易区加上对非成员的共同对外关税。"},
    {"term_en": "Common market", "term_zh": "共同市场", "topic": "4.4",
     "def_en": "A customs union plus free movement of factors of production.",
     "def_zh": "关税同盟加上生产要素的自由流动。"},
    {"term_en": "Monetary union", "term_zh": "货币联盟", "topic": "4.4",
     "def_en": "A common currency and monetary policy across members. (HL)",
     "def_zh": "成员间采用共同货币与货币政策。（HL）"},
    {"term_en": "Exchange rate", "term_zh": "汇率", "topic": "4.5",
     "def_en": "The price of one currency in terms of another.",
     "def_zh": "一种货币以另一种货币表示的价格。"},
    {"term_en": "Appreciation", "term_zh": "升值", "topic": "4.5",
     "def_en": "A rise in a currency's value under a floating exchange rate.",
     "def_zh": "浮动汇率下货币价值的上升。"},
    {"term_en": "Depreciation", "term_zh": "贬值", "topic": "4.5",
     "def_en": "A fall in a currency's value under a floating exchange rate.",
     "def_zh": "浮动汇率下货币价值的下降。"},
    {"term_en": "Balance of payments", "term_zh": "国际收支", "topic": "4.6",
     "def_en": "A record of all transactions between a country and the rest of the world.",
     "def_zh": "一国与世界其他地区所有交易的记录。"},
    {"term_en": "Current account", "term_zh": "经常账户", "topic": "4.6",
     "def_en": "The balance of trade in goods and services plus net income and transfers.",
     "def_zh": "货物与服务贸易差额加上净收入与转移支付。"},
    {"term_en": "Trade deficit", "term_zh": "贸易逆差", "topic": "4.6",
     "def_en": "When the value of imports exceeds the value of exports.",
     "def_zh": "进口价值超过出口价值的情况。"},
    {"term_en": "Trade surplus", "term_zh": "贸易顺差", "topic": "4.6",
     "def_en": "When the value of exports exceeds the value of imports.",
     "def_zh": "出口价值超过进口价值的情况。"},
    {"term_en": "Sustainable development", "term_zh": "可持续发展", "topic": "4.7",
     "def_en": "Development that meets present needs without compromising future generations.",
     "def_zh": "满足当代需求而又不损害后代的发展。"},
    {"term_en": "Sustainability", "term_zh": "可持续性", "topic": "4.7",
     "def_en": "The ability to maintain a process or level of resource use over time.",
     "def_zh": "长期维持某种过程或资源使用水平的能力。"},
    {"term_en": "Economic development", "term_zh": "经济发展", "topic": "4.8",
     "def_en": "Improvements in living standards, health, education, and well-being.",
     "def_zh": "生活水平、健康、教育与福祉的改善。"},
    {"term_en": "Human Development Index", "term_zh": "人类发展指数（HDI）", "topic": "4.8",
     "def_en": "A composite measure of income, life expectancy, and education.",
     "def_zh": "综合衡量收入、预期寿命与教育的指标。"},
    {"term_en": "Poverty trap", "term_zh": "贫困陷阱", "topic": "4.9",
     "def_en": "A self-reinforcing cycle where low income prevents the investment needed to escape poverty.",
     "def_zh": "低收入阻碍脱贫所需投资的自我强化循环。"},
    {"term_en": "Foreign direct investment", "term_zh": "外商直接投资（FDI）", "topic": "4.10",
     "def_en": "Long-term investment by a firm in productive assets in another country.",
     "def_zh": "企业在另一国生产性资产上的长期投资。"},
    {"term_en": "Official development assistance", "term_zh": "官方发展援助（ODA）", "topic": "4.10",
     "def_en": "Concessional aid from governments and international organizations to developing countries.",
     "def_zh": "政府与国际组织向发展中国家提供的优惠性援助。"},
    {"term_en": "Multinational corporation", "term_zh": "跨国公司（MNC）", "topic": "4.10",
     "def_en": "A firm that operates in more than one country.",
     "def_zh": "在多个国家经营的企业。"},
]

# ---------------------------------------------------------------------------
# Assessment (first assessment 2022)
# ---------------------------------------------------------------------------

ASSESSMENT = {
    "SL": {
        "name_en": "Standard Level",
        "name_zh": "标准级别（SL）",
        "total_marks": 95,
        "components": [
            {"id": "p1", "name_en": "Paper 1 — Extended response", "name_zh": "卷一 · 延伸回答题",
             "time": "1 h 15 m", "marks": 25, "weight": 30, "external": True,
             "note_en": "Answer 1 of 3 questions; each has (a) 10 marks and (b) 15 marks.",
             "note_zh": "从 3 题中选答 1 题；每题含 (a) 10 分与 (b) 15 分。"},
            {"id": "p2", "name_en": "Paper 2 — Data response", "name_zh": "卷二 · 数据回应题",
             "time": "1 h 30 m", "marks": 40, "weight": 40, "external": True,
             "note_en": "One compulsory data response question (40 marks).",
             "note_zh": "一道必答数据回应题（40 分）。"},
            {"id": "ia", "name_en": "Internal assessment — Portfolio", "name_zh": "内部评估 · 评论组合",
             "time": "—", "marks": 30, "weight": 30, "external": False,
             "note_en": "3 commentaries (~800 words each), one each from micro, macro and the global economy, based on real news articles.",
             "note_zh": "3 篇评论（每篇约 800 词），分别取材自微观、宏观与全球经济，基于真实新闻文章。"},
        ],
    },
    "HL": {
        "name_en": "Higher Level",
        "name_zh": "高级别（HL）",
        "total_marks": 155,
        "components": [
            {"id": "p1", "name_en": "Paper 1 — Extended response", "name_zh": "卷一 · 延伸回答题",
             "time": "1 h 15 m", "marks": 25, "weight": 20, "external": True,
             "note_en": "Answer 1 of 3 questions; each has (a) 10 marks and (b) 15 marks (more demanding).",
             "note_zh": "从 3 题中选答 1 题；每题含 (a) 10 分与 (b) 15 分（要求更高）。"},
            {"id": "p2", "name_en": "Paper 2 — Data response", "name_zh": "卷二 · 数据回应题",
             "time": "1 h 45 m", "marks": 40, "weight": 30, "external": True,
             "note_en": "One compulsory data response question (40 marks).",
             "note_zh": "一道必答数据回应题（40 分）。"},
            {"id": "p3", "name_en": "Paper 3 — Policy paper", "name_zh": "卷三 · 政策题（仅 HL）",
             "time": "1 h 45 m", "marks": 60, "weight": 30, "external": True,
             "note_en": "Two compulsory questions (60 marks); HL only.",
             "note_zh": "两道必答题（60 分）；仅 HL。"},
            {"id": "ia", "name_en": "Internal assessment — Portfolio", "name_zh": "内部评估 · 评论组合",
             "time": "—", "marks": 30, "weight": 20, "external": False,
             "note_en": "3 commentaries (~800 words each), one each from micro, macro and the global economy.",
             "note_zh": "3 篇评论（每篇约 800 词），分别取材自微观、宏观与全球经济。"},
        ],
    },
}

# ---------------------------------------------------------------------------
# Command terms (for command-term analysis)
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Cross-topic relationships (curated) — economics is a whole, so link topics
# across units, especially macro <-> micro / global spillovers.
# type: "micro" | "macro" | "global" | "macro2micro" | "micro2macro" | "cross"
# ---------------------------------------------------------------------------

RELATED_TOPICS = [
    # —— within micro ——
    {"a": "2.1", "b": "2.5", "type": "micro",
     "rel_en": "Elasticity of demand measures how responsive demand is to price and income changes.",
     "rel_zh": "需求弹性衡量需求对价格与收入变化的反应程度。"},
    {"a": "2.2", "b": "2.6", "type": "micro",
     "rel_en": "Elasticity of supply measures how responsive supply is to price changes.",
     "rel_zh": "供给弹性衡量供给对价格变化的反应程度。"},
    {"a": "2.3", "b": "2.7", "type": "micro",
     "rel_en": "Government price controls, taxes and subsidies intervene directly on market equilibrium.",
     "rel_zh": "政府的价格管制、税收与补贴直接干预市场均衡。"},
    {"a": "2.5", "b": "2.7", "type": "micro",
     "rel_en": "PED determines the incidence of an indirect tax between consumers and producers.",
     "rel_zh": "需求价格弹性决定间接税在消费者与生产者之间的税负归宿。"},
    {"a": "2.8", "b": "2.9", "type": "micro",
     "rel_en": "Externalities and public goods are two classic sources of market failure.",
     "rel_zh": "外部性与公共物品是两种典型的市场失灵来源。"},
    {"a": "2.10", "b": "2.11", "type": "micro",
     "rel_en": "Asymmetric information and market power are both HL market-failure causes.",
     "rel_zh": "信息不对称与市场力量同为 HL 市场失灵成因。"},

    # —— within macro ——
    {"a": "3.1", "b": "3.3", "type": "macro",
     "rel_en": "GDP and inflation figures are used to measure the macroeconomic objectives.",
     "rel_zh": "GDP 与通胀数据用于衡量宏观经济目标。"},
    {"a": "3.2", "b": "3.3", "type": "macro",
     "rel_en": "The AD/AS model explains inflation, unemployment and growth (the objectives).",
     "rel_zh": "AD/AS 模型解释通胀、失业与增长等宏观目标。"},
    {"a": "3.5", "b": "3.6", "type": "macro",
     "rel_en": "Monetary and fiscal policy are the two demand-side management tools.",
     "rel_zh": "货币政策与财政政策是两大需求侧管理工具。"},
    {"a": "3.4", "b": "3.7", "type": "macro",
     "rel_en": "Education/training supply-side policies help reduce inequality and poverty.",
     "rel_zh": "教育培训类供给侧政策有助于减少不平等与贫困。"},

    # —— within global ——
    {"a": "4.1", "b": "4.2", "type": "global",
     "rel_en": "Trade protection (tariffs, quotas) reduces the benefits of free trade.",
     "rel_zh": "贸易保护（关税、配额）削弱自由贸易的收益。"},
    {"a": "4.5", "b": "4.6", "type": "global",
     "rel_en": "Exchange-rate movements directly affect the current account balance.",
     "rel_zh": "汇率变动直接影响经常账户差额。"},
    {"a": "4.8", "b": "4.9", "type": "global",
     "rel_en": "Barriers to development explain why HDI and living standards stay low.",
     "rel_zh": "发展障碍解释了为何 HDI 与生活水平长期偏低。"},
    {"a": "4.7", "b": "4.10", "type": "global",
     "rel_en": "Development strategies should respect environmental sustainability.",
     "rel_zh": "发展战略应兼顾环境可持续性。"},

    # —— macro environment -> micro (整体环境影响微观) ——
    {"a": "3.5", "b": "2.1", "type": "macro2micro",
     "rel_en": "Interest-rate changes affect borrowing and consumption, shifting demand.",
     "rel_zh": "利率变化影响借贷与消费，使需求移动。"},
    {"a": "3.5", "b": "2.2", "type": "macro2micro",
     "rel_en": "Higher interest rates raise firms' cost of capital, shifting supply.",
     "rel_zh": "利率上升提高企业融资成本，使供给移动。"},
    {"a": "3.6", "b": "2.7", "type": "macro2micro",
     "rel_en": "Taxation and subsidies are fiscal-policy tools applied at the micro level.",
     "rel_zh": "税收与补贴是作用于微观层面的财政政策工具。"},
    {"a": "3.3", "b": "2.3", "type": "macro2micro",
     "rel_en": "Inflation erodes purchasing power and shifts individual market prices.",
     "rel_zh": "通胀侵蚀购买力并推高个别市场价格。"},
    {"a": "3.2", "b": "2.3", "type": "macro2micro",
     "rel_en": "Aggregate demand aggregates the demand of all individual markets.",
     "rel_zh": "总需求是个别市场需求的总和。"},
    {"a": "3.7", "b": "2.2", "type": "macro2micro",
     "rel_en": "Supply-side policies raise productivity and lower firm costs (supply).",
     "rel_zh": "供给侧政策提升生产率、降低企业成本（供给）。"},
    {"a": "3.4", "b": "2.12", "type": "macro2micro",
     "rel_en": "Inequality relates to the HL idea that markets fail to achieve equity.",
     "rel_zh": "不平等对应 HL 中市场无法实现公平的观点。"},

    # —— micro -> macro (微观基础支撑宏观) ——
    {"a": "2.8", "b": "3.3", "type": "micro2macro",
     "rel_en": "Correcting externalities (e.g. carbon tax) feeds into macro objectives.",
     "rel_zh": "纠正外部性（如碳税）服务于宏观经济目标。"},
    {"a": "2.11", "b": "3.4", "type": "micro2macro",
     "rel_en": "Market power can worsen income inequality across the economy. (HL)",
     "rel_zh": "市场力量可能加剧整体收入不平等。（HL）"},

    # —— global <-> macro / micro ——
    {"a": "4.5", "b": "3.3", "type": "cross",
     "rel_en": "A depreciation raises import prices, feeding imported inflation.",
     "rel_zh": "本币贬值抬高进口价格，引发输入型通胀。"},
    {"a": "4.6", "b": "3.2", "type": "cross",
     "rel_en": "The current account is the (X−M) component of aggregate demand.",
     "rel_zh": "经常账户是总需求中 (X−M) 的组成部分。"},
    {"a": "4.2", "b": "2.2", "type": "cross",
     "rel_en": "Tariffs and quotas raise domestic prices and shift domestic supply/demand.",
     "rel_zh": "关税与配额抬高国内价格，移动国内供求。"},
    {"a": "4.7", "b": "2.8", "type": "cross",
     "rel_en": "Sustainability is undermined by negative production externalities.",
     "rel_zh": "生产负外部性损害可持续性。"},
    {"a": "4.10", "b": "3.7", "type": "cross",
     "rel_en": "Development strategies often rely on supply-side policies.",
     "rel_zh": "发展战略常依赖供给侧政策。"},
]

COMMAND_TERMS = [
    {"term_en": "Define", "term_zh": "下定义", "ao": 1,
     "def_en": "Give the precise meaning of a term.", "def_zh": "给出术语的准确含义。"},
    {"term_en": "Describe", "term_zh": "描述", "ao": 1,
     "def_en": "Give a detailed account.", "def_zh": "给出详细说明。"},
    {"term_en": "State", "term_zh": "陈述", "ao": 1,
     "def_en": "Give a specific name, value or fact without explanation.", "def_zh": "给出具体名称、数值或事实，无需解释。"},
    {"term_en": "Outline", "term_zh": "概述", "ao": 1,
     "def_en": "Give a brief account or summary.", "def_zh": "给出简要说明或总结。"},
    {"term_en": "List", "term_zh": "列举", "ao": 1,
     "def_en": "Give a sequence of brief answers with no explanation.", "def_zh": "给出若干简要答案，无需解释。"},
    {"term_en": "Identify", "term_zh": "识别", "ao": 1,
     "def_en": "Provide an answer from a number of possibilities.", "def_zh": "从若干可能性中给出答案。"},
    {"term_en": "Calculate", "term_zh": "计算", "ao": 2,
     "def_en": "Obtain a numerical answer, showing relevant working.", "def_zh": "得出数值答案并展示相关过程。"},
    {"term_en": "Draw", "term_zh": "绘制", "ao": 1,
     "def_en": "Represent by means of a labelled, accurate diagram.", "def_zh": "用带标注的准确图表表示。"},
    {"term_en": "Explain", "term_zh": "解释", "ao": 2,
     "def_en": "Give a detailed account of causes, reasons or mechanisms.", "def_zh": "详细说明原因、理由或机制。"},
    {"term_en": "Analyse", "term_zh": "分析", "ao": 2,
     "def_en": "Break down to reveal essential elements, structure and relationships.", "def_zh": "分解以揭示基本要素、结构与关系。"},
    {"term_en": "Distinguish", "term_zh": "区分", "ao": 2,
     "def_en": "Make clear the differences between two or more concepts.", "def_zh": "阐明两个或多个概念之间的区别。"},
    {"term_en": "Compare", "term_zh": "比较", "ao": 3,
     "def_en": "Give an account of similarities between two or more items.", "def_zh": "说明两个或多个项目之间的相似之处。"},
    {"term_en": "Contrast", "term_zh": "对比", "ao": 3,
     "def_en": "Give an account of differences between two or more items.", "def_zh": "说明两个或多个项目之间的差异。"},
    {"term_en": "Discuss", "term_zh": "讨论", "ao": 3,
     "def_en": "Offer a balanced review of a range of arguments.", "def_zh": "对一系列论点给出平衡的评述。"},
    {"term_en": "Evaluate", "term_zh": "评估", "ao": 3,
     "def_en": "Make an appraisal by weighing strengths and limitations.", "def_zh": "权衡优势与局限做出评价。"},
    {"term_en": "Examine", "term_zh": "审视", "ao": 3,
     "def_en": "Consider an argument or concept in a way that uncovers assumptions and interrelationships.", "def_zh": "以揭示假设与相互关系的方式考虑某一论点或概念。"},
    {"term_en": "Justify", "term_zh": "论证", "ao": 3,
     "def_en": "Give valid reasons or evidence to support an answer or conclusion.", "def_zh": "给出有效理由或证据支持答案或结论。"},
    {"term_en": "Recommend", "term_zh": "建议", "ao": 3,
     "def_en": "Present an advisable course of action with appropriate evidence.", "def_zh": "以适当证据提出可采取的行动方案。"},
    {"term_en": "To what extent", "term_zh": "在多大程度上", "ao": 3,
     "def_en": "Consider the merits of an argument and reach a justified conclusion.", "def_zh": "考虑论点优劣并得出有理有据的结论。"},
]


# ---------------------------------------------------------------------------
# Textbook resource classification
# ---------------------------------------------------------------------------

def classify_textbook(name):
    """Classify a textbook file into resource_type."""
    n = name.lower()
    if "answers" in n:
        return "answers"
    if any(k in n for k in ("study guide", "revision guide", "revision notes",
                            "study and revision", "in a nutshell",
                            "prepare for success", "ib prepared")):
        return "study_guide"
    if any(k in n for k in ("workbook", "worksheets", "quantitative",
                            "skills and practice", "paper 3", "essentials")):
        return "workbook"
    if "diagram" in n:
        return "diagrams"
    return "textbook"


RESOURCE_TYPE_LABEL = {
    "textbook": {"zh": "主教材", "en": "Textbook"},
    "study_guide": {"zh": "学习指南 · 难点详解", "en": "Study Guide"},
    "workbook": {"zh": "练习册", "en": "Workbook"},
    "answers": {"zh": "答案", "en": "Answers"},
    "diagrams": {"zh": "图表集", "en": "Diagrams"},
}

# ---------------------------------------------------------------------------
# Exam technique: how to answer by assessment objective (AO)
# ---------------------------------------------------------------------------

ANSWER_GUIDE = [
    {"ao": 1, "name_zh": "知识理解 AO1",
     "how_zh": "准确写出定义、公式、图表，使用规范术语。对应命令词：Define / Describe / State / Outline / List / Draw。",
     "how_en": "State accurate definitions, formulas and diagrams with correct terminology (Define / Describe / State / Outline / List / Draw)."},
    {"ao": 2, "name_zh": "应用与分析 AO2",
     "how_zh": "解释机制与因果链条，用图表展开分析、引用数据。对应命令词：Explain / Analyse / Distinguish / Calculate。",
     "how_en": "Explain mechanisms and causal chains, develop analysis with diagrams and data (Explain / Analyse / Distinguish / Calculate)."},
    {"ao": 3, "name_zh": "综合与评估 AO3",
     "how_zh": "权衡利弊、结合现实案例、给出有理有据的结论（evaluation）。对应命令词：Evaluate / Discuss / Examine / To what extent。",
     "how_en": "Weigh strengths and limitations, use real-world examples, reach a justified conclusion (Evaluate / Discuss / Examine / To what extent)."},
]

# ---------------------------------------------------------------------------
# Per-topic exam guide: 答什么 (diagrams) + 怎么答 (exam tips / 易错点)
# Curated synthesis of the official markscheme & subject-report logic.
# ---------------------------------------------------------------------------

TOPIC_EXAM_GUIDE = {
    "1.1": {
        "diagrams": ["生产可能性曲线 PPC（稀缺性 · 机会成本 · 效率）"],
        "tips": ["机会成本是高频考点，必须写准定义“the next best alternative foregone”并联系 PPC 图。",
                 "沿 PPC 移动＝机会成本；曲线内＝无效率；曲线外＝当前不可达；PPC 外移＝经济增长。",
                 "区分“稀缺性 (scarcity)”与“短缺 (shortage)”，勿混淆。"]},
    "1.2": {
        "diagrams": [],
        "tips": ["区分 positive（实证，“是什么”）与 normative（规范，“应该怎样”）陈述。",
                 "ceteris paribus 是经济模型的前提假设，答题时点明它。"]},
    "2.1": {
        "diagrams": ["需求曲线（价格变动＝沿曲线移动 movement；非价格因素＝整条曲线平移 shift）"],
        "tips": ["必考：区分 movement along（价格本身）与 shift（收入、偏好、替代品/互补品价格、预期等）。",
                 "画图标注 P、Q 轴与 D 曲线，箭头方向正确。"]},
    "2.2": {
        "diagrams": ["供给曲线（同理区分 movement 与 shift）"],
        "tips": ["供给 shift 的因素：生产成本、技术、税收/补贴、天气、厂商数量、预期。",
                 "与需求对称作答，注意不要把供给曲线的移动方向搞反。"]},
    "2.3": {
        "diagrams": ["市场均衡图（均衡价量 · 超额需求/超额供给 · 消费者/生产者剩余）"],
        "tips": ["均衡点 Qd=Qs；超额需求→价格上升，超额供给→价格下降。",
                 "消费者剩余＝需求曲线下方、均衡价上方；生产者剩余＝供给曲线上方、均衡价下方。"]},
    "2.4": {
        "diagrams": [],
        "tips": ["理性假设的局限：信息有限、认知偏差（锚定、框架效应、损失厌恶）。",
                 "企业目标不止利润最大化：市场份额、企业社会责任、增长、收入最大化等。"]},
    "2.5": {
        "diagrams": ["PED 五种情况（弹性/单位/无弹性/完全弹性/完全无弹性）"],
        "tips": ["|PED|>1 弹性、<1 无弹性、=1 单位弹性；用总收入 TR=P×Q 判断（弹性商品降价增收）。",
                 "PED 决定因素：替代品多寡、必需品 vs 奢侈品、占收入比重、时间。"]},
    "2.6": {
        "diagrams": ["PES 图示（陡峭＝无弹性，平缓＝弹性）"],
        "tips": ["PES 决定因素：时间、闲置产能、库存、要素替代难易。"]},
    "2.7": {
        "diagrams": ["间接税（供给上移）· 补贴（供给下移）· 价格上限/下限"],
        "tips": ["税负归宿由弹性决定：弹性低的一方承担更多税负（需画图说明）。",
                 "价格上限→短缺；价格下限→过剩（如最低工资、农产品保护价）。"]},
    "2.8": {
        "diagrams": ["负外部性（MSC>MPC，过度生产）· 正外部性（MSB>MPB，供给不足）"],
        "tips": ["必考图：画出 MSC 与 MPC（或 MSB 与 MPB），标出市场均衡与社会最优的偏离及福利损失三角形。",
                 "区分“生产负外部性”与“消费负外部性”；对策：税收、补贴、监管、产权。"]},
    "2.9": {
        "diagrams": [],
        "tips": ["公共物品＝非竞争＋非排他（国防、路灯），市场供给不足→搭便车。",
                 "区分 public goods（公共物品）与 merit goods（优值品，政府鼓励消费）。"]},
    "2.10": {
        "diagrams": [],
        "tips": ["逆向选择（签约前，如二手车“劣币驱逐良币”）vs 道德风险（签约后，如投保后冒险）。",
                 "对策：信号 (signalling)、筛查 (screening)、监管、保险条款设计。"]},
    "2.11": {
        "diagrams": ["垄断图（MR 在 D 下方 · 利润最大化 MR=MC · 配置无效率）"],
        "tips": ["垄断利润最大化条件 MR=MC；垄断导致价高量少、配置效率损失 (deadweight loss)。",
                 "寡头＝相互依赖、博弈论、合谋 vs 价格战；进入壁垒类型。"]},
    "2.12": {
        "diagrams": [],
        "tips": ["equity（公平）≠ equality（平等）：公平关注分配正义，平等是结果相同。",
                 "市场可能产生不公平结果，需税收与转移支付等再分配政策。"]},
    "3.1": {
        "diagrams": ["收入循环流 circular flow（含漏出与注入）"],
        "tips": ["区分 GDP（境内生产）与 GNI（国民收入）；区分名义与实际 GDP（剔除通胀）。",
                 "GDP 的局限：不计家务/地下经济/环境成本、不反映收入分配与福利。"]},
    "3.2": {
        "diagrams": ["AD-AS 模型（AD、SRAS、LRAS 及移动）"],
        "tips": ["AD=C+I+G+(X−M)；区分 SRAS（成本因素）与 LRAS（生产能力）移动。",
                 "HL：凯恩斯 LRAS（水平段→上倾）vs 新古典 LRAS（垂直）；通胀缺口与通缩缺口。"]},
    "3.3": {
        "diagrams": ["AD-AS 说明通胀缺口 / 通缩缺口"],
        "tips": ["四大目标：低通胀、低失业、经济增长、收入公平；目标间存在冲突（如增长 vs 通胀、菲利普斯曲线权衡）。",
                 "通胀＝CPI 持续上涨；失业类型：摩擦性、结构性、周期性。"]},
    "3.4": {
        "diagrams": ["洛伦兹曲线 Lorenz curve + 基尼系数 Gini"],
        "tips": ["洛伦兹曲线越弯曲越不平等；基尼系数 0＝完全平等、1＝完全不平等。",
                 "区分绝对贫困 vs 相对贫困；税收（累进）与转移支付可再分配收入。"]},
    "3.5": {
        "diagrams": ["货币政策传导机制（利率→投资/消费→AD）"],
        "tips": ["扩张性＝降息/增货币→AD 右移；紧缩性＝加息→AD 左移。",
                 "HL 评估：时滞、信心、流动性陷阱、央行独立性。"]},
    "3.6": {
        "diagrams": ["财政政策作用于 AD（增支/减税→右移）"],
        "tips": ["扩张性＝增支/减税→AD 右移；自动稳定器＝累进税、失业救济。",
                 "HL 评估：挤出效应 (crowding out)、公共债务可持续性。"]},
    "3.7": {
        "diagrams": ["LRAS 右移（生产能力提升，无通胀增长）"],
        "tips": ["市场型（减税、去监管、私有化）vs 干预型（教育、基建、研发）。",
                 "供给侧政策可在不引发通胀的前提下促增长（LRAS 右移）。"]},
    "4.1": {
        "diagrams": ["比较优势（机会成本表）· 贸易收益"],
        "tips": ["比较优势＝较低的机会成本；专业化＋交换使双方受益。",
                 "绝对优势≠比较优势：用机会成本而非绝对生产力判断。"]},
    "4.2": {
        "diagrams": ["关税图（世界价＋关税→进口减少、税收与无谓损失）"],
        "tips": ["关税 vs 配额 vs 补贴 vs 行政壁垒：机制与图示各不同，能画图说明。"]},
    "4.3": {
        "diagrams": [],
        "tips": ["保护理由：幼稚产业、就业、战略安全、反倾销；代价：高价、低效、报复。",
                 "评估题要“两头写”：先给保护理由，再给自由贸易反驳，最后结论。"]},
    "4.4": {
        "diagrams": ["一体化阶梯（FTA→关税同盟→共同市场→货币联盟）"],
        "tips": ["各阶段特征递进：FTA（免关税）、关税同盟（＋共同对外关税）、共同市场（＋要素流动）、货币联盟（＋共同货币）。",
                 "HL：货币联盟利弊——丧失独立货币政策 vs 降低交易成本与汇率风险。"]},
    "4.5": {
        "diagrams": ["汇率供需图（本币升值/贬值）"],
        "tips": ["浮动汇率由供求决定；升值抑制出口、鼓励进口，贬值反之。",
                 "区分 appreciation/depreciation（浮动）与 revaluation/devaluation（固定）。"]},
    "4.6": {
        "diagrams": ["经常账户 vs 金融账户结构"],
        "tips": ["经常账户＝货物＋服务＋收入＋转移；金融账户＝资本流动；两者互为镜像。",
                 "HL：马歇尔-勒纳条件与 J 曲线（贬值短期恶化、长期改善贸易收支）。"]},
    "4.7": {
        "diagrams": [],
        "tips": ["可持续发展＝经济＋社会＋环境三者兼顾；增长 vs 可持续存在权衡。",
                 "联系负外部性（如污染）与公共池塘资源（过度开发）作答。"]},
    "4.8": {
        "diagrams": ["HDI 构成（收入＋预期寿命＋教育）"],
        "tips": ["HDI 三要素：人均收入、预期寿命、受教育程度；单一 GDP 指标有局限。"]},
    "4.9": {
        "diagrams": ["贫困循环 poverty cycle"],
        "tips": ["障碍：贫困陷阱、基础设施落后、制度薄弱、不平等、债务、外部冲击。"]},
    "4.10": {
        "diagrams": [],
        "tips": ["战略：贸易导向 vs 进口替代、吸引 FDI、对外援助 (ODA)、市场 vs 干预。",
                 "评估题：说明各战略利弊并给出情境化结论。"]},
}


# ---------------------------------------------------------------------------
# Diagram library: 图表解析与训练 (points / lines / areas)
# Each diagram: what it shows, line movements (线移动), point movements (点移动),
# area meanings (面积含义), and practice questions (q/opts/a/why).
# ---------------------------------------------------------------------------

DIAGRAMS = [
    # ---- Unit 1 ----
    {"id": "ppc", "name_en": "Production Possibility Curve (PPC)", "name_zh": "生产可能性曲线",
     "topic": "1.1",
     "what": "表示在资源与技术既定下，两种商品最大可能产出的组合。",
     "lines": "整条 PPC 外移（右移）＝经济增长（资源增加或技术进步）；内移＝衰退/资源减少。",
     "points": "沿 PPC 移动＝多生产一种商品的机会成本（放弃另一种）；曲线内点＝无效率；曲线外点＝当前不可达。",
     "areas": "PPC 与两轴围成的区域＝可达产出组合；曲线上的点＝充分有效使用资源。",
     "practice": [
        {"q": "经济在 PPC 内部某点生产，意味着？", "opts": ["资源未充分利用/无效率", "资源充分利用", "当前无法达到", "实现了经济增长"], "a": 0, "why": "PPC 内部=存在闲置资源或无效率。"},
        {"q": "技术进步使 PPC 如何变化？", "opts": ["整体向外移", "整体向内移", "沿曲线移动", "不变"], "a": 0, "why": "技术进步扩大生产能力，PPC 外移。"},
     ]},
    # ---- Unit 2 ----
    {"id": "demand_curve", "name_en": "Demand Curve", "name_zh": "需求曲线",
     "topic": "2.1",
     "what": "向下倾斜，表示价格与需求量负相关（需求定律）。",
     "lines": "价格变动→沿曲线移动 (movement along)；收入/偏好/替代品互补品价格/预期等→整条曲线平移 (shift)。",
     "points": "无（单曲线，重点区分 movement 与 shift）。",
     "areas": "无面积概念（到市场均衡才出现剩余）。",
     "practice": [
        {"q": "商品自身价格上升，需求量将？", "opts": ["沿需求曲线向左上移动", "需求曲线右移", "需求曲线左移", "供给曲线右移"], "a": 0, "why": "价格是内生变量，引起 movement along，而非 shift。"},
        {"q": "替代品价格上涨，本商品需求曲线将？", "opts": ["右移", "左移", "沿曲线移动", "不变"], "a": 0, "why": "替代品变贵→本商品需求增加，曲线右移（非价格因素）。"},
     ]},
    {"id": "supply_curve", "name_en": "Supply Curve", "name_zh": "供给曲线",
     "topic": "2.2",
     "what": "向上倾斜，表示价格与供给量正相关（供给定律）。",
     "lines": "价格变动→movement along；成本/技术/税收补贴/天气/厂商数量/预期→shift。",
     "points": "无。",
     "areas": "无面积概念。",
     "practice": [
        {"q": "生产成本上升，供给曲线将？", "opts": ["左移（减少供给）", "右移（增加供给）", "沿曲线移动", "不变"], "a": 0, "why": "成本上升→每一价格下供给减少，曲线左移。"},
     ]},
    {"id": "equilibrium", "name_en": "Market Equilibrium & Surplus", "name_zh": "市场均衡与剩余",
     "topic": "2.3",
     "what": "需求与供给交点决定均衡价格 P* 与均衡数量 Q*。",
     "lines": "需求或供给曲线移动→均衡点沿另一条曲线移动（如需求右移→均衡沿供给曲线右上移动）。",
     "points": "均衡点 (P*, Q*) 随曲线移动而改变；超额需求→价格上升，超额供给→价格下降。",
     "areas": "消费者剩余＝D 曲线下方、P* 上方的三角形；生产者剩余＝S 曲线上方、P* 下方的三角形；二者之和为社会总剩余。",
     "practice": [
        {"q": "需求曲线右移，均衡价格与数量将？", "opts": ["都上升", "都下降", "价升量降", "价降量升"], "a": 0, "why": "需求增加→均衡沿供给曲线右上移，价量齐升。"},
        {"q": "均衡价格上方、需求曲线下方的面积代表？", "opts": ["消费者剩余", "生产者剩余", "无谓损失", "税收"], "a": 0, "why": "该区域是消费者愿付与实际支付之差。"},
     ]},
    {"id": "ped", "name_en": "Price Elasticity of Demand (PED)", "name_zh": "需求价格弹性",
     "topic": "2.5",
     "what": "需求曲线陡峭程度表示需求量对价格的敏感度。",
     "lines": "弹性越足（曲线越平缓）→同样的价格变化引起更大的量变。",
     "points": "完全弹性＝水平线；完全无弹性＝垂直线。",
     "areas": "可用 TR=P×Q 判断：降价时，弹性商品总收入上升（量增幅度大于价降），无弹性商品总收入下降。",
     "practice": [
        {"q": "|PED|<1 的商品，降价将使总收入？", "opts": ["下降", "上升", "不变", "无法判断"], "a": 0, "why": "无弹性商品量增幅度小于价降，TR 下降。"},
     ]},
    {"id": "pes", "name_en": "Price Elasticity of Supply (PES)", "name_zh": "供给价格弹性",
     "topic": "2.6",
     "what": "供给曲线陡峭程度表示供给量对价格的敏感度。",
     "lines": "陡峭＝无弹性；平缓＝弹性。",
     "points": "从原点出发的直线 PES=1。",
     "areas": "无重点面积概念。",
     "practice": [
        {"q": "PES 较大的主要原因是？", "opts": ["长期、有闲置产能", "短期、产能满负荷", "需求无弹性", "替代品少"], "a": 0, "why": "时间越充裕、闲置产能越多，供给越易调整。"},
     ]},
    {"id": "tax", "name_en": "Indirect Tax & Incidence", "name_zh": "间接税与税负归宿",
     "topic": "2.7",
     "what": "对商品征税使供给曲线上移（幅度=税额）。",
     "lines": "供给曲线垂直上移（幅度为每单位税额）。",
     "points": "新均衡价 P2 与旧价 P1 之差＝消费者承担部分；税额−消费者承担＝生产者承担部分。",
     "areas": "税收收入＝税额 × Q2（长方形）；需求/供给弹性较小的一方承担更多税负。",
     "practice": [
        {"q": "需求完全无弹性时，谁承担全部税负？", "opts": ["消费者", "生产者", "双方平分", "政府"], "a": 0, "why": "需求无弹性→消费者无法通过减少购买避税，承担全部。"},
     ]},
    {"id": "subsidy", "name_en": "Subsidy", "name_zh": "补贴",
     "topic": "2.7",
     "what": "政府对生产者补贴使供给曲线下移（幅度=补贴额）。",
     "lines": "供给曲线垂直下移。",
     "points": "均衡价下降、均衡量增加；消费者与生产者共享补贴收益（取决于弹性）。",
     "areas": "补贴总成本＝补贴额 × Q2（长方形）。",
     "practice": [
        {"q": "对生产者的补贴使供给曲线？", "opts": ["下移（右移）", "上移（左移）", "不变", "需求曲线移动"], "a": 0, "why": "补贴降低生产者成本，供给增加。"},
     ]},
    {"id": "price_ceiling", "name_en": "Price Ceiling (Maximum Price)", "name_zh": "最高限价",
     "topic": "2.7",
     "what": "法定最高价，设定在均衡价之下才有效。",
     "lines": "无移动；水平价格线横切供求曲线。",
     "points": "限价 Pc 低于均衡价→需求量>供给量。",
     "areas": "短缺＝Qd−Qs；限价下产生配给/排队/黑市等无效率。",
     "practice": [
        {"q": "有效价格上限设在何处？", "opts": ["均衡价之下", "均衡价之上", "等于均衡价", "与均衡无关"], "a": 0, "why": "只有低于均衡价才产生约束力并造成短缺。"},
     ]},
    {"id": "price_floor", "name_en": "Price Floor (Minimum Price)", "name_zh": "最低限价",
     "topic": "2.7",
     "what": "法定最低价，设定在均衡价之上才有效。",
     "lines": "无移动；水平价格线横切供求曲线。",
     "points": "限价 Pf 高于均衡价→供给量>需求量。",
     "areas": "过剩＝Qs−Qd（如最低工资造成失业、农产品过剩）。",
     "practice": [
        {"q": "有效价格下限（如最低工资）导致？", "opts": ["过剩（失业）", "短缺", "均衡", "无影响"], "a": 0, "why": "最低价高于均衡价→供给量>需求量，形成过剩。"},
     ]},
    {"id": "neg_ext_prod", "name_en": "Negative Externality of Production", "name_zh": "生产负外部性",
     "topic": "2.8",
     "what": "生产成本溢出到第三方（如污染），MSC > MPC。",
     "lines": "MSC 曲线在 MPC 之上，差距＝外部成本。",
     "points": "市场均衡（MPC=D）产量高于社会最优（MSC=D）产量。",
     "areas": "过度生产部分（Qm 与 Q* 之间）MSC 高于 MSB 的三角形＝无谓损失（福利损失）。",
     "practice": [
        {"q": "生产负外部性下，市场产量相对社会最优是？", "opts": ["过度生产", "供给不足", "恰好最优", "无法判断"], "a": 0, "why": "MSC>MPC，市场忽视外部成本而过度生产。"},
     ]},
    {"id": "neg_ext_cons", "name_en": "Negative Externality of Consumption", "name_zh": "消费负外部性",
     "topic": "2.8",
     "what": "消费行为溢出成本（如二手烟），MPB > MSB。",
     "lines": "MPB 曲线在 MSB 之上，差距＝外部成本。",
     "points": "市场均衡（MPB=S）消费量高于社会最优（MSB=S）。",
     "areas": "过度消费部分的福利损失三角形。",
     "practice": [
        {"q": "消费负外部性（如吸烟）下 MSB 与 MPB 的关系？", "opts": ["MSB < MPB", "MSB > MPB", "MSB = MPB", "无关"], "a": 0, "why": "消费有外部成本，社会边际收益低于私人边际收益。"},
     ]},
    {"id": "pos_ext", "name_en": "Positive Externality", "name_zh": "正外部性",
     "topic": "2.8",
     "what": "消费或生产产生溢出收益（如教育、疫苗），MSB > MPB（消费）或 MSC < MPC（生产）。",
     "lines": "MSB 在 MPB 之上（消费）；MPC 在 MSC 之上（生产）。",
     "points": "市场均衡产量低于社会最优产量（供给不足）。",
     "areas": "供给不足部分的潜在福利损失三角形。",
     "practice": [
        {"q": "正外部性下，市场产量相对社会最优是？", "opts": ["供给不足", "过度生产", "恰好最优", "无法判断"], "a": 0, "why": "市场低估社会收益，供给不足。"},
     ]},
    {"id": "monopoly", "name_en": "Monopoly Profit Maximisation", "name_zh": "垄断利润最大化 (HL)",
     "topic": "2.11",
     "what": "垄断者面对整个市场需求，MR 曲线在 D 曲线下方。",
     "lines": "MR 曲线斜率是 D 的两倍（线性需求下）。",
     "points": "利润最大化点＝MR=MC；由该点向上到需求曲线定价格 Pm。",
     "areas": "垄断产量低于完全竞争、价格更高；两者之差形成配置无效率（无谓损失三角形）。",
     "practice": [
        {"q": "垄断者利润最大化条件？", "opts": ["MR = MC", "P = MC", "P = AC", "MR = AR"], "a": 0, "why": "任何企业利润最大化都在 MR=MC。"},
     ]},
    # ---- Unit 3 ----
    {"id": "circular_flow", "name_en": "Circular Flow of Income", "name_zh": "收入循环流",
     "topic": "3.1",
     "what": "家庭与企业之间的收入、支出、要素流动。",
     "lines": "无曲线（流程图）。",
     "points": "漏出 (leakages)＝储蓄、税收、进口；注入 (injections)＝投资、政府支出、出口。",
     "areas": "无。",
     "practice": [
        {"q": "下列哪项是循环流的注入？", "opts": ["投资", "储蓄", "税收", "进口"], "a": 0, "why": "投资是注入，储蓄/税收/进口是漏出。"},
     ]},
    {"id": "ad", "name_en": "Aggregate Demand (AD)", "name_zh": "总需求",
     "topic": "3.2",
     "what": "各价格水平下经济体对总产出的需求量，向下倾斜。",
     "lines": "AD 右移＝总需求增加（消费/投资/政府支出/出口增加、或利率下降等）。",
     "points": "沿 AD 移动＝价格水平变化（财富效应、利率效应、汇率效应）。",
     "areas": "AD=C+I+G+(X−M)。",
     "practice": [
        {"q": "AD 曲线右移最可能由？", "opts": ["政府减税", "利率上升", "本币升值", "价格水平上升"], "a": 0, "why": "减税刺激消费，AD 右移；其余使 AD 左移或沿曲线移动。"},
     ]},
    {"id": "sras", "name_en": "Short-run Aggregate Supply (SRAS)", "name_zh": "短期总供给",
     "topic": "3.2",
     "what": "短期各价格水平下厂商愿供给的总产出，向上倾斜。",
     "lines": "SRAS 左移＝成本上升（工资/原料/能源/税收）；右移＝成本下降。",
     "points": "沿 SRAS 移动＝价格水平变化。",
     "areas": "无重点面积。",
     "practice": [
        {"q": "油价大幅上涨将导致 SRAS？", "opts": ["左移", "右移", "沿曲线移动", "不变"], "a": 0, "why": "能源成本上升→供给减少，SRAS 左移（滞胀）。"},
     ]},
    {"id": "lras", "name_en": "Long-run Aggregate Supply (LRAS)", "name_zh": "长期总供给 (HL)",
     "topic": "3.2",
     "what": "长期潜在产出（充分就业产出）的曲线。",
     "lines": "新古典 LRAS＝垂直（潜在产出）；凯恩斯 LRAS＝水平段→上倾→垂直。",
     "points": "LRAS 右移＝生产能力提升（供给侧政策）。",
     "areas": "无。",
     "practice": [
        {"q": "新古典 LRAS 曲线形状？", "opts": ["垂直", "水平", "向下倾斜", "上倾"], "a": 0, "why": "新古典认为长期产出由生产能力决定，与价格无关。"},
     ]},
    {"id": "adas_gap", "name_en": "AD-AS Equilibrium & Gaps", "name_zh": "AD-AS 均衡与缺口",
     "topic": "3.2",
     "what": "AD 与 SRAS 交点决定短期均衡价格水平与实际产出。",
     "lines": "AD 或 SRAS 移动改变均衡。",
     "points": "通胀缺口＝均衡产出>潜在产出；通缩（衰退）缺口＝均衡产出<潜在产出。",
     "areas": "缺口＝实际产出与潜在产出（LRAS）之间的水平距离。",
     "practice": [
        {"q": "衰退缺口（recessionary gap）意味着？", "opts": ["实际产出<潜在产出，失业上升", "实际产出>潜在产出", "充分就业", "通胀压力"], "a": 0, "why": "衰退缺口=AD 不足，产出低于潜在水平。"},
     ]},
    {"id": "business_cycle", "name_en": "Business Cycle", "name_zh": "经济周期",
     "topic": "3.2",
     "what": "实际产出围绕趋势线的波动。",
     "lines": "趋势线＝潜在增长路径。",
     "points": "四个阶段：扩张→顶峰→收缩→谷底。",
     "areas": "无。",
     "practice": [
        {"q": "经济周期的正确顺序？", "opts": ["扩张→顶峰→收缩→谷底", "顶峰→扩张→谷底→收缩", "收缩→谷底→顶峰→扩张", "谷底→收缩→扩张→顶峰"], "a": 0, "why": "标准四阶段循环。"},
     ]},
    {"id": "lorenz", "name_en": "Lorenz Curve & Gini", "name_zh": "洛伦兹曲线与基尼系数",
     "topic": "3.4",
     "what": "累计人口比例对应累计收入比例。",
     "lines": "45° 线＝完全平等；越弯曲＝越不平等。",
     "points": "无。",
     "areas": "基尼系数＝45°线与洛伦兹曲线之间面积 ÷ 45°线下方三角形面积。",
     "practice": [
        {"q": "基尼系数越接近 1，说明？", "opts": ["收入越不平等", "收入越平等", "经济增长越快", "失业率越高"], "a": 0, "why": "基尼系数 0=平等，1=完全不平等。"},
     ]},
    {"id": "monetary_transmission", "name_en": "Monetary Policy Transmission", "name_zh": "货币政策传导",
     "topic": "3.5",
     "what": "利率变动→投资/消费→AD 移动。",
     "lines": "降息→AD 右移；加息→AD 左移。",
     "points": "在 AD-AS 图中观察均衡变动。",
     "areas": "无。",
     "practice": [
        {"q": "扩张性货币政策通过什么传导？", "opts": ["降息→投资/消费↑→AD 右移", "加息→AD 左移", "增税→AD 左移", "减支→AD 左移"], "a": 0, "why": "扩张性货币政策=降息，刺激总需求。"},
     ]},
    {"id": "supply_side", "name_en": "Supply-side Policy (LRAS shift)", "name_zh": "供给侧政策",
     "topic": "3.7",
     "what": "提高生产能力使 LRAS 右移。",
     "lines": "LRAS 右移。",
     "points": "在 AD 不变下，价格水平下降、产出增加。",
     "areas": "无。",
     "practice": [
        {"q": "成功的供给侧政策使？", "opts": ["LRAS 右移，潜在产出增加", "AD 左移", "SRAS 左移", "仅价格上升"], "a": 0, "why": "供给侧政策提升生产能力，LRAS 右移。"},
     ]},
    # ---- Unit 4 ----
    {"id": "comparative_advantage", "name_en": "Comparative Advantage (PPF)", "name_zh": "比较优势",
     "topic": "4.1",
     "what": "两国 PPF 斜率（机会成本）不同，决定比较优势。",
     "lines": "PPF 斜率＝机会成本。",
     "points": "专业化生产有比较优势的商品，再交换使双方受益。",
     "areas": "无。",
     "practice": [
        {"q": "比较优势由什么决定？", "opts": ["较低的机会成本", "较高的绝对产出", "更先进的技术", "更多资源"], "a": 0, "why": "比较优势看机会成本，而非绝对生产力。"},
     ]},
    {"id": "tariff", "name_en": "Tariff Diagram", "name_zh": "关税图",
     "topic": "4.2",
     "what": "对进口征税，国内价格从世界价 Pw 上升到 Pw+t。",
     "lines": "世界价为水平线（小国假设）；征税使国内价上移。",
     "points": "进口量从 Q1Q4 减少到 Q2Q3。",
     "areas": "长方形＝政府关税收入；两个三角形＝无谓损失（生产无效率+消费损失）。",
     "practice": [
        {"q": "关税图中两个三角形代表？", "opts": ["无谓损失", "政府收入", "消费者剩余增加", "生产者剩余增加"], "a": 0, "why": "关税导致配置无效率，产生两个福利损失三角形。"},
     ]},
    {"id": "exchange_rate", "name_en": "Exchange Rate (Floating)", "name_zh": "浮动汇率",
     "topic": "4.5",
     "what": "汇率由本币的供求决定。",
     "lines": "需求（出口/资本流入）右移→本币升值；供给（进口/资本流出）右移→本币贬值。",
     "points": "均衡汇率＝供求交点。",
     "areas": "无。",
     "practice": [
        {"q": "本国出口增加，本币将？", "opts": ["升值", "贬值", "不变", "无法判断"], "a": 0, "why": "出口增加→本币需求增加→升值。"},
     ]},
    {"id": "jcurve", "name_en": "J-Curve Effect", "name_zh": "J 曲线效应 (HL)",
     "topic": "4.6",
     "what": "本币贬值后贸易收支先恶化后改善的时间路径。",
     "lines": "曲线先下降后上升，呈 J 形。",
     "points": "短期：合同价格固定，进口成本上升→恶化；长期：数量调整→改善。",
     "areas": "无（时间序列图）。",
     "practice": [
        {"q": "J 曲线解释贬值后贸易收支？", "opts": ["先恶化后改善", "先改善后恶化", "立即改善", "无影响"], "a": 0, "why": "短期价格效应主导、长期数量效应主导。"},
     ]},
    {"id": "poverty_cycle", "name_en": "Poverty Cycle", "name_zh": "贫困循环",
     "topic": "4.9",
     "what": "低收入→低储蓄→低投资→低增长→低收入的恶性循环。",
     "lines": "无（流程图）。",
     "points": "各环节相互强化。",
     "areas": "无。",
     "practice": [
        {"q": "贫困循环的核心机制？", "opts": ["低收入→低储蓄→低投资→低增长", "高储蓄→高投资", "高收入→低增长", "无关"], "a": 0, "why": "贫困陷阱的自我强化循环。"},
     ]},
]


